apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: matomo
  namespace: 26e83e-prod
  labels:
    app: matomo
    name: matomo
    service: matomo
    template: matomo-template
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: matomo
    deploymentconfig: matomo
    template: matomo-template
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - matomo
      from:
        kind: ImageStreamTag
        name: matomo:prod
        namespace: 26e83e-tools
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - matomo-proxy
      from:
        kind: ImageStreamTag
        name: matomo-proxy:prod
        namespace: 26e83e-tools
  template:
    metadata:
      labels:
        app: matomo
        deploymentconfig: matomo
        name: matomo
        template: matomo-template
    spec:
      volumes:
        - name: matomo-source
          emptyDir: {}
        - name: matomo
          persistentVolumeClaim:
            claimName: matomo
      containers:
      - name: matomo
        image: matomo
        imagePullPolicy: Always
        ports:
          - containerPort: 9000
        volumeMounts:
          - name: matomo-source
            mountPath: /var/www/html
          - name: matomo
            mountPath: /var/www/html/config
      - name: matomo-proxy
        image: image-registry.openshift-image-registry.svc:5000/26e83e-tools/matomo-proxy@sha256:76d7f6f07975dca65818684a3362f91a39690b333ad346d549b11a3691dea59a
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: matomo-source
            mountPath: /var/www/html
