kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: matomo
  namespace: 26e83e-prod
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: matomo
    name: matomo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: netapp-file-standard
  volumeMode: Filesystem
