apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: matomo
  annotations:
    description: Template for deploying matomo, an open source web analytics platform.
labels:
  app: matomo
  name: matomo
  service: matomo
  template: matomo-template
parameters:
  - name: PVC_NAME
    description: Name of the PVC to use for Matomo data storage, in dev and test use matomo-config, in prod use matomo
    required: true
objects:
# ----------------- DEPLOYMENT -----------------
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: matomo
      name: matomo
      annotations:
        image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"matomo:latest","namespace":"26e83e-tools"},"fieldPath":"spec.template.spec.containers[?(@.name==\"matomo\")].image","pause":false}, {"from":{"kind":"ImageStreamTag","name":"matomo:proxy","namespace":"26e83e-tools"},"fieldPath":"spec.template.spec.containers[?(@.name==\"matomo-proxy\")].image","pause":false}]'
    spec:
      selector:
        matchLabels:
          app: matomo
          template: matomo-template
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            name: matomo
          name: matomo
        spec:
          containers:
          - name: matomo
            image: image-registry.openshift-image-registry.svc:5000/26e83e-tools/matomo:latest
            imagePullPolicy: Always
            ports:
            - containerPort: 9000
              protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/www/html
              name: matomo-source
            - mountPath: /var/www/html/config
              name: matomo
          - name: matomo-proxy
            image: image-registry.openshift-image-registry.svc:5000/26e83e-tools/matomo-proxy:latest
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 8080
              protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/www/html
              name: matomo-source
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - emptyDir: {}
            name: matomo-source
          - name: matomo
            persistentVolumeClaim:
              claimName: ${PVC_NAME}
# ----------------- PVC -----------------
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${PVC_NAME}
      finalizers:
        - kubernetes.io/pvc-protection
      labels:
        app: matomo
        name: ${PVC_NAME}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: netapp-file-standard
      volumeMode: Filesystem
