# Generated by Django 2.1.8 on 2019-04-12 01:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone

import gwells.db_comments.model_mixins
import submissions.data_migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WellActivityCode',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_user', models.CharField(max_length=60)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=utc))),
                ('code', models.CharField(db_column='well_activity_type_code', editable=False, max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'well_activity_code',
                'ordering': ['display_order', 'description'],
            },
            bases=(models.Model, gwells.db_comments.model_mixins.DBComments),
        ),
        migrations.RunPython(
            code=submissions.data_migrations.load_well_activity_codes,
            reverse_code=submissions.data_migrations.unload_well_activity_codes,
        ),
    ]
