# Generated by Django 2.1.7 on 2019-02-13 00:35

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def insert_well_activity_code(apps, schema_editor):
    data = {
        'CON': {
            "description": "Construction report",
            "display_order": 1
        },
        'ALT': {
            "description": "Alteration report",
            "display_order": 2
        },
        'DEC': {
            "description": "Decommission report",
            "display_order": 3
        },
        'STAFF_EDIT': {
            "description": "Staff edit",
            "display_order": 4
        },
        'LEGACY': {
            "description": "Legacy record",
            "display_order": 5
        }
    }
    WellActivityCode = apps.get_model('submissions', 'WellActivityCode')

    for (key, value) in data.items():
        WellActivityCode.objects.update_or_create(code=key, defaults=value)


def revert(apps, schema_editor):
    # Deleting these could be dangerous (we don't want to cascade delete the submissions),
    # so we do nothing here.
    logger.warn('Not deleting WellActivityCode records! That would be dangerous.')


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20180815_2216'),
    ]

    operations = [
        migrations.RunPython(insert_well_activity_code, revert),
    ]
