# Generated by Django 2.1.7 on 2019-02-12 06:31

import logging

from django.db import migrations


logger = logging.getLogger(__name__)


def fix_spelling(apps, schema_editor):
    WellActivityCode = apps.get_model('submissions', 'WellActivityCode')
    record = WellActivityCode.objects.get(code='DEC')
    record.description = 'Decommission report'
    record.save()


def revert(apps, schema_editor):
    logger.warn('Not bothering to revert back to spelling mistake!')


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20180815_2216'),
    ]

    operations = [
        migrations.RunPython(fix_spelling, revert),
    ]
