# Generated by Django 2.1.7 on 2019-03-07 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_fix_spelling_20190212_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellactivitycode',
            name='create_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='wellactivitycode',
            name='effective_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='wellactivitycode',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)),
        ),
        migrations.AlterField(
            model_name='wellactivitycode',
            name='update_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
