# Generated by Django 2.1.8 on 2019-04-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_auto_20190309_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellactivitycode',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
    ]
