# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-25 06:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gwells', '0073_auto_20180108_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('who_created', models.CharField(max_length=30)),
                ('when_created', models.DateTimeField(blank=True, null=True)),
                ('who_updated', models.CharField(max_length=30, null=True)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('appl_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Application UUID, hidden from users')),
                ('file_no', models.CharField(blank=True, max_length=25, null=True, verbose_name='ORCS File # reference.')),
                ('over19_ind', models.BooleanField(default=True)),
                ('registrar_notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Registrar Notes, for internal use only.')),
                ('reason_denied', models.CharField(blank=True, max_length=255, null=True, verbose_name='Free form text explaining reason for denial.')),
            ],
            options={
                'verbose_name_plural': 'Applications for Driller or Pump Installer',
                'db_table': 'gwells_registry_application',
            },
        ),
        migrations.CreateModel(
            name='ContactAt',
            fields=[
                ('who_created', models.CharField(max_length=30)),
                ('when_created', models.DateTimeField(blank=True, null=True)),
                ('who_updated', models.CharField(max_length=30, null=True)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('contact_at_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Contact At UUID, hidden from users')),
                ('tel', models.CharField(blank=True, max_length=12, null=True, verbose_name='Contact telephone number')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email adddress')),
                ('effective_date', models.DateField(default=datetime.date.today)),
                ('expired_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
            options={
                'verbose_name_plural': 'Person contact details for a given Company',
                'db_table': 'gwells_contact_at',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('who_created', models.CharField(max_length=30)),
                ('when_created', models.DateTimeField(blank=True, null=True)),
                ('who_updated', models.CharField(max_length=30, null=True)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('org_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Organization UUID, hidden from users')),
                ('name', models.CharField(max_length=200)),
                ('street_address', models.CharField(blank=True, max_length=100, verbose_name='Street Address')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Town/City')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Postal Code')),
                ('main_tel', models.CharField(blank=True, max_length=12, null=True, verbose_name='Company main telephone number')),
                ('fax_tel', models.CharField(blank=True, max_length=12, null=True, verbose_name='Facsimile telephone number')),
                ('province_state', models.ForeignKey(db_column='province_state_guid', on_delete=django.db.models.deletion.CASCADE, to='gwells.ProvinceState', verbose_name='Province/State')),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'db_table': 'gwells_organization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('who_created', models.CharField(max_length=30)),
                ('when_created', models.DateTimeField(blank=True, null=True)),
                ('who_updated', models.CharField(max_length=30, null=True)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('person_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Person UUID, hidden from users')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Persons',
                'db_table': 'gwells_person',
                'ordering': ['first_name', 'surname'],
            },
        ),
        migrations.CreateModel(
            name='QualificationAppliedFor',
            fields=[
                ('who_created', models.CharField(max_length=30)),
                ('when_created', models.DateTimeField(blank=True, null=True)),
                ('who_updated', models.CharField(max_length=30, null=True)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('qual_appl_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Qualification XREF UUID, hidden from users')),
                ('application', models.ForeignKey(db_column='appl_guid', on_delete=django.db.models.deletion.CASCADE, to='registry.Person', verbose_name='Application Reference')),
            ],
            options={
                'verbose_name_plural': 'Application Qualification being applied for',
                'db_table': 'gwells_registry_qual_applied',
            },
        ),
        migrations.CreateModel(
            name='RegistryApplicationType',
            fields=[
                ('who_created', models.CharField(max_length=30)),
                ('when_created', models.DateTimeField(blank=True, null=True)),
                ('who_updated', models.CharField(max_length=30, null=True)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('registry_appl_type_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('subcode', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gwells_registry_appl_type',
                'ordering': ['sort_order', 'description'],
            },
        ),
        migrations.CreateModel(
            name='RegistryQualifiedFor',
            fields=[
                ('who_created', models.CharField(max_length=30)),
                ('when_created', models.DateTimeField(blank=True, null=True)),
                ('who_updated', models.CharField(max_length=30, null=True)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('registry_qual_for_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
                ('registry_appl_type', models.ForeignKey(blank=True, db_column='registry_appl_type_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.RegistryApplicationType')),
            ],
            options={
                'db_table': 'gwells_registry_qualified_for',
                'ordering': ['sort_order', 'description'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='registryapplicationtype',
            unique_together=set([('code', 'subcode')]),
        ),
        migrations.AddField(
            model_name='qualificationappliedfor',
            name='qualification',
            field=models.ForeignKey(db_column='registry_qual_for_guid', on_delete=django.db.models.deletion.CASCADE, to='registry.RegistryQualifiedFor', verbose_name='Qualification being applied for'),
        ),
        migrations.AddField(
            model_name='contactat',
            name='org',
            field=models.ForeignKey(blank=True, db_column='org_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.Organization', verbose_name='Company Reference'),
        ),
        migrations.AddField(
            model_name='contactat',
            name='person',
            field=models.ForeignKey(blank=True, db_column='person_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.Person', verbose_name='Person Reference'),
        ),
        migrations.AddField(
            model_name='application',
            name='person',
            field=models.ForeignKey(db_column='person_guid', on_delete=django.db.models.deletion.CASCADE, to='registry.Person', verbose_name='Person Reference'),
        ),
    ]
