# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='Town/City'),
        ),
    ]
