# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='well_class',
            field=models.ForeignKey(db_column='registries_well_class_code', on_delete=django.db.models.deletion.PROTECT, to='registries.WellClassCode'),
        ),
    ]
