# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='activitycode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='applicationstatuscode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='applicationstatuscode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='classificationappliedfor',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='classificationappliedfor',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='contactat',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='contactat',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='organization',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='person',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qualificationcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='qualificationcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='register',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='registriesapplication',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='registriesapplication',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='registriesapplicationstatus',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='registriesapplicationstatus',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='registriesremovalreason',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='registriesremovalreason',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='registriesstatuscode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='registriesstatuscode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='subactivitycode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='subactivitycode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
