# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitycode',
            options={'ordering': ['display_order', 'description'], 'verbose_name_plural': 'Activity codes'},
        ),
        migrations.AlterModelOptions(
            name='applicationstatuscode',
            options={'ordering': ['display_order', 'description'], 'verbose_name_plural': 'Application status codes'},
        ),
        migrations.AlterModelOptions(
            name='classificationappliedfor',
            options={'verbose_name_plural': 'Application classifications'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'Contact info'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name', 'surname'], 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='qualificationcode',
            options={'ordering': ['display_order', 'description'], 'verbose_name_plural': 'Qualification codes'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name_plural': 'Registrations'},
        ),
        migrations.AlterModelOptions(
            name='registriesapplication',
            options={'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='registriesapplicationstatus',
            options={'ordering': ['application', 'effective_date'], 'verbose_name_plural': 'Application status'},
        ),
        migrations.AlterModelOptions(
            name='registriesremovalreason',
            options={'ordering': ['display_order', 'description'], 'verbose_name_plural': 'Registry removal reasons'},
        ),
        migrations.AlterModelOptions(
            name='registriesstatuscode',
            options={'ordering': ['display_order', 'description'], 'verbose_name_plural': 'Registry status codes'},
        ),
        migrations.AlterModelOptions(
            name='subactivitycode',
            options={'ordering': ['display_order', 'description'], 'verbose_name_plural': 'Subactivity codes'},
        ),
        migrations.RemoveField(
            model_name='qualificationcode',
            name='registries_subactivity',
        ),
        migrations.AddField(
            model_name='registriesapplication',
            name='qualifications',
            field=models.ManyToManyField(to='registries.QualificationCode'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='person',
            field=models.ForeignKey(db_column='person_guid', default='', on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='registries.Person', verbose_name='Person Reference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='registries.Organization'),
        ),
    ]
