# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactat',
            name='org',
            field=models.ForeignKey(db_column='org_guid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='registries.Organization', verbose_name='Company Reference'),
        ),
        migrations.AlterField(
            model_name='contactat',
            name='person',
            field=models.ForeignKey(db_column='person_guid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='registries.Person', verbose_name='Person Reference'),
        ),
    ]
