# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillerRegister',
            fields=[
                ('registration_no', models.CharField(blank=True, max_length=15, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('status_code', models.CharField(max_length=10)),
                ('register_removal_date', models.DateField(blank=True, null=True, verbose_name='Date of Removal from Register')),
                ('register_removal_reason', models.DateField(blank=True, null=True)),
                ('activity_code', models.CharField(max_length=10, unique=True)),
                ('file_no', models.CharField(blank=True, max_length=25, null=True, verbose_name='ORCS File # reference.')),
                ('over19_ind', models.BooleanField(default=True)),
                ('registrar_notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Registrar Notes, for internal use only.')),
                ('reason_denied', models.CharField(blank=True, max_length=255, null=True, verbose_name='Free form text explaining reason for denial.')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('contact_tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact telephone number')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email adddress')),
                ('org_name', models.CharField(max_length=200)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Address')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Town/City')),
                ('prov_state_code', models.CharField(max_length=10, unique=True)),
                ('prov_state_desc', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Code')),
                ('main_tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='Company main telephone number')),
                ('fax_tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='Facsimile telephone number')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name="Orgnization's Website")),
                ('register_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Register UUID, hidden from users')),
                ('reg_create_user', models.CharField(max_length=30)),
                ('reg_create_date', models.DateTimeField(blank=True, null=True)),
                ('reg_update_user', models.CharField(max_length=30, null=True)),
                ('reg_update_date', models.DateTimeField(blank=True, null=True)),
                ('status_create_user', models.CharField(max_length=30)),
                ('status_create_date', models.DateTimeField(blank=True, null=True)),
                ('status_update_user', models.CharField(max_length=30, null=True)),
                ('status_update_date', models.DateTimeField(blank=True, null=True)),
                ('appl_create_user', models.CharField(max_length=30)),
                ('appl_create_date', models.DateTimeField(blank=True, null=True)),
                ('appl_update_user', models.CharField(max_length=30, null=True)),
                ('appl_update_date', models.DateTimeField(blank=True, null=True)),
                ('removal_create_user', models.CharField(max_length=30)),
                ('removal_create_date', models.DateTimeField(blank=True, null=True)),
                ('removal_update_user', models.CharField(max_length=30, null=True)),
                ('removal_update_date', models.DateTimeField(blank=True, null=True)),
                ('act_create_user', models.CharField(max_length=30)),
                ('act_create_date', models.DateTimeField(blank=True, null=True)),
                ('act_update_user', models.CharField(max_length=30, null=True)),
                ('act_update_date', models.DateTimeField(blank=True, null=True)),
                ('person_guid', models.UUIDField(editable=False, verbose_name='Person UUID, hidden from users')),
                ('per_create_user', models.CharField(max_length=30)),
                ('per_create_date', models.DateTimeField(blank=True, null=True)),
                ('per_update_user', models.CharField(max_length=30, null=True)),
                ('per_update_date', models.DateTimeField(blank=True, null=True)),
                ('contact_at_guid', models.UUIDField(editable=False, verbose_name='ContactAt UUID, hidden from users')),
                ('contact_effective_date', models.DateTimeField(blank=True, null=True)),
                ('contact_expired_date', models.DateTimeField(blank=True, null=True)),
                ('contact_create_user', models.CharField(max_length=30)),
                ('contact_create_date', models.DateTimeField(blank=True, null=True)),
                ('contact_update_user', models.CharField(max_length=30, null=True)),
                ('contact_update_date', models.DateTimeField(blank=True, null=True)),
                ('org_guid', models.UUIDField(editable=False, verbose_name='Organization UUID, hidden from users')),
                ('org_create_user', models.CharField(max_length=30)),
                ('org_create_date', models.DateTimeField(blank=True, null=True)),
                ('org_update_user', models.CharField(max_length=30, null=True)),
                ('org_update_date', models.DateTimeField(blank=True, null=True)),
                ('prov_guid', models.UUIDField(editable=False, verbose_name='ProvinceStateCode UUID, hidden from users')),
                ('prov_create_user', models.CharField(max_length=30)),
                ('prov_create_date', models.DateTimeField(blank=True, null=True)),
                ('prov_update_user', models.CharField(max_length=30, null=True)),
                ('prov_update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registries_driller_register',
                'managed': False,
            },
        ),
    ]
