# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-03 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contact_cell',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact cell number'),
        ),
        migrations.AddField(
            model_name='person',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email adddress'),
        ),
        migrations.AddField(
            model_name='person',
            name='contact_tel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact telephone number'),
        ),
    ]
