# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0002_auto_20180213_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registriesapplication',
            name='person',
            field=models.ForeignKey(db_column='person_guid', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='registries.Person', verbose_name='Person Reference'),
        ),
    ]
