# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0002_organization_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address'),
        ),
    ]
