# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0002_auto_20180327_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='registriesapplication',
            name='subactivity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='registries.SubactivityCode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registriesapplicationstatus',
            name='application',
            field=models.ForeignKey(db_column='application_guid', on_delete=django.db.models.deletion.CASCADE, related_name='status_set', to='registries.RegistriesApplication', verbose_name='Application Reference'),
        ),
    ]
