# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0002_auto_20180405_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='fax_tel',
            field=models.CharField(max_length=15, null=True, verbose_name='Fax number'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='main_tel',
            field=models.CharField(max_length=15, null=True, verbose_name='Telephone number'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(max_length=10, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='street_address',
            field=models.CharField(max_length=100, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website_url',
            field=models.URLField(null=True, verbose_name='Website'),
        ),
    ]
