# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-02 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0003_auto_20180202_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationappliedfor',
            name='primary_certificate_authority',
            field=models.ForeignKey(db_column='certifying_org_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='registries.Organization', verbose_name='Certifying Organization'),
        ),
    ]
