# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0003_auto_20180507_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='contact_email',
        ),
    ]
