# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0003_auto_20180327_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registriesapplication',
            name='subactivity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='registries.SubactivityCode'),
        ),
    ]
