# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0004_auto_20180328_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registriesapplication',
            old_name='person',
            new_name='registration',
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Town/City'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='main_tel',
            field=models.CharField(default='', max_length=15, null=True, verbose_name='Telephone number'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='Postal Code'),
        ),
    ]
