# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0004_auto_20180406_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='subactivity',
            field=models.ForeignKey(db_column='registries_subactivity_code', on_delete=django.db.models.deletion.PROTECT, related_name='qualification_set', to='registries.SubactivityCode'),
        ),
    ]
