# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0005_auto_20180406_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registriesapplicationstatus',
            name='application',
            field=models.ForeignKey(db_column='application_guid', on_delete=django.db.models.deletion.CASCADE, related_name='status_set', to='registries.RegistriesApplication', verbose_name='Application Reference'),
        ),
    ]
