# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-03 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0005_auto_20180203_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactat',
            name='org',
            field=models.ForeignKey(db_column='org_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='registries.Organization', verbose_name='Company Reference'),
        ),
        migrations.AlterField(
            model_name='contactat',
            name='person',
            field=models.ForeignKey(db_column='person_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='registries.Person', verbose_name='Person Reference'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='province_state',
            field=models.ForeignKey(db_column='province_state_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.ProvinceState', verbose_name='Province/State'),
        ),
    ]
