# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0005_auto_20180404_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='fax_tel',
            field=models.CharField(max_length=15, null=True, verbose_name='Fax number'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='main_tel',
            field=models.CharField(max_length=15, null=True, verbose_name='Telephone number'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(max_length=10, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='province_state',
            field=models.ForeignKey(db_column='province_state_code', default='BC', on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='gwells.ProvinceStateCode', verbose_name='Province/State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='website_url',
            field=models.URLField(null=True, verbose_name='Website'),
        ),
    ]
