# version: '3.7'
# NOTE For Red Hat or other images on the internal registry please login as follows:
#     1. Be logged into the BC Gov OpenShift Console
#          https://console.pathfinder.gov.bc.ca:8443/console/catalog)
#     2. Be logged into the BC Gov OpenShift Image Registry via
#          docker login -u <github> -p `oc whoami -t` docker-registry.pathfinder.gov.bc.ca
#
#        For example:
#          docker login -u garywong-bc -p `oc whoami -t` docker-registry.pathfinder.gov.bc.ca
services:
  #############################################################################################
  ###                                       Minio-Pub                                       ###
  #############################################################################################
  minio-public:
    build:
      context: ./openshift/docker/minio/
    hostname: minio
    ports:
      - "9000:9000"
    volumes:
      - /data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_DATA_DIR: /data
    entrypoint: /minio-entrypoint.sh
    command: server /data
    networks:
      - gwells-network
  #############################################################################################
  ###                                       Minio-Priv                                      ###
  #############################################################################################
  minio-private:
    build:
      context: ./openshift/docker/minio/
    hostname: minio
    ports:
      - "9001:9001"
    volumes:
      - /data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_DATA_DIR: /data
    entrypoint: /minio-entrypoint.sh
    command: server --address :9001 /data
    networks:
      - gwells-network
  #############################################################################################
  ###                                       CrunchyDB                                       ###
  #############################################################################################
  db:
    platform: linux/x86_64
    image: crunchydata/crunchy-postgres-gis:centos7-12.2-4.2.2
    hostname: db
    environment:
      PG_USER: gwells
      PG_PASSWORD: ${DATABASE_PASSWORD}
      PG_DATABASE: gwells
      PG_MODE: primary
      PG_PRIMARY_USER: primaryuser
      PG_PRIMARY_PASSWORD: ${PG_PRIMARY_PASSWORD}
      PG_ROOT_PASSWORD: ${PG_ROOT_PASSWORD}
      PG_PRIMARY_PORT: 5432
      TEMP_BUFFERS: 9MB
      MAX_CONNECTIONS: 101
      SHARED_BUFFERS: 128MB
      MAX_WAL_SENDERS: 7
      WORK_MEM: 5MB
      PG_PRIMARY_HOST: db
      PGHOST: /tmp
      TILESERVER_USER: ftw_reader
      TILESERVER_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata-volume:/pgdata:z
      - type: bind
        source: ./app/database/scripts/local_dev/setup.sql
        target: /pgconf/setup.sql
        consistency: cached
    healthcheck:
      test: ["CMD-SHELL", "/usr/pgsql-12/bin/pg_isready", "-d", "gwells"]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 120s
    networks:
      - gwells-network
  #############################################################################################
  ###                                       Tileserv                                        ###
  #############################################################################################
  tileserv:
    hostname: tileserv
    depends_on:
      - db
    platform: linux/x86_64
    image: pramsey/pg_tileserv:20231005
    env_file:
      - path: ./.env.test
        required: false
    environment:
      DATABASE_URL: "postgres://ftw_reader:${DATABASE_PASSWORD}@${GWELLS_SERVICE_HOST:-db}:${GWELLS_SERVICE_PORT:-5432}/gwells"
    ports:
      - "7800:7800"
    entrypoint: sh -c "sleep 10; /app/pg_tileserv"
    networks:
      - gwells-network
  #############################################################################################
  ###                                       Frontend                                        ###
  #############################################################################################
  frontend:
    image: node:22.12.0
    container_name: frontend
    working_dir: /app/frontend
    environment:
      DEBUG: "True"
      VITE_FRONTEND_TILE_URL: "http://localhost:7800"
      VITE_AXIOS_BASE_URL: "http://localhost:8000/gwells/api/v2/"
    command: /bin/bash -c "cd /frontend && npm install --legacy-peer-deps && npm run dev"
    ports:
      - "8080:8080"
    volumes:
      - ./app/frontend:/frontend
      - /app/frontend/node_modules/
    depends_on:
      - backend
    networks:
      - gwells-network
  #############################################################################################
  ###                                       Backend                                         ###
  #############################################################################################
  backend:
    platform: linux/x86_64
    # working_dir: /backend
    build:
      context: ./app/backend
      dockerfile: ./Dockerfile
    image: nr-gwells/backend:latest
    container_name: backend
    # env_file:
    # - path: ./.env.test
    #   required: false
    environment:
      ENVIRONMENT: "${ENVIRONMENT:-local}"
      APP_CONTEXT_ROOT: gwells
      CSRF_COOKIE_SECURE: "false"
      CUSTOM_GDAL_GEOS: "false"
      DATABASE_NAME: gwells
      DATABASE_USER: "${DATABASE_USER:-gwells}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      # DATABASE_SERVICE_NAME: gwells
      DJANGO_ADMIN_URL: admin
      DJANGO_DEBUG: "True"
      DJANGO_SECRET_KEY: secret
      ENABLE_ADDITIONAL_DOCUMENTS: "True"
      ENABLE_AQUIFERS_SEARCH: "True"
      # GWELLS_SERVICE_HOST: "${GWELLS_SERVICE_HOST:-db}"
      # GWELLS_SERVICE_PORT: "${GWELLS_SERVICE_PORT:-5432}"
      DATABASE_SERVICE_NAME: db
      DATABASE_PORT: 5432
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      PYTHONUNBUFFERED: "1"
      SESSION_COOKIE_SECURE: "false"
      SSO_AUDIENCE: gwells-4121
      SSO_CLIENT: gwells-4121
      SSO_TEST_AUDIENCE: gwells-api-tests-4820
      SSO_TEST_CLIENT: gwells-api-tests-4820
      SSO_AUTH_HOST: https://test.loginproxy.gov.bc.ca/auth
      SSO_IDP_HINT: "undefined"
      SSO_PORT: 0
      SSO_REALM: standard
      SSO_PUBKEY: ${SSO_PUBKEY}
      S3_HOST: minio-public:9000
      S3_PRIVATE_HOST: minio-private:9001
      S3_PRIVATE_BUCKET: gwells
      S3_PRIVATE_ROOT_BUCKET: gwells
      S3_PRIVATE_WELL_BUCKET: well-docs
      S3_PRIVATE_AQUIFER_BUCKET: aquifer-docs
      S3_PRIVATE_REGISTRANT_BUCKET: driller-docs
      S3_PUBLIC_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      S3_PUBLIC_SECRET_KEY: ${MINIO_SECRET_KEY}
      S3_AQUIFER_BUCKET: aquifer-docs
      S3_REGISTRANT_BUCKET: driller-docs
      S3_ROOT_BUCKET: gwells
      S3_WELL_BUCKET: well-docs
      S3_WELL_EXPORT_BUCKET: gwells
      S3_USE_SECURE: 0
      EMAIL_NOTIFICATION_RECIPIENT: sustainment.team@gov.bc.ca
      GEOCODER_ADDRESS_API_BASE: https://geocoder.api.gov.bc.ca/addresses.json?
      LOCAL: "true"
      LOAD_FIXTURES: "true"
    command: /bin/bash -c "python3 manage.py migrate --noinput && ./load_fixtures.sh all && python3 manage.py createinitialrevisions && python3 manage.py collectstatic --noinput && python3 manage.py runserver 0.0.0.0:8000"
    # volumes:
    #   - ./app/backend:/app/backend
    healthcheck:
      test: timeout 3s bash -c 'true > /dev/tcp/127.0.0.1/8000'
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
    ports: ["8000:8000"]
    depends_on:
      db:
        condition: service_healthy
      minio-public:
        condition: service_started
    networks:
      - gwells-network
  #############################################################################################
  ###                                       Volumes                                         ###
  #############################################################################################
  pgadmin:
    container_name: gwells-pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: admin@gwells.com
    networks:
      - gwells-network

#############################################################################################
###                                       Volumes                                         ###
#############################################################################################
volumes:
  pgdata-volume:

#############################################################################################
###                                       Network                                         ###
#############################################################################################
networks:
  gwells-network:
    driver: "bridge"
