--------------------------------------------------------
--  File created - Friday-March-10-2017   
--------------------------------------------------------
CREATE INDEX AQF_WELLS_ASCD_FK_I ON GW_AQUIFER_ATTRS (AQUIFER_SUBTYPE_CODE ASC) ;

ALTER TABLE GW_AQUIFER_ATTRS
ADD CONSTRAINT AQF_WELLS_ASCD_FK FOREIGN KEY
(
  AQUIFER_SUBTYPE_CODE 
)
REFERENCES WELLS_AQUIFER_SUBTYPE_CODES
(
  AQUIFER_SUBTYPE_CODE 
);

ALTER TABLE GW_AQUIFER_ATTRS
ADD CONSTRAINT AVCON_1456177180_AQUIF_000 CHECK 
(AQUIFER_DESCRIPTION_RPT_IND BETWEEN 'Y' AND 'Y' OR AQUIFER_DESCRIPTION_RPT_IND BETWEEN 'N' AND 'N');

ALTER TABLE GW_AQUIFER_ATTRS
ADD CONSTRAINT AVCON_1456177180_AQUIF_001 CHECK 
(AQUIFER_STATISTICS_RPT_IND BETWEEN 'Y' AND 'Y' OR AQUIFER_STATISTICS_RPT_IND BETWEEN 'N' AND 'N');

CREATE UNIQUE INDEX AW_PK ON GW_AQUIFER_WELLS (AQUIFER_WELL_ID ASC) ;

CREATE INDEX GW_AW_AQF_FK_I ON GW_AQUIFER_WELLS (AQUIFER_ID ASC) ;

CREATE INDEX GW_AW_WELL_FK_I ON GW_AQUIFER_WELLS (WELL_ID ASC) ;

ALTER TABLE GW_AQUIFER_WELLS
ADD CONSTRAINT GW_AW_AQF_FK FOREIGN KEY
(
  AQUIFER_ID 
)
REFERENCES GW_AQUIFER_ATTRS
(
  AQUIFER_ID 
);

ALTER TABLE GW_AQUIFER_WELLS
ADD CONSTRAINT GW_AW_WELL_FK FOREIGN KEY
(
  WELL_ID 
)
REFERENCES WELLS_WELLS
(
  WELL_ID 
);


CREATE UNIQUE INDEX CNCD_PK ON WELLS_CONSTR_METHOD_CODES (CONSTRUCTION_METHOD_CODE ASC) ;

CREATE UNIQUE INDEX DRCD_PK ON WELLS_DRILLER_CODES (DRILLER_COMPANY_CODE ASC) ;



CREATE INDEX CSNG_WELLS_CAMC_FK_I ON WELLS_CASINGS (CASING_MATERIAL_CODE ASC) ;

CREATE INDEX CSNG_WELL_FK_I ON WELLS_CASINGS (WELL_ID ASC) ;

ALTER TABLE WELLS_CASINGS
ADD CONSTRAINT CSNG_WELLS_CAMC_FK FOREIGN KEY
(
  CASING_MATERIAL_CODE 
)
REFERENCES GW_CASING_MATERIAL_CODES
(
  CASING_MATERIAL_CODE 
);

ALTER TABLE WELLS_CASINGS
ADD CONSTRAINT CSNG_WELL_FK FOREIGN KEY
(
  WELL_ID 
)
REFERENCES WELLS_WELLS
(
  WELL_ID 
);

CREATE UNIQUE INDEX CONST_PK ON WELLS_CONSTANT (CODE_NAME ASC) ;


CREATE INDEX GW_WWQX_WELLS_WQCC_FK_I ON GW_WELL_WATER_QUALITY_XREFS (WATER_QUAL_CHARACTERISTICS_CD ASC) ;

CREATE INDEX GW_WWQX_WELL_FK_I ON GW_WELL_WATER_QUALITY_XREFS (WELL_ID ASC) ;
ALTER TABLE GW_WELL_WATER_QUALITY_XREFS
ADD CONSTRAINT GW_WWQX_WELLS_WQCC_FK FOREIGN KEY
(
  WATER_QUAL_CHARACTERISTICS_CD 
)
REFERENCES GW_WATER_QUAL_CHRCTRSTC_CDS
(
  WATER_QUAL_CHARACTERISTICS_CD 
);

ALTER TABLE GW_WELL_WATER_QUALITY_XREFS
ADD CONSTRAINT GW_WWQX_WELL_FK FOREIGN KEY
(
  WELL_ID 
)
REFERENCES WELLS_WELLS
(
  WELL_ID 
);





CREATE INDEX GW_CSC_WELLS_CLWC_FK_I ON GW_CLASS_SUBCLASS_XREFS (CLASS_OF_WELL_CODE ASC) ;

CREATE INDEX GW_CSC_WELLS_SWLC_FK_I ON GW_CLASS_SUBCLASS_XREFS (SUBCLASS_OF_WELL_CODE ASC) ;
ALTER TABLE GW_CLASS_SUBCLASS_XREFS
ADD CONSTRAINT GW_CSC_WELLS_CLWC_FK FOREIGN KEY
(
  CLASS_OF_WELL_CODE 
)
REFERENCES GW_CLASS_OF_WELL_CODES
(
  CLASS_OF_WELL_CODE 
);

ALTER TABLE GW_CLASS_SUBCLASS_XREFS
ADD CONSTRAINT GW_CSC_WELLS_SWLC_FK FOREIGN KEY
(
  SUBCLASS_OF_WELL_CODE 
)
REFERENCES GW_SUBCLASS_OF_WELL_CODES
(
  SUBCLASS_OF_WELL_CODE 
);



-- Unable to render TABLE DDL for object GW_CLASS_OF_WELL_CODES with DBMS_METADATA attempting internal generator.






CREATE INDEX GW_NTM_AQA_FK_I ON GW_NTS_MAPSHEETS (AQUIFER_ID ASC) ;

CREATE UNIQUE INDEX NTM_PK ON GW_NTS_MAPSHEETS (NTS_MAPSHEET_ID ASC) ;
ALTER TABLE GW_NTS_MAPSHEETS
ADD CONSTRAINT GW_NTM_AQF_FK FOREIGN KEY
(
  AQUIFER_ID 
)
REFERENCES GW_AQUIFER_ATTRS
(
  AQUIFER_ID 
);



CREATE UNIQUE INDEX ERR_PK ON WELLS_ERRORS (ERROR_ID ASC) ;
CREATE UNIQUE INDEX DCD_PK ON WELLS_LEGAL_LAND_DIST_CODES (LEGAL_LAND_DISTRICT_CODE ASC) ;

CREATE UNIQUE INDEX DSCD_PK ON WELLS_LITH_DESCRIPTION_CODES (LITHOLOGY_CODE ASC) ;

CREATE UNIQUE INDEX LTCL_PK ON WELLS_LITHOLOGY_COLOUR_CODES (LITHOLOGY_COLOUR_CODE ASC) ;

CREATE UNIQUE INDEX YECD_PK ON WELLS_YIELD_UNIT_CODES (YIELD_UNIT_CODE ASC) ;

CREATE UNIQUE INDEX MTCD_PK ON WELLS_LITHOLOGY_MATERIAL_CODES (LITHOLOGY_MATERIAL_CODE ASC) ;
CREATE UNIQUE INDEX LIDS_PK ON WELLS_LITHOLOGY_DESCRIPTIONS (LITHOLOGY_DESCRIPTION_ID ASC) ;
CREATE INDEX LIDS_WELLS_RHC_FK_I ON WELLS_LITHOLOGY_DESCRIPTIONS (RELATIVE_HARDNESS_CODE ASC) ;
CREATE INDEX LIDS_YECD_FK_I ON WELLS_LITHOLOGY_DESCRIPTIONS (WATER_BEARING_EST_FLW_UNT_CD ASC) ;
CREATE INDEX WELL_LIDS_DSCD_FK_I ON WELLS_LITHOLOGY_DESCRIPTIONS (LITHOLOGY_CODE ASC) ;
CREATE INDEX WELL_LIDS_LTCL_FK_I ON WELLS_LITHOLOGY_DESCRIPTIONS (LITHOLOGY_COLOUR_CODE ASC) ;
CREATE INDEX WELL_LIDS_MTCD_FK_I ON WELLS_LITHOLOGY_DESCRIPTIONS (LITHOLOGY_MATERIAL_CODE ASC) ;
CREATE INDEX WELL_LIDS_WELL_FK_I ON WELLS_LITHOLOGY_DESCRIPTIONS (WELL_ID ASC) ;
ALTER TABLE WELLS_LITHOLOGY_DESCRIPTIONS
ADD CONSTRAINT LIDS_WELLS_RHC_FK FOREIGN KEY
(
  RELATIVE_HARDNESS_CODE 
)
REFERENCES GW_RELATIVE_HARDNESS_CODES
(
  RELATIVE_HARDNESS_CODE 
);

ALTER TABLE WELLS_LITHOLOGY_DESCRIPTIONS
ADD CONSTRAINT LIDS_YECD_FK FOREIGN KEY
(
  WATER_BEARING_EST_FLW_UNT_CD 
)
REFERENCES WELLS_YIELD_UNIT_CODES
(
  YIELD_UNIT_CODE 
);

ALTER TABLE WELLS_LITHOLOGY_DESCRIPTIONS
ADD CONSTRAINT WELL_LIDS_DSCD_FK FOREIGN KEY
(
  LITHOLOGY_CODE 
)
REFERENCES WELLS_LITH_DESCRIPTION_CODES
(
  LITHOLOGY_CODE 
);

ALTER TABLE WELLS_LITHOLOGY_DESCRIPTIONS
ADD CONSTRAINT WELL_LIDS_LTCL_FK FOREIGN KEY
(
  LITHOLOGY_COLOUR_CODE 
)
REFERENCES WELLS_LITHOLOGY_COLOUR_CODES
(
  LITHOLOGY_COLOUR_CODE 
);

ALTER TABLE WELLS_LITHOLOGY_DESCRIPTIONS
ADD CONSTRAINT WELL_LIDS_MTCD_FK FOREIGN KEY
(
  LITHOLOGY_MATERIAL_CODE 
)
REFERENCES WELLS_LITHOLOGY_MATERIAL_CODES
(
  LITHOLOGY_MATERIAL_CODE 
);

ALTER TABLE WELLS_LITHOLOGY_DESCRIPTIONS
ADD CONSTRAINT WELL_LIDS_WELL_FK FOREIGN KEY
(
  WELL_ID 
)
REFERENCES WELLS_WELLS
(
  WELL_ID 
);
CREATE UNIQUE INDEX LOCN_PK ON WELLS_LOCATION_ACCURACY_CODE (LOC_ACCURACY_CODE ASC) ;

CREATE UNIQUE INDEX OWNR_PK ON WELLS_OWNERS (OWNER_ID ASC) ;
CREATE INDEX OWNR_WELLS_PSC_FK_I ON WELLS_OWNERS (PROVINCE_STATE_CODE ASC) ;
ALTER TABLE WELLS_OWNERS
ADD CONSTRAINT OWNR_WELLS_PSC_FK FOREIGN KEY
(
  PROVINCE_STATE_CODE 
)
REFERENCES GW_PROVINCE_STATE_CODES
(
  PROVINCE_STATE_CODE 
);
CREATE UNIQUE INDEX PFRT_PK ON WELLS_PERFORATIONS (PERFORATION_ID ASC) ;
CREATE INDEX WELL_PFRT_WELL_FK_I ON WELLS_PERFORATIONS (WELL_ID ASC) ;
ALTER TABLE WELLS_PERFORATIONS
ADD CONSTRAINT WELL_PFRT_WELL_FK FOREIGN KEY
(
  WELL_ID 
)
REFERENCES WELLS_WELLS
(
  WELL_ID 
);

CREATE INDEX PRDT_WELLS_YEMC_FK_I ON WELLS_PRODUCTION_DATA (YIELD_ESTIMATED_METHOD_CODE ASC) ;
CREATE INDEX PRDT_WELL_FK_I ON WELLS_PRODUCTION_DATA (WELL_ID ASC) ;
CREATE INDEX PRDT_YECD_FK_I ON WELLS_PRODUCTION_DATA (TEST_RATE_UNITS_CODE ASC) ;
ALTER TABLE WELLS_PRODUCTION_DATA
ADD CONSTRAINT PRDT_WELLS_YEMC_FK FOREIGN KEY
(
  YIELD_ESTIMATED_METHOD_CODE 
)
REFERENCES GW_YIELD_ESTIMATED_MTHD_CDS
(
  YIELD_ESTIMATED_METHOD_CODE 
);

ALTER TABLE WELLS_PRODUCTION_DATA
ADD CONSTRAINT PRDT_WELL_FK FOREIGN KEY
(
  WELL_ID 
)
REFERENCES WELLS_WELLS
(
  WELL_ID 
);

ALTER TABLE WELLS_PRODUCTION_DATA
ADD CONSTRAINT PRDT_YECD_FK FOREIGN KEY
(
  TEST_RATE_UNITS_CODE 
)
REFERENCES WELLS_YIELD_UNIT_CODES
(
  YIELD_UNIT_CODE 
);
CREATE INDEX SCRN_WELLS_SATC_FK_I ON WELLS_SCREENS (SCREEN_ASSEMBLY_TYPE_CODE ASC) ;
CREATE INDEX SCRN_WELL_FK_I ON WELLS_SCREENS (WELL_ID ASC) ;
ALTER TABLE WELLS_SCREENS
ADD CONSTRAINT SCRN_WELLS_SATC_FK FOREIGN KEY
(
  SCREEN_ASSEMBLY_TYPE_CODE 
)
REFERENCES GW_SCREEN_ASSEMBLY_TYPE_CDS
(
  SCREEN_ASSEMBLY_TYPE_CODE 
);

ALTER TABLE WELLS_SCREENS
ADD CONSTRAINT SCRN_WELL_FK FOREIGN KEY
(
  WELL_ID 
)
REFERENCES WELLS_WELLS
(
  WELL_ID 
);

CREATE UNIQUE INDEX SEQ_PK ON WELLS_SEQUENCES (SEQUENCE_ID ASC) ;



CREATE UNIQUE INDEX TMP_ACCESS_PK ON WELLS_TEMP_ACCESS (TEMP_ACCESS_ID ASC) ;
CREATE UNIQUE INDEX TMP_CON_PK ON WELLS_TEMP_ACCESS_CONTRACTORS (TEMP_ACCESS_CONTRACTOR_ID ASC) ;
COMMENT ON TABLE WELLS_TEMP_ACCESS_CONTRACTORS IS 'Temporary table for importing and exporting WELL contractor data to and from Microsoft Access compatible comma seperated file CONTRACTOR.TXT.';
-- Unable to render TABLE DDL for object WELLS_TEMP_ACCESS_LITHOLOGY with DBMS_METADATA attempting internal generator.


CREATE UNIQUE INDEX TMP_LITH_PK ON WELLS_TEMP_ACCESS_LITHOLOGY (TEMP_ACCESS_LITHOLGY_ID ASC) ;
CREATE UNIQUE INDEX USCD_PK ON WELLS_USE_CODES (WELL_USE_CODE ASC) ;

CREATE UNIQUE INDEX UMCD_PK ON WELLS_UTM_DESCRIPTION (UTM_DESCRIPTION_ID ASC) ;
COMMENT ON TABLE WELLS_UTM_DESCRIPTION IS 'Univeral Transverse Mercator (UTM) coordinates used to indentify zone where well is located location. UTM Provides a constant distance relationship anywhere on a map.  BC contains 4 UTM zones these are  8,9,10 and 11.Every 8 degrees. This code table supports the manual additon of UTM values to a Well record.';
-- Unable to render TABLE DDL for object WELLS_UTM_SCALE_CODES with DBMS_METADATA attempting internal generator.


CREATE UNIQUE INDEX USC_PK ON WELLS_UTM_SCALE_CODES (UTM_ACCURACY_CODE ASC) ;
COMMENT ON TABLE WELLS_WATERSHED_CODES IS 'Watershed where the well is located.';

ALTER TABLE WELLS_WELL_LICENCE
ADD CONSTRAINT WELL_LCNC_WELL_LCNC_UK_UK UNIQUE 
(
  WELL_TAG_NUMBER 
, AUTHORIZATION_NUMBER 
, AUTHORIZATION_STATUS 
, AUTHORIZATION_STATUS_DATE 
);
CREATE INDEX WELL_LCNC_WELL_FK_I ON WELLS_WELL_LICENCE (WELL_TAG_NUMBER ASC) ;
CREATE INDEX WELL_LCNC_WELL_GWA_FK_I ON WELLS_WELL_LICENCE (AUTHORIZATION_NUMBER ASC) ;
ALTER TABLE WELLS_WELL_LICENCE
ADD CONSTRAINT WELL_LCNC_WELL_FK FOREIGN KEY
(
  WELL_TAG_NUMBER 
)
REFERENCES WELLS_WELLS
(
  WELL_TAG_NUMBER 
);

ALTER TABLE WELLS_WELL_LICENCE
ADD CONSTRAINT WELL_LCNC_WELL_GWA_FK FOREIGN KEY
(
  AUTHORIZATION_NUMBER 
)
REFERENCES WELLS_GROUND_WATER_AUTHRZATION
(
  AUTHORIZATION_NUMBER 
);

ALTER TABLE WELLS_WELL_LICENCE
ADD CONSTRAINT WELL_LCNC_STS_CHK CHECK 
(AUTHORIZATION_STATUS IN ('ACTIVE', 'CANCELLED', 'ABANDONED', 'ERROR', 'LICENCE ASSOCIATION ENDED'));
-- Unable to render TABLE DDL for object WELLS_WELLS with DBMS_METADATA attempting internal generator.



ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELL_UK_UK UNIQUE 
(
  WELL_TAG_NUMBER 
);

ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WIPN_UK UNIQUE 
(
  WELL_IDENTIFICATION_PLATE_NO 
);

CREATE INDEX WELLS_WELLS_WTN_I ON WELLS_WELLS (WELL_TAG_NUMBER ASC) ;
CREATE INDEX WELL_CNCD_FK_I ON WELLS_WELLS (CONSTRUCTION_METHOD_CODE ASC) ;
CREATE INDEX WELL_DCD_FK_I ON WELLS_WELLS (LEGAL_LAND_DISTRICT_CODE ASC) ;
CREATE INDEX WELL_DRCD_FK_I ON WELLS_WELLS (DRILLER_COMPANY_CODE ASC) ;
CREATE INDEX WELL_LICD_FK_I ON WELLS_WELLS (AQUIFER_LITHOLOGY_CODE ASC) ;
CREATE INDEX WELL_LOCN_FK_I ON WELLS_WELLS (LOC_ACCURACY_CODE ASC) ;
CREATE INDEX WELL_NMB_FK_I ON WELLS_WELLS (BCGS_ID ASC) ;
CREATE INDEX WELL_OWNR_FK_I ON WELLS_WELLS (OWNER_ID ASC) ;
CREATE INDEX WELL_USCD_FK_I ON WELLS_WELLS (WELL_USE_CODE ASC); 
CREATE INDEX WELL_USC_FK_I ON WELLS_WELLS (UTM_ACCURACY_CODE ASC) ;
CREATE INDEX WELL_WELLS_ACST_FK_I ON WELLS_WELLS (ACCEPTANCE_STATUS_CODE ASC) ;
CREATE INDEX WELL_WELLS_CLMC_FK_I ON WELLS_WELLS (CLOSURE_METHOD_CODE ASC) ;
CREATE INDEX WELL_WELLS_CLWC_FK_I ON WELLS_WELLS (CLASS_OF_WELL_CODE ASC) ;
CREATE INDEX WELL_WELLS_CSC_FK_I ON WELLS_WELLS (CLASS_OF_WELL_CODCLASSIFIED_BY ASC, SUBCLASS_OF_WELL_CLASSIFIED_BY ASC) ;
CREATE INDEX WELL_WELLS_DRMC_FK_I ON WELLS_WELLS (DRILLING_METHOD_CODE ASC) ;
CREATE INDEX WELL_WELLS_DVMC_FK_I ON WELLS_WELLS (DEVELOPMENT_METHOD_CODE ASC) ;
CREATE INDEX WELL_WELLS_FPMC_FK_I ON WELLS_WELLS (FILTER_PACK_MATERIAL_CODE ASC) ;
CREATE INDEX WELL_WELLS_FPSC_FK_I ON WELLS_WELLS (FILTER_PACK_SIZE_CODE ASC) ;
CREATE INDEX WELL_WELLS_GEMC_FK_I ON WELLS_WELLS (GROUND_ELEVATION_METHOD_CODE ASC) ;
CREATE INDEX WELL_WELLS_LMC_FK_I ON WELLS_WELLS (LINER_MATERIAL_CODE ASC) ;
CREATE INDEX WELL_WELLS_OWC_FK_I ON WELLS_WELLS (ORIENTATION_OF_WELL_CODE ASC) ;
CREATE INDEX WELL_WELLS_SBC_FK_I ON WELLS_WELLS (SCREEN_BOTTOM_CODE ASC) ;
CREATE INDEX WELL_WELLS_SIC_FK_I ON WELLS_WELLS (SCREEN_INTAKE_CODE ASC) ;
CREATE INDEX WELL_WELLS_SMC_FK_I ON WELLS_WELLS (SCREEN_MATERIAL_CODE ASC) ;
CREATE INDEX WELL_WELLS_SOC_FK_I ON WELLS_WELLS (SCREEN_OPENING_CODE ASC) ;
CREATE INDEX WELL_WELLS_SSMC_FK_I ON WELLS_WELLS (SURFACE_SEAL_MATERIAL_CODE ASC) ;
CREATE INDEX WELL_WELLS_SSMT_FK_I ON WELLS_WELLS (SURFACE_SEAL_METHOD_CODE ASC) ;
CREATE INDEX WELL_WELLS_STC_FK_I ON WELLS_WELLS (SCREEN_TYPE_CODE ASC) ;
CREATE INDEX WELL_WELLS_SWC_FK_I ON WELLS_WELLS (STATUS_OF_WELL_CODE ASC) ;
CREATE INDEX WELL_WELLS_SWLC_FK_I ON WELLS_WELLS (SUBCLASS_OF_WELL_CODE ASC) ;
CREATE INDEX WELL_WELLS_UZC_FK_I ON WELLS_WELLS (UTM_ZONE_CODE ASC) ;
CREATE UNIQUE INDEX WELL_WIPN_UK_I ON WELLS_WELLS (WELL_IDENTIFICATION_PLATE_NO ASC) ;
CREATE INDEX WELL_WTSH_FK_I ON WELLS_WELLS (WATERSHED_CODE ASC) ;
CREATE INDEX WELL_YECD_FK_I ON WELLS_WELLS (ARTESIAN_FLOW_UNIT_CODE ASC) ;
CREATE INDEX WELYIELD_ESTIMATE_DESCRIBED__I ON WELLS_WELLS (YIELD_UNIT_CODE ASC) ;


-- Unable to render INDEX DDL for object AQF_WELLS_ASCD_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX AQF_WELLS_ASCD_FK_I ON GW_AQUIFER_ATTRS (AQUIFER_SUBTYPE_CODE ASC) ;
-- Unable to render INDEX DDL for object GW_AQF_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_AQF_PK ON GW_AQUIFER_ATTRS (AQUIFER_ID) ;
-- Unable to render INDEX DDL for object GW_AW_AQF_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX GW_AW_AQF_FK_I ON GW_AQUIFER_WELLS (AQUIFER_ID ASC) ;
-- Unable to render INDEX DDL for object GW_AW_WELL_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX GW_AW_WELL_FK_I ON GW_AQUIFER_WELLS (WELL_ID ASC) ;
-- Unable to render INDEX DDL for object GW_CAMC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_CAMC_PK ON GW_CASING_MATERIAL_CODES (CASING_MATERIAL_CODE) ;
-- Unable to render INDEX DDL for object GW_CLWC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_CLWC_PK ON GW_CLASS_OF_WELL_CODES (CLASS_OF_WELL_CODE) ;
-- Unable to render INDEX DDL for object GW_CSC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_CSC_PK ON GW_CLASS_SUBCLASS_XREFS (CLASS_OF_WELL_CODE, SUBCLASS_OF_WELL_CODE) ;
-- Unable to render INDEX DDL for object GW_CSC_WELLS_CLWC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX GW_CSC_WELLS_CLWC_FK_I ON GW_CLASS_SUBCLASS_XREFS (CLASS_OF_WELL_CODE ASC) ;
-- Unable to render INDEX DDL for object GW_CLMC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_CLMC_PK ON GW_CLOSURE_METHOD_CODES (CLOSURE_METHOD_CODE) ;
-- Unable to render INDEX DDL for object GW_DVMC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_DVMC_PK ON GW_DEVELOPMENT_METHOD_CDS (DEVELOPMENT_METHOD_CODE) ;
-- Unable to render INDEX DDL for object GW_DRMC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_DRMC_PK ON GW_DRILLING_METHOD_CODES (DRILLING_METHOD_CODE) ;
-- Unable to render INDEX DDL for object GW_FPMC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_FPMC_PK ON GW_FILTER_PACK_MATERIAL_CDS (FILTER_PACK_MATERIAL_CODE) ;
-- Unable to render INDEX DDL for object GW_FPSC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_FPSC_PK ON GW_FILTER_PACK_SIZE_CODES (FILTER_PACK_SIZE_CODE) ;
-- Unable to render INDEX DDL for object GW_GEMC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_GEMC_PK ON GW_GROUND_ELEVATON_MTHD_CDS (GROUND_ELEVATION_METHOD_CODE) ;
-- Unable to render INDEX DDL for object GW_LMC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_LMC_PK ON GW_LINER_MATERIAL_CODES (LINER_MATERIAL_CODE) ;
-- Unable to render INDEX DDL for object GW_NTM_AQA_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX GW_NTM_AQA_FK_I ON GW_NTS_MAPSHEETS (AQUIFER_ID ASC) ;
-- Unable to render INDEX DDL for object GW_OWC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_OWC_PK ON GW_ORIENTATION_OF_WELL_CDS (ORIENTATION_OF_WELL_CODE) ;
-- Unable to render INDEX DDL for object GW_PSC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_PSC_PK ON GW_PROVINCE_STATE_CODES (PROVINCE_STATE_CODE) ;
-- Unable to render INDEX DDL for object GW_RHC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_RHC_PK ON GW_RELATIVE_HARDNESS_CODES (RELATIVE_HARDNESS_CODE) ;
-- Unable to render INDEX DDL for object GW_SATC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_SATC_PK ON GW_SCREEN_ASSEMBLY_TYPE_CDS (SCREEN_ASSEMBLY_TYPE_CODE) ;
-- Unable to render INDEX DDL for object GW_SBC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_SBC_PK ON GW_SCREEN_BOTTOM_CODES (SCREEN_BOTTOM_CODE) ;
-- Unable to render INDEX DDL for object GW_SIC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_SIC_PK ON GW_SCREEN_INTAKE_CODES (SCREEN_INTAKE_CODE) ;
-- Unable to render INDEX DDL for object GW_SMC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_SMC_PK ON GW_SCREEN_MATERIAL_CODES (SCREEN_MATERIAL_CODE) ;
-- Unable to render INDEX DDL for object GW_SOC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_SOC_PK ON GW_SCREEN_OPENING_CODES (SCREEN_OPENING_CODE) ;
-- Unable to render INDEX DDL for object GW_STC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_STC_PK ON GW_SCREEN_TYPE_CODES (SCREEN_TYPE_CODE) ;
-- Unable to render INDEX DDL for object GW_SWC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_SWC_PK ON GW_STATUS_OF_WELL_CODES (STATUS_OF_WELL_CODE) ;
-- Unable to render INDEX DDL for object GW_SWLC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_SWLC_PK ON GW_SUBCLASS_OF_WELL_CODES (SUBCLASS_OF_WELL_CODE) ;
-- Unable to render INDEX DDL for object GW_SSMC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_SSMC_PK ON GW_SURFACE_SEAL_MATERIL_CDS (SURFACE_SEAL_MATERIAL_CODE) ;
-- Unable to render INDEX DDL for object GW_SSMT_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_SSMT_PK ON GW_SURFACE_SEAL_METHOD_CDS (SURFACE_SEAL_METHOD_CODE) ;
-- Unable to render INDEX DDL for object GW_UZC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_UZC_PK ON GW_UTM_ZONE_CODES (UTM_ZONE_CODE) ;
-- Unable to render INDEX DDL for object GW_WQCC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_WQCC_PK ON GW_WATER_QUAL_CHRCTRSTC_CDS (WATER_QUAL_CHARACTERISTICS_CD) ;
-- Unable to render INDEX DDL for object GW_WWQX_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_WWQX_PK ON GW_WELL_WATER_QUALITY_XREFS (WELL_ID, WATER_QUAL_CHARACTERISTICS_CD) ;
-- Unable to render INDEX DDL for object GW_WWQX_WELLS_WQCC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX GW_WWQX_WELLS_WQCC_FK_I ON GW_WELL_WATER_QUALITY_XREFS (WATER_QUAL_CHARACTERISTICS_CD ASC) ;
-- Unable to render INDEX DDL for object GW_YEMC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GW_YEMC_PK ON GW_YIELD_ESTIMATED_MTHD_CDS (YIELD_ESTIMATED_METHOD_CODE) ;
-- Unable to render INDEX DDL for object WELLS_ACST_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX WELLS_ACST_PK ON WELLS_ACCEPTANCE_STATUS_CODE (ACCEPTANCE_STATUS_CODE) ;

-- Unable to render INDEX DDL for object WELLS_ASCD_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX WELLS_ASCD_PK ON WELLS_AQUIFER_SUBTYPE_CODES (AQUIFER_SUBTYPE_CODE) ;

-- Unable to render INDEX DDL for object CSNG_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX CSNG_PK ON WELLS_CASINGS (CASING_ID) ;


-- Unable to render INDEX DDL for object CSNG_WELLS_CAMC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX CSNG_WELLS_CAMC_FK_I ON WELLS_CASINGS (CASING_MATERIAL_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_GWA_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX WELL_GWA_PK ON WELLS_GROUND_WATER_AUTHRZATION (AUTHORIZATION_NUMBER) ;
-- Unable to render INDEX DDL for object WELL_LIDS_DSCD_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_LIDS_DSCD_FK_I ON WELLS_LITHOLOGY_DESCRIPTIONS (LITHOLOGY_CODE ASC) ;
-- Unable to render INDEX DDL for object LIDS_WELLS_RHC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX LIDS_WELLS_RHC_FK_I ON WELLS_LITHOLOGY_DESCRIPTIONS (RELATIVE_HARDNESS_CODE ASC) ;
-- Unable to render INDEX DDL for object LIDS_YECD_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX LIDS_YECD_FK_I ON WELLS_LITHOLOGY_DESCRIPTIONS (WATER_BEARING_EST_FLW_UNT_CD ASC) ;
-- Unable to render INDEX DDL for object WELL_LIDS_WELL_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_LIDS_WELL_FK_I ON WELLS_LITHOLOGY_DESCRIPTIONS (WELL_ID ASC) ;
-- Unable to render INDEX DDL for object WELL_LIDS_LTCL_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_LIDS_LTCL_FK_I ON WELLS_LITHOLOGY_DESCRIPTIONS (LITHOLOGY_COLOUR_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_LIDS_MTCD_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_LIDS_MTCD_FK_I ON WELLS_LITHOLOGY_DESCRIPTIONS (LITHOLOGY_MATERIAL_CODE ASC) ;
-- Unable to render INDEX DDL for object OWNR_WELLS_PSC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX OWNR_WELLS_PSC_FK_I ON WELLS_OWNERS (PROVINCE_STATE_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_PFRT_WELL_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_PFRT_WELL_FK_I ON WELLS_PERFORATIONS (WELL_ID ASC) ;
-- Unable to render INDEX DDL for object PRDT_WELLS_YEMC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX PRDT_WELLS_YEMC_FK_I ON WELLS_PRODUCTION_DATA (YIELD_ESTIMATED_METHOD_CODE ASC) ;
-- Unable to render INDEX DDL for object PRDT_YECD_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX PRDT_YECD_FK_I ON WELLS_PRODUCTION_DATA (TEST_RATE_UNITS_CODE ASC) ;
-- Unable to render INDEX DDL for object PRDT_WELL_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX PRDT_WELL_FK_I ON WELLS_PRODUCTION_DATA (WELL_ID ASC) ;
-- Unable to render INDEX DDL for object PRDT_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX PRDT_PK ON WELLS_PRODUCTION_DATA (PRODUCTION_ID) ;
-- Unable to render INDEX DDL for object SCRN_WELLS_SATC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX SCRN_WELLS_SATC_FK_I ON WELLS_SCREENS (SCREEN_ASSEMBLY_TYPE_CODE ASC) ;
-- Unable to render INDEX DDL for object SCRN_WELL_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX SCRN_WELL_FK_I ON WELLS_SCREENS (WELL_ID ASC) ;
-- Unable to render INDEX DDL for object SCRN_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SCRN_PK ON WELLS_SCREENS (SCREEN_ID) ;
-- Unable to render INDEX DDL for object WTSH_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX WTSH_PK ON WELLS_WATERSHED_CODES (WATERSHED_CODE) ;
-- Unable to render INDEX DDL for object WELL_LCNC_WELL_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_LCNC_WELL_FK_I ON WELLS_WELL_LICENCE (WELL_TAG_NUMBER ASC) ;
-- Unable to render INDEX DDL for object WELL_LCNC_WELL_GWA_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_LCNC_WELL_GWA_FK_I ON WELLS_WELL_LICENCE (AUTHORIZATION_NUMBER ASC) ;
-- Unable to render INDEX DDL for object WELL_LCNC_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX WELL_LCNC_PK ON WELLS_WELL_LICENCE (WELL_LICENCE_ID) ;
-- Unable to render INDEX DDL for object WELL_LCNC_WELL_LCNC_UK_UK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX WELL_LCNC_WELL_LCNC_UK_UK ON WELLS_WELL_LICENCE (WELL_TAG_NUMBER, AUTHORIZATION_NUMBER, AUTHORIZATION_STATUS, AUTHORIZATION_STATUS_DATE) ;
-- Unable to render INDEX DDL for object WELL_DRCD_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_DRCD_FK_I ON WELLS_WELLS (DRILLER_COMPANY_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_DCD_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_DCD_FK_I ON WELLS_WELLS (LEGAL_LAND_DISTRICT_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX WELL_PK ON WELLS_WELLS (WELL_ID) ;
-- Unable to render INDEX DDL for object WELL_WTSH_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WTSH_FK_I ON WELLS_WELLS (WATERSHED_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_LOCN_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_LOCN_FK_I ON WELLS_WELLS (LOC_ACCURACY_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_USC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_USC_FK_I ON WELLS_WELLS (UTM_ACCURACY_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_ACST_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_ACST_FK_I ON WELLS_WELLS (ACCEPTANCE_STATUS_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_CSC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_CSC_FK_I ON WELLS_WELLS (CLASS_OF_WELL_CODCLASSIFIED_BY ASC, SUBCLASS_OF_WELL_CLASSIFIED_BY ASC) ;
-- Unable to render INDEX DDL for object WELL_YECD_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_YECD_FK_I ON WELLS_WELLS (ARTESIAN_FLOW_UNIT_CODE ASC) ;
-- Unable to render INDEX DDL for object WELYIELD_ESTIMATE_DESCRIBED__I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELYIELD_ESTIMATE_DESCRIBED__I ON WELLS_WELLS (YIELD_UNIT_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_NMB_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_NMB_FK_I ON WELLS_WELLS (BCGS_ID ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_DVMC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_DVMC_FK_I ON WELLS_WELLS (DEVELOPMENT_METHOD_CODE ASC) ;
-- Unable to render INDEX DDL for object WELLS_WELLS_WTN_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELLS_WELLS_WTN_I ON WELLS_WELLS (WELL_TAG_NUMBER ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_DRMC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_DRMC_FK_I ON WELLS_WELLS (DRILLING_METHOD_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_FPSC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_FPSC_FK_I ON WELLS_WELLS (FILTER_PACK_SIZE_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_OWC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_OWC_FK_I ON WELLS_WELLS (ORIENTATION_OF_WELL_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_SMC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_SMC_FK_I ON WELLS_WELLS (SCREEN_MATERIAL_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WIPN_UK_I with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX WELL_WIPN_UK_I ON WELLS_WELLS (WELL_IDENTIFICATION_PLATE_NO ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_SOC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_SOC_FK_I ON WELLS_WELLS (SCREEN_OPENING_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_SSMC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_SSMC_FK_I ON WELLS_WELLS (SURFACE_SEAL_MATERIAL_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_UZC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_UZC_FK_I ON WELLS_WELLS (UTM_ZONE_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_SWLC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_SWLC_FK_I ON WELLS_WELLS (SUBCLASS_OF_WELL_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_SWC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_SWC_FK_I ON WELLS_WELLS (STATUS_OF_WELL_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_STC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_STC_FK_I ON WELLS_WELLS (SCREEN_TYPE_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_SSMT_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_SSMT_FK_I ON WELLS_WELLS (SURFACE_SEAL_METHOD_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_SIC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_SIC_FK_I ON WELLS_WELLS (SCREEN_INTAKE_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_SBC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_SBC_FK_I ON WELLS_WELLS (SCREEN_BOTTOM_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_LMC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_LMC_FK_I ON WELLS_WELLS (LINER_MATERIAL_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_GEMC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_GEMC_FK_I ON WELLS_WELLS (GROUND_ELEVATION_METHOD_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_FPMC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_FPMC_FK_I ON WELLS_WELLS (FILTER_PACK_MATERIAL_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_CLWC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_CLWC_FK_I ON WELLS_WELLS (CLASS_OF_WELL_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_WELLS_CLMC_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_WELLS_CLMC_FK_I ON WELLS_WELLS (CLOSURE_METHOD_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_OWNR_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_OWNR_FK_I ON WELLS_WELLS (OWNER_ID ASC) ;
-- Unable to render INDEX DDL for object WELL_LICD_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_LICD_FK_I ON WELLS_WELLS (AQUIFER_LITHOLOGY_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_USCD_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_USCD_FK_I ON WELLS_WELLS (WELL_USE_CODE ASC) ;
-- Unable to render INDEX DDL for object WELL_CNCD_FK_I with DBMS_METADATA attempting internal generator.
CREATE INDEX WELL_CNCD_FK_I ON WELLS_WELLS (CONSTRUCTION_METHOD_CODE ASC) ;
-- Unable to render INDEX DDL for object YECD_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX YECD_PK ON WELLS_YIELD_UNIT_CODES (YIELD_UNIT_CODE ASC) ;

ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_CNCD_FK FOREIGN KEY
(
  CONSTRUCTION_METHOD_CODE 
)
REFERENCES WELLS_CONSTR_METHOD_CODES
(
  CONSTRUCTION_METHOD_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_DCD_FK FOREIGN KEY
(
  LEGAL_LAND_DISTRICT_CODE 
)
REFERENCES WELLS_LEGAL_LAND_DIST_CODES
(
  LEGAL_LAND_DISTRICT_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_DRCD_FK FOREIGN KEY
(
  DRILLER_COMPANY_CODE 
)
REFERENCES WELLS_DRILLER_CODES
(
  DRILLER_COMPANY_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_LICD_FK FOREIGN KEY
(
  AQUIFER_LITHOLOGY_CODE 
)
REFERENCES WELLS_AQUIFER_LITHOLOGY_CODES
(
  AQUIFER_LITHOLOGY_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_LOCN_FK FOREIGN KEY
(
  LOC_ACCURACY_CODE 
)
REFERENCES WELLS_LOCATION_ACCURACY_CODE
(
  LOC_ACCURACY_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_NMB_FK FOREIGN KEY
(
  BCGS_ID 
)
REFERENCES WELLS_BCGS_NUMBERS
(
  BCGS_ID 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_OWNR_FK FOREIGN KEY
(
  OWNER_ID 
)
REFERENCES WELLS_OWNERS
(
  OWNER_ID 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_USCD_FK FOREIGN KEY
(
  WELL_USE_CODE 
)
REFERENCES WELLS_USE_CODES
(
  WELL_USE_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_USC_FK FOREIGN KEY
(
  UTM_ACCURACY_CODE 
)
REFERENCES WELLS_UTM_SCALE_CODES
(
  UTM_ACCURACY_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_ACST_FK FOREIGN KEY
(
  ACCEPTANCE_STATUS_CODE 
)
REFERENCES WELLS_ACCEPTANCE_STATUS_CODE
(
  ACCEPTANCE_STATUS_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_CLMC_FK FOREIGN KEY
(
  CLOSURE_METHOD_CODE 
)
REFERENCES GW_CLOSURE_METHOD_CODES
(
  CLOSURE_METHOD_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_CLWC_FK FOREIGN KEY
(
  CLASS_OF_WELL_CODE 
)
REFERENCES GW_CLASS_OF_WELL_CODES
(
  CLASS_OF_WELL_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_CSC_FK FOREIGN KEY
(
  CLASS_OF_WELL_CODCLASSIFIED_BY 
, SUBCLASS_OF_WELL_CLASSIFIED_BY 
)
REFERENCES GW_CLASS_SUBCLASS_XREFS
(
  CLASS_OF_WELL_CODE 
, SUBCLASS_OF_WELL_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_DRMC_FK FOREIGN KEY
(
  DRILLING_METHOD_CODE 
)
REFERENCES GW_DRILLING_METHOD_CODES
(
  DRILLING_METHOD_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_DVMC_FK FOREIGN KEY
(
  DEVELOPMENT_METHOD_CODE 
)
REFERENCES GW_DEVELOPMENT_METHOD_CDS
(
  DEVELOPMENT_METHOD_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_FPMC_FK FOREIGN KEY
(
  FILTER_PACK_MATERIAL_CODE 
)
REFERENCES GW_FILTER_PACK_MATERIAL_CDS
(
  FILTER_PACK_MATERIAL_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_FPSC_FK FOREIGN KEY
(
  FILTER_PACK_SIZE_CODE 
)
REFERENCES GW_FILTER_PACK_SIZE_CODES
(
  FILTER_PACK_SIZE_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_GEMC_FK FOREIGN KEY
(
  GROUND_ELEVATION_METHOD_CODE 
)
REFERENCES GW_GROUND_ELEVATON_MTHD_CDS
(
  GROUND_ELEVATION_METHOD_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_LMC_FK FOREIGN KEY
(
  LINER_MATERIAL_CODE 
)
REFERENCES GW_LINER_MATERIAL_CODES
(
  LINER_MATERIAL_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_OWC_FK FOREIGN KEY
(
  ORIENTATION_OF_WELL_CODE 
)
REFERENCES GW_ORIENTATION_OF_WELL_CDS
(
  ORIENTATION_OF_WELL_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_SBC_FK FOREIGN KEY
(
  SCREEN_BOTTOM_CODE 
)
REFERENCES GW_SCREEN_BOTTOM_CODES
(
  SCREEN_BOTTOM_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_SIC_FK FOREIGN KEY
(
  SCREEN_INTAKE_CODE 
)
REFERENCES GW_SCREEN_INTAKE_CODES
(
  SCREEN_INTAKE_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_SMC_FK FOREIGN KEY
(
  SCREEN_MATERIAL_CODE 
)
REFERENCES GW_SCREEN_MATERIAL_CODES
(
  SCREEN_MATERIAL_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_SOC_FK FOREIGN KEY
(
  SCREEN_OPENING_CODE 
)
REFERENCES GW_SCREEN_OPENING_CODES
(
  SCREEN_OPENING_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_SSMC_FK FOREIGN KEY
(
  SURFACE_SEAL_MATERIAL_CODE 
)
REFERENCES GW_SURFACE_SEAL_MATERIL_CDS
(
  SURFACE_SEAL_MATERIAL_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_SSMT_FK FOREIGN KEY
(
  SURFACE_SEAL_METHOD_CODE 
)
REFERENCES GW_SURFACE_SEAL_METHOD_CDS
(
  SURFACE_SEAL_METHOD_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_STC_FK FOREIGN KEY
(
  SCREEN_TYPE_CODE 
)
REFERENCES GW_SCREEN_TYPE_CODES
(
  SCREEN_TYPE_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_SWC_FK FOREIGN KEY
(
  STATUS_OF_WELL_CODE 
)
REFERENCES GW_STATUS_OF_WELL_CODES
(
  STATUS_OF_WELL_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_SWLC_FK FOREIGN KEY
(
  SUBCLASS_OF_WELL_CODE 
)
REFERENCES GW_SUBCLASS_OF_WELL_CODES
(
  SUBCLASS_OF_WELL_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WELLS_UZC_FK FOREIGN KEY
(
  UTM_ZONE_CODE 
)
REFERENCES GW_UTM_ZONE_CODES
(
  UTM_ZONE_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_WTSH_FK FOREIGN KEY
(
  WATERSHED_CODE 
)
REFERENCES WELLS_WATERSHED_CODES
(
  WATERSHED_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELL_YECD_FK FOREIGN KEY
(
  ARTESIAN_FLOW_UNIT_CODE 
)
REFERENCES WELLS_YIELD_UNIT_CODES
(
  YIELD_UNIT_CODE 
);
ALTER TABLE WELLS_WELLS
ADD CONSTRAINT WELYIELD_ESTIMATE_DESCRIBED_FK FOREIGN KEY
(
  YIELD_UNIT_CODE 
)
REFERENCES WELLS_YIELD_UNIT_CODES
(
  YIELD_UNIT_CODE 
);
