\echo '...creating xform_gwells_well ETL table';

DROP TABLE IF EXISTS xform_gwells_well;
CREATE unlogged TABLE IF NOT EXISTS xform_gwells_well (
   well_tag_number                     integer,
   well_id                             bigint,
   well_guid                           uuid,
   acceptance_status_code              character varying(10),
   owner_full_name                     character varying(200),
   owner_mailing_address               character varying(100),
   owner_city                          character varying(100),
   owner_postal_code                   character varying(10),
   street_address                      character varying(100),
   city                                character varying(50),
   legal_lot                           character varying(10),
   legal_plan                          character varying(20),
   legal_district_lot                  character varying(20),
   legal_block                         character varying(10),
   legal_section                       character varying(10),
   legal_township                      character varying(20),
   legal_range                         character varying(10),
   legal_pid                           character varying(9),
   well_location_description           character varying(500),
   identification_plate_number         integer,
   diameter                            character varying(9),
   total_depth_drilled                 numeric(7,2),
   finished_well_depth                 numeric(7,2),
   static_water_level                  numeric(7,2),
   well_cap_type                       character varying(40),
   well_disinfected                    boolean,
   well_yield                          numeric(8,3),
   intended_water_use_guid             uuid,
   land_district_guid                  uuid,
   province_state_guid                 uuid,
   well_class_guid                     uuid,
   well_subclass_guid                  uuid,
   well_yield_unit_guid                uuid,
   latitude                            numeric(8,6),
   longitude                           numeric(9,6),
   ground_elevation                    numeric(10,2),
   well_orientation                    boolean,
   other_drilling_method               character varying(50),
   drilling_method_guid                uuid,
   ground_elevation_method_guid        uuid,
   well_status_guid 	                  uuid,
   observation_well_number	            character varying(3),
   observation_well_status_guid        uuid,
   licenced_status_guid                uuid,
   alternative_specifications_ind      boolean,
   construction_start_date             timestamp with time zone,
   construction_end_date               timestamp with time zone,
   alteration_start_date               timestamp with time zone,
   alteration_end_date                 timestamp with time zone,
   decommission_start_date             timestamp with time zone,
   decommission_end_date               timestamp with time zone,
   drilling_company_guid               uuid,
   final_casing_stick_up               integer,
   artesian_flow                       numeric(7,2),
   artesian_pressure                   numeric(5,2),
   bedrock_depth                       numeric(7,2),
   well_identification_plate_attached character varying(500),
   water_supply_system_name            character varying(80),
   water_supply_system_well_name       character varying(80),
   ems                                 character varying(10),
   screen_intake_method_guid           uuid,
   screen_type_guid                    uuid,
   screen_material_guid                uuid,
   screen_opening_guid                 uuid,
   screen_bottom_guid                  uuid,
   utm_zone_code                       character varying(10),
   utm_northing                        integer,
   utm_easting                         integer,
   utm_accuracy_code                   character varying(10),
   bcgs_id                             bigint,
   development_method_guid             uuid,
   development_duration                integer,
   yield_estimation_method_guid        uuid,
   surface_seal_method_guid            uuid,
   surface_seal_material_guid          uuid,
   surface_seal_length                 numeric(5,2),
   surface_seal_thickness              numeric(7,2),
   backfill_type                       character varying(250),
   backfill_depth                      numeric(7,2),
   liner_material_guid                 uuid,
   decommission_reason                 character varying(250),
   decommission_method_guid            uuid,
   sealant_material                    character varying(100),
   backfill_material                   character varying(100),
   decommission_details                character varying(250),
   comments                            character varying(255),
   create_date                        timestamp with time zone,
   update_date                        timestamp with time zone,
   create_user                         character varying(30),
   update_user                         character varying(30)
);

\echo 'Created xform_gwells_well ETL table';
