\encoding windows-1251
\copy WELLS_LITHOLOGY_DESCRIPTIONS FROM '/tmp/legacy-data/WELLS_LITHOLOGY_DESCRIPTIONS.1-of-4.csv' HEADER DELIMITER ',' CSV
\copy WELLS_LITHOLOGY_DESCRIPTIONS FROM '/tmp/legacy-data/WELLS_LITHOLOGY_DESCRIPTIONS.2-of-4.csv' HEADER DELIMITER ',' CSV
\copy WELLS_LITHOLOGY_DESCRIPTIONS FROM '/tmp/legacy-data/WELLS_LITHOLOGY_DESCRIPTIONS.3-of-4.csv' HEADER DELIMITER ',' CSV
\copy WELLS_LITHOLOGY_DESCRIPTIONS FROM '/tmp/legacy-data/WELLS_LITHOLOGY_DESCRIPTIONS.4-of-4.csv' HEADER DELIMITER ',' CSV
