\echo '... importing xform into the gwells_well table';
INSERT INTO gwells_well (
  well_tag_number                    ,
  well_guid                          ,
  owner_full_name                    ,
  owner_mailing_address              ,
  owner_city                         ,
  owner_postal_code                  ,
  street_address                     ,
  city                               ,
  legal_lot                          ,
  legal_plan                         ,
  legal_district_lot                 ,
  legal_block                        ,
  legal_section                      ,
  legal_township                     ,
  legal_range                        ,
  legal_pid                          ,
  well_location_description          ,
  identification_plate_number        ,
  diameter                           ,
  total_depth_drilled                ,
  finished_well_depth                ,
  static_water_level                 ,
  well_cap_type                      ,
  well_yield                         ,
  intended_water_use_guid            ,
  legal_land_district_guid           ,
  province_state_guid                ,
  well_class_guid                    ,
  well_subclass_guid                 ,
  well_yield_unit_guid               ,
  latitude                           ,
  longitude                          ,
  ground_elevation                   ,
  well_orientation                   ,
  other_drilling_method              ,
  drilling_method_guid               ,
  ground_elevation_method_guid       ,
  when_created                       ,
  when_updated                       ,
  who_created                        ,
  who_updated                        ,
  surface_seal_length                ,
  surface_seal_thickness             ,
  surface_seal_method_guid           ,
  surface_seal_material_guid         ,
  backfill_type                      ,
  backfill_depth                     ,
  liner_material_guid                ,
  well_status_guid                   ,
  observation_well_number            ,
  observation_well_status            ,
  licenced_status_guid               ,
  other_screen_bottom                ,
  other_screen_material              ,
  development_notes                  ,
  water_quality_colour               ,
  water_quality_odour                ,
  well_disinfected                   ,
  alternative_specs_submitted        ,
  comments                           ,
  construction_start_date            ,
  construction_end_date              ,
  alteration_start_date              ,
  alteration_end_date                ,
  decommission_start_date            ,
  decommission_end_date              ,
  drilling_company_guid              ,
  final_casing_stick_up              ,
  artesian_flow                      ,
  artesian_pressure                  ,
  bedrock_depth                      ,
  water_supply_system_name           ,
  water_supply_system_well_name      ,
  well_identification_plate_attached,
  ems                                ,
  screen_intake_method_guid          ,
  screen_type_guid                   ,
  screen_material_guid               ,
  screen_opening_guid                ,
  screen_bottom_guid                 ,
  utm_zone_code                      ,
  utm_northing                       ,
  utm_easting                        ,
  utm_accuracy_code                  ,
  bcgs_id                            ,
  development_method_guid            ,
  development_hours
  )
SELECT
	xform.well_tag_number                          ,
	gen_random_uuid()                              ,
	coalesce(xform.owner_full_name,' ')            ,
	coalesce(xform.owner_mailing_address, ' ')     ,
	coalesce(xform.owner_city, ' ')                ,
	coalesce(xform.owner_postal_code , ' ')        ,
	coalesce(xform.street_address    , ' ')        ,
	coalesce(xform.city              , ' ')        ,
	coalesce(xform.legal_lot         , ' ')        ,
	coalesce(xform.legal_plan        , ' ')        ,
	coalesce(xform.legal_district_lot, ' ')        ,
	coalesce(xform.legal_block       , ' ')        ,
	coalesce(xform.legal_section     , ' ')        ,
	coalesce(xform.legal_township    , ' ')        ,
	coalesce(xform.legal_range       , ' ')        ,
	xform.legal_pid                                ,
	coalesce(xform.well_location_description,' ')  ,
	xform.identification_plate_number              ,
	coalesce(xform.diameter, ' ')                  ,
	xform.total_depth_drilled                      ,
	xform.finished_well_depth                      ,
  xform.static_water_level                       ,
  xform.well_cap_type                            ,
	xform.well_yield                               ,
	use.intended_water_use_guid                    ,
	land.land_district_guid                        ,
	xform.province_state_guid                      ,
	class.well_class_guid                          ,
	subclass.well_subclass_guid                    ,
	xform.well_yield_unit_guid                     ,
	xform.latitude                                 ,
	xform.longitude                                ,
	xform.ground_elevation                         ,
	xform.well_orientation                         ,
	null                                           ,
	xform.drilling_method_guid                     ,
	xform.ground_elevation_method_guid             ,
	xform.when_created                             ,
	xform.when_updated                             ,
	xform.who_created                              ,
	xform.who_updated                              ,
	xform.surface_seal_length                      ,
	xform.surface_seal_thickness                   ,
	xform.surface_seal_method_guid                 ,
  xform.surface_seal_material_guid               ,
  xform.backfill_type                            ,
  xform.backfill_depth                           ,
  xform.liner_material_guid                      ,
	well_status.well_status_guid                   ,
  xform.observation_well_number                  ,
  xform.observation_well_status                  ,
	licenced_status.well_licenced_status_guid      ,
	''                                             ,
	''                                             ,
	''                                             ,
	''                                             ,
	''                                             ,
	false                                          ,
	false                                          ,
	''                                             ,
	xform.construction_start_date                  ,
	xform.construction_end_date                    ,
	xform.alteration_start_date                    ,
	xform.alteration_end_date                      ,
	xform.decommission_start_date                  ,
	xform.decommission_end_date                    ,
	xform.drilling_company_guid                    ,
  xform.final_casing_stick_up                    ,
  xform.artesian_flow                            ,
  xform.artesian_pressure                        ,
  xform.bedrock_depth                            ,
  xform.water_supply_system_name                 ,
  xform.water_supply_system_well_name            ,
  xform.well_identification_plate_attached      ,
  xform.ems                                      ,
  xform.screen_intake_method_guid                ,
  xform.screen_type_guid                         ,
  xform.screen_material_guid                     ,
  xform.screen_opening_guid                      ,
  xform.screen_bottom_guid                       ,
  xform.utm_zone_code                            ,
  xform.utm_northing                             ,
  xform.utm_easting                              ,
  xform.utm_accuracy_code                        ,
	xform.bcgs_id                                  ,
  xform.development_method_guid                  ,
  xform.development_duration
FROM xform_gwells_well xform
LEFT OUTER JOIN gwells_intended_water_use use ON xform.WELL_USE_CODE=use.code
LEFT OUTER JOIN gwells_well_status well_status ON xform.STATUS_OF_WELL_GUID=upper(well_status.code)
LEFT OUTER JOIN gwells_licenced_status licenced_status ON xform.LICENCED_STATUS=upper(licenced_status.code)
LEFT OUTER JOIN gwells_land_district     land ON xform.LEGAL_LAND_DISTRICT_CODE=land.code
INNER      JOIN gwells_well_class       class ON xform.CLASS_OF_WELL_CODCLASSIFIED_BY=class.code
LEFT OUTER JOIN gwells_well_subclass subclass ON xform.SUBCLASS_OF_WELL_CLASSIFIED_BY=subclass.code AND subclass.well_class_guid = class.well_class_guid;

\echo 'xform data imported into the gwells_well table';

\t
SELECT count(*) || ' rows loaded into the gwells_well table' from gwells_well;
\t

DROP TABLE IF EXISTS xform_gwells_well;
