FROM crunchydata/crunchy-postgres-gis:centos7-12.2-4.2.2

RUN yum install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm && \
  yum install postgresql96 postgresql96-server
