# Generated by Django 2.1.7 on 2019-03-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0001_squashed_0009_auto_20181116_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_gwells_admin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='realm',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='smgov_userdisplayname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='smgov_useremail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='smgov_useridentifier',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
