# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0002_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincestatecode',
            name='province_state_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_introduction_text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Introduction Text'),
        ),
    ]
