# Generated by Django 2.2.10 on 2020-02-13 17:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gwells.db_comments.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0108_auto_20200213_1741'),
        ('aquifers', '0028_auto_20200213_1741'),
        ('gwells', '0003_auto_20190724_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkWellAquiferCorrelationHistory',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_user', models.CharField(max_length=60)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(db_column='bulk_well_aquifer_correlation_history_id', primary_key=True, serialize=False, verbose_name='Bulk History Id')),
                ('update_from_aquifer', models.ForeignKey(blank=True, db_column='from_aquifer_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='aquifers.Aquifer', verbose_name='Aquifer ID Number')),
                ('update_to_aquifer', models.ForeignKey(db_column='to_aquifer_id', on_delete=django.db.models.deletion.PROTECT, to='aquifers.Aquifer', verbose_name='Aquifer ID Number')),
                ('well', models.ForeignKey(db_column='well_tag_number', on_delete=django.db.models.deletion.PROTECT, to='wells.Well')),
            ],
            options={
                'db_table': 'bulk_well_aquifer_correlation_history',
            },
            bases=(models.Model, gwells.db_comments.model_mixins.DBComments),
        ),
    ]
