# Generated by Django 2.2.10 on 2020-02-07 23:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import gwells.db_comments.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0003_auto_20190724_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkHistory',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_user', models.CharField(max_length=60)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(db_column='bulk_history_id', primary_key=True, serialize=False, verbose_name='Bulk History Id')),
                ('operation_name', models.CharField(max_length=60)),
                ('record', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'bulk_history',
                'ordering': ['-created_date'],
            },
            bases=(models.Model, gwells.db_comments.model_mixins.DBComments),
        ),
    ]
