# Generated by Django 2.2.10 on 2020-02-25 21:47

from django.db import migrations, models
import django.db.models.deletion

# NOTE: That this isn't actually a no-op migration. This migration actually adds the related_name field.

class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0004_bulkwellaquifercorrelationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkwellaquifercorrelationhistory',
            name='update_from_aquifer',
            field=models.ForeignKey(blank=True, db_column='from_aquifer_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='update_from_aquifer', to='aquifers.Aquifer', verbose_name='Aquifer ID Number'),
        ),
        migrations.AlterField(
            model_name='bulkwellaquifercorrelationhistory',
            name='update_to_aquifer',
            field=models.ForeignKey(db_column='to_aquifer_id', on_delete=django.db.models.deletion.PROTECT, related_name='update_to_aquifer', to='aquifers.Aquifer', verbose_name='Aquifer ID Number'),
        ),
    ]
