# Generated by Django 2.2.10 on 2020-03-02 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0005_weird_no_op_migration_20200225_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkwellaquifercorrelationhistory',
            name='update_from_aquifer',
            field=models.ForeignKey(blank=True, db_column='from_aquifer_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='update_from_aquifer_set', to='aquifers.Aquifer', verbose_name='Aquifer ID Number'),
        ),
        migrations.AlterField(
            model_name='bulkwellaquifercorrelationhistory',
            name='update_to_aquifer',
            field=models.ForeignKey(db_column='to_aquifer_id', on_delete=django.db.models.deletion.PROTECT, related_name='update_to_aquifer_set', to='aquifers.Aquifer', verbose_name='Aquifer ID Number'),
        ),
    ]
