# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0005_auto_20180629_0024'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='lithologydescription',
            name='activity_submission',
        ),
        migrations.RemoveField(
            model_name='lithologydescription',
            name='bedrock_material',
        ),
        migrations.RemoveField(
            model_name='lithologydescription',
            name='bedrock_material_descriptor',
        ),
        migrations.RemoveField(
            model_name='lithologydescription',
            name='lithology_colour',
        ),
        migrations.RemoveField(
            model_name='lithologydescription',
            name='lithology_description',
        ),
        migrations.RemoveField(
            model_name='lithologydescription',
            name='lithology_hardness',
        ),
        migrations.RemoveField(
            model_name='lithologydescription',
            name='lithology_material',
        ),
        migrations.RemoveField(
            model_name='lithologydescription',
            name='lithology_moisture',
        ),
        migrations.RemoveField(
            model_name='lithologydescription',
            name='lithology_structure',
        ),
        migrations.RemoveField(
            model_name='lithologydescription',
            name='secondary_surficial_material',
        ),
        migrations.RemoveField(
            model_name='lithologydescription',
            name='surficial_material',
        ),
        migrations.RemoveField(
            model_name='lithologydescription',
            name='water_bearing_estimated_flow_units',
        ),
        migrations.RemoveField(
            model_name='lithologydescription',
            name='well_tag_number',
        ),
        migrations.DeleteModel(
            name='LithologyDescription',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
