# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0006_auto_20180724_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincestatecode',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterField(
            model_name='provincestatecode',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
