# Generated by Django 2.1.8 on 2019-04-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0007_drop_replications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrockmaterialcode',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='bedrockmaterialdescriptorcode',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='lithologycolourcode',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='lithologydescriptioncode',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='lithologyhardnesscode',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='lithologymaterialcode',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='lithologymoisturecode',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='lithologystructurecode',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='provincestatecode',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='screenassemblytypecode',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='screenbottomcode',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='screenintakemethodcode',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='screenmaterialcode',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='screenopeningcode',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='screentypecode',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='surficialmaterialcode',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='survey',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
    ]
