# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-07 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0007_auto_20180726_1909'),
    ]

    operations = [
    ]
