# Generated by Django 3.2 on 2024-06-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0008_profile_silver_keycloak_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='border',
            name='afctd_area',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='border',
            name='oic_number',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='border',
            name='oic_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='border',
            name='se_a_c_flg',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='border',
            name='shape',
            field=models.FloatField(null=True),
        ),
    ]
