# Generated by Django 2.1.8 on 2019-05-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0008_auto_20190409_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lithologymaterialcode',
            options={'ordering': ['display_order', 'description']},
        ),
    ]
