# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-16 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0008_auto_20180807_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinesurvey',
            name='survey_page',
            field=models.CharField(choices=[('w', 'well'), ('r', 'registry'), ('s', 'search'), ('a', 'aquifer')], default='w', max_length=1, verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_page',
            field=models.CharField(choices=[('w', 'well'), ('r', 'registry'), ('s', 'search'), ('a', 'aquifer')], default='w', max_length=1, verbose_name='Page'),
        ),
    ]
