# Generated by Django 2.1.7 on 2019-03-05 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0002_auto_20190301_2303'),
        ('gwells', '0010_border'),
    ]

    operations = [
    ]
