apiVersion: batch/v2alpha1
kind: ScheduledJob
metadata:
  name: postgresql
spec:
  schedule: "30 22 * * *"  
  jobTemplate:             
    spec:
      template:
        spec:
          containers:
          - name: postgresql
            image: moe-gwells-tools/openshift-postgresql-oracle-fdw
            command: ["psql -d gwells -c 'select gwells_replicate();'"]
          restartPolicy: Never
          
