# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 20:26
from __future__ import unicode_literals

from django.db import migrations, models


def insert_well_activity_code(apps, schema_editor):
    data = {
        'CON': {
            "description": "Construction report",
            "display_order": 1
        },
        'ALT': {
            "description": "Alteration report",
            "display_order": 1
        },
        'DEC': {
            "description": "Decomission report",
            "display_order": 1
        },
        'STAFF_EDIT': {
            "description": "Staff edit",
            "display_order": 1
        },
        'LEGACY': {
            "description": "Legacy record",
            "display_order": 1
        }
    }
    WellActivityCode = apps.get_model('submissions', 'WellActivityCode')

    for (key, value) in data.items():
        WellActivityCode.objects.update_or_create(well_activity_type_code=key, defaults=value)


def revert(apps, schema_editor):
    # Deleting these could be dangerous (we don't want to cascade delete the submissions),
    # so we do nothing here.
    logger.warn('Not deleting WellActivityCode records! That would be dangerous.')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    state_operations = [
        migrations.CreateModel(
            name='WellActivityCode',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('well_activity_type_code', models.CharField(
                    editable=False, max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'well_activity_code',
                'ordering': ['display_order', 'description'],
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.RunPython(insert_well_activity_code, revert),
    ]
