# Generated by Django 2.1.8 on 2019-04-10 18:31

from django.db import migrations
from django.db.models import Q

from gwells.models import DATALOAD_USER


def fix_bad_submissions(apps, schema_editor):
    # NOTE: Don't squash this - when you squash, just get rid of this!
    # This fix was for a bug we had in production, where create and update user wasn't being pulled
    # correctly from the old record. If this has run in prod, it never has to run again anywhere - so
    # just get rid of it!
    ActivitySubmission = apps.get_model('wells', 'ActivitySubmission')
    ActivitySubmission.objects.filter(
        Q(create_user__isnull=True) | Q(create_user='')).update(create_user=DATALOAD_USER)
    ActivitySubmission.objects.filter(
        Q(update_user__isnull=True) | Q(update_user='')).update(update_user=DATALOAD_USER)


def revert_bad_submissions(apps, schema_editor):
    # We don't borther reverting.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_squashed_0069_auto_20190409_1634'),
    ]

    operations = [
        migrations.RunPython(fix_bad_submissions, revert_bad_submissions),
    ]
