# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):
    atomic = settings.DATABASES.get('default').get('engine') == 'django.db.backends.postgresql'

    dependencies = [
        ('wells', '0004_auto_20180724_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casingmaterialcode',
            old_name='casing_material_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='casingcode',
            old_name='casing_code',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='casing',
            name='activity_submission',
            field=models.ForeignKey(blank=True, db_column='filing_number', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casings', to='wells.ActivitySubmission'),
        ),
        migrations.AlterField(
            model_name='casingcode',
            name='code',
            field=models.CharField(db_column='casing_code', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='casingmaterialcode',
            name='code',
            field=models.CharField(db_column='casing_material_code', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
