# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-17 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0001_initial'),
        ('wells', '0007_auto_20180816_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='AquiferVulnerablityCode',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='aquifer_vulnerablity_code', max_length=1, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Aquifer Vulnerability Codes',
                'db_table': 'aquifer_vulnerablity_code',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='HydraulicProperty',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('hydraulic_property_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storativity', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True, verbose_name='Storativity')),
                ('transmissivity', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Transmissivity')),
                ('hydraulic_conductivity', models.TextField(blank=True, max_length=100, null=True, verbose_name='Hydraulic Conductivity')),
                ('specific_storage', models.TextField(blank=True, max_length=100, null=True, verbose_name='Specific Storage')),
                ('specific_yield', models.TextField(blank=True, max_length=100, null=True, verbose_name='Specific Yield')),
                ('testing_method', models.TextField(blank=True, max_length=100, null=True, verbose_name='Testing Method')),
                ('testing_duration', models.TextField(blank=True, max_length=100, null=True, verbose_name='Testing Duration')),
                ('analytic_solution_type', models.TextField(blank=True, max_length=100, null=True, verbose_name='Analytic Solution Type')),
                ('boundary_effect', models.TextField(blank=True, max_length=100, null=True, verbose_name='Boundary Effect')),
                ('avi', models.ForeignKey(blank=True, db_column='aquifer_vulnerablity_code', null=True, on_delete=django.db.models.deletion.PROTECT, to='wells.AquiferVulnerablityCode', verbose_name='AVI Reference')),
            ],
            options={
                'verbose_name_plural': 'Hydraulic Properties',
                'db_table': 'hydraulic_property',
            },
        ),
        migrations.AddField(
            model_name='well',
            name='aquifer',
            field=models.ForeignKey(blank=True, db_column='aquifer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='aquifers.Aquifer', verbose_name='Aquifer ID Number'),
        ),
        migrations.AddField(
            model_name='hydraulicproperty',
            name='well_tag_number',
            field=models.ForeignKey(db_column='well_tag_number', on_delete=django.db.models.deletion.CASCADE, to='wells.Well'),
        ),
    ]
