# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0009_auto_20180911_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysubmission',
            name='water_quality_characteristics',
        ),
        migrations.RemoveField(
            model_name='waterqualitycharacteristic',
            name='water_quality_characteristic_guid',
        ),
        migrations.RemoveField(
            model_name='well',
            name='water_quality_characteristics',
        ),
        migrations.AlterField(
            model_name='waterqualitycharacteristic',
            name='code',
            field=models.CharField(db_column='water_quality_characteristic_code', max_length=10, primary_key=True, serialize=False),
        ),
    ]
