# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 17:48
from __future__ import unicode_literals

from django.db import migrations
import json
from io import open
import os
from gwells.codes import CodeFixture
from wells.models import WaterQualityCharacteristic, WaterQualityColour


def water_quality_codes():
    fixture = '0010_water_quality_codes.json'
    fixture_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), fixture)

    return CodeFixture(fixture_path)


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0009_auto_20180911_2330'),
    ]

    operations = [
        migrations.RunPython(water_quality_codes().load_fixture, reverse_code=water_quality_codes().unload_fixture),
    ]
