# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0010_auto_20180917_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='water_quality_characteristics',
            field=models.ManyToManyField(blank=True, db_table='activity_submission_water_quality', to='wells.WaterQualityCharacteristic', verbose_name='Obvious Water Quality Characteristics'),
        ),
        migrations.AddField(
            model_name='well',
            name='water_quality_characteristics',
            field=models.ManyToManyField(blank=True, db_table='well_water_quality', to='wells.WaterQualityCharacteristic', verbose_name='Obvious Water Quality Characteristics'),
        ),
    ]
