# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 17:48
from __future__ import unicode_literals

from django.db import migrations
import json
from io import open
import os
from gwells.codes import CodeFixture
from wells.models import WaterQualityCharacteristic, WaterQualityColour
from wells import data_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0011_auto_20180917_1728'),
    ]

    operations = [
        migrations.RunPython(data_migrations.load_water_quality_codes, reverse_code=data_migrations.unload_water_quality_codes),
    ]
