# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0012_load_water_quality_codes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linermaterialcode',
            old_name='liner_material_code',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='linermaterialcode',
            name='code',
            field=models.CharField(db_column='liner_material_code', editable=False, max_length=10, primary_key=True, serialize=False),
        )
    ]
