# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0013_auto_20180820_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linerperforation',
            old_name='liner_perforation_from',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='linerperforation',
            old_name='liner_perforation_to',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='casing',
            old_name='casing_from',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='casing',
            old_name='casing_to',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='screen',
            old_name='screen_from',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='screen',
            old_name='screen_to',
            new_name='end',
        ),
    ]
