# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 21:43
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0014_auto_20180917_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casing',
            options={'ordering': ['start', 'end']},
        ),
        migrations.AlterModelOptions(
            name='linerperforation',
            options={'ordering': ['start', 'end']},
        ),
        migrations.AlterModelOptions(
            name='screen',
            options={'ordering': ['start', 'end']},
        ),
        migrations.AlterField(
            model_name='casing',
            name='end',
            field=models.DecimalField(blank=True, db_column='casing_to', decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='casing',
            name='start',
            field=models.DecimalField(blank=True, db_column='casing_from', decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='linerperforation',
            name='activity_submission',
            field=models.ForeignKey(blank=True, db_column='filing_number', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linerperforation_set', to='wells.ActivitySubmission'),
        ),
        migrations.AlterField(
            model_name='linerperforation',
            name='end',
            field=models.DecimalField(db_column='liner_perforation_to', decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Perforated To'),
        ),
        migrations.AlterField(
            model_name='linerperforation',
            name='start',
            field=models.DecimalField(db_column='liner_perforation_from', decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Perforated From'),
        ),
        migrations.AlterField(
            model_name='linerperforation',
            name='well',
            field=models.ForeignKey(blank=True, db_column='well_tag_number', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linerperforation_set', to='wells.Well'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='activity_submission',
            field=models.ForeignKey(blank=True, db_column='filing_number', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screen_set', to='wells.ActivitySubmission'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='end',
            field=models.DecimalField(db_column='screen_to', decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='start',
            field=models.DecimalField(blank=True, db_column='screen_from', decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='well',
            field=models.ForeignKey(blank=True, db_column='well_tag_number', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screen_set', to='wells.Well'),
        ),
    ]
