# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-18 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0015_auto_20180917_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydraulicProperty',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('hydraulic_property_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storativity', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True, verbose_name='Storativity')),
                ('transmissivity', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Transmissivity')),
                ('hydraulic_conductivity', models.TextField(blank=True, max_length=100, null=True, verbose_name='Hydraulic Conductivity')),
                ('specific_storage', models.TextField(blank=True, max_length=100, null=True, verbose_name='Specific Storage')),
                ('specific_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Specific Yield')),
                ('testing_method', models.TextField(blank=True, max_length=100, null=True, verbose_name='Testing Method')),
                ('testing_duration', models.PositiveIntegerField()),
                ('analytic_solution_type', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Analytic Solution Type')),
                ('boundary_effect', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Boundary Effect')),
                # This is a redundant foreign key reference! We never used this link!
                # ('avi', models.ForeignKey(blank=True, db_column='aquifer_vulnerablity_code', null=True, on_delete=django.db.models.deletion.PROTECT, to='wells.AquiferVulnerabilityCode', verbose_name='AVI Reference')),
                ('avi', models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True, verbose_name='AVI')),
            ],
            options={
                'verbose_name_plural': 'Hydraulic Properties',
                'db_table': 'hydraulic_property',
            },
        ),
        migrations.AddField(
            model_name='well',
            name='aquifer',
            # field=models.ForeignKey(blank=True, db_column='aquifer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='aquifers.Aquifer', verbose_name='Aquifer ID Number'),
            field=models.IntegerField(blank=True, null=True),

        ),
        migrations.AddField(
            model_name='hydraulicproperty',
            name='well',
            field=models.ForeignKey(db_column='well_tag_number', on_delete=django.db.models.deletion.CASCADE, to='wells.Well'),
        ),
    ]
