# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-26 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0016_auto_20180918_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='ems_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
