# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 20:22
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0017_update_casing_material_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecommissionDescription',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('decommission_description_guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start', models.DecimalField(db_column='decommission_description_from', decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Decommissioned From')),
                ('end', models.DecimalField(db_column='decommission_description_to', decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Decommissioned To')),
                ('observations', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecommissionMaterialCode',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='decommission_material_code', max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='backfill_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Backfill Material'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='decommission_details',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Decommission Details'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='decommission_method',
            field=models.ForeignKey(blank=True, db_column='decommission_method_code', null='True', on_delete=django.db.models.deletion.CASCADE, to='wells.DecommissionMethodCode', verbose_name='Method of Decommission'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='decommission_reason',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Reason for Decommission'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='sealant_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sealant Material'),
        ),
        migrations.AddField(
            model_name='decommissiondescription',
            name='material',
            field=models.ForeignKey(db_column='decommission_material_code', on_delete=django.db.models.deletion.PROTECT, to='wells.DecommissionMaterialCode'),
        ),
    ]
