# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 16:56
from __future__ import unicode_literals

from django.db import migrations
import json
from io import open
import os
from gwells.codes import CodeFixture
from wells import data_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0017_auto_20180926_2104'),
    ]

    operations = [
        migrations.RunPython(data_migrations.load_aquifer_vulnerability_codes, reverse_code=data_migrations.unload_aquifer_vulnerability_codes),
    ]
