# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0017_update_casing_material_code'),
    ]

    # If this migration fails, it means you have bad data in your database that you have to resolve 1st!
    operations = [
        migrations.AlterField(
            model_name='well',
            name='legal_pid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Property Identification Description (PID)'),
        ),
    ]
