# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-24 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0017_well_aquifer_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydraulicproperty',
            name='testing_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
