# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0018_auto_change_pid_to_positive_integerfield_20180925_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lithologydescription',
            old_name='well_tag_number',
            new_name='well',
        ),
    ]
