# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-27 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0019_auto_20180924_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydraulicproperty',
            name='avi',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='AVI'),
        ),
    ]
