# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 19:56
from __future__ import unicode_literals

from django.db import migrations, models, DataError

from wells import data_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0021_delete_aquifervulnerabilitycode'),
    ]

    operations = [
        migrations.RunPython(data_migrations.change_code_description, reverse_code=data_migrations.restore_code_description),        
    ]
