# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 19:56
from __future__ import unicode_literals

from django.db import migrations, models, DataError
import django.db.models.deletion

from wells import data_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0021_delete_aquifervulnerabilitycode'),
        ('aquifers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(data_migrations.change_code_description, reverse_code=data_migrations.restore_code_description),
        migrations.AlterField(
            model_name='well',
            name='aquifer',
            field=models.ForeignKey(blank=True, db_column='aquifer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='aquifers.Aquifer', verbose_name='Aquifer ID Number'),
        ),
    ]
