# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-01 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0024_auto_20180925_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='decommissiondescription',
            name='activity_submission',
            field=models.ForeignKey(blank=True, db_column='filing_number', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decommission_description_set', to='wells.ActivitySubmission'),
        ),
        migrations.AddField(
            model_name='decommissiondescription',
            name='well',
            field=models.ForeignKey(blank=True, db_column='well_tag_number', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decommission_description_set', to='wells.Well'),
        ),
    ]
