# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0013_auto_20180712_2107'),
        ('wells', '0026_decommission_material_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='consultant_company',
            field=models.CharField(max_length=200, null=True, verbose_name='Consultant Company'),
        ),
        migrations.AddField(
            model_name='well',
            name='consultant_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Consultant Name'),
        ),
        migrations.AddField(
            model_name='well',
            name='driller_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Name of Person Who Did the Work'),
        ),
        migrations.AddField(
            model_name='well',
            name='driller_responsible',
            field=models.ForeignKey(db_column='driller_responsible_guid', null=True, on_delete=django.db.models.deletion.PROTECT, to='registries.Person', verbose_name='Person Responsible for Drilling'),
        ),
    ]
