# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-16 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0028_auto_20181116_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='owner_tel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telephone number'),
        ),
    ]
