# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-19 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0029_auto_20181116_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='backfill_above_surface_seal',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Backfill Material Above Surface Seal'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Town/City'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='comments',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='consultant_company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Consultant Company'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='consultant_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Consultant Name'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='decommission_method',
            field=models.ForeignKey(blank=True, db_column='decommission_method_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.DecommissionMethodCode', verbose_name='Method of Decommission'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='development_notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Development Notes'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='diameter',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='driller_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of Person Who Did the Work'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='ems_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='legal_block',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Block'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='legal_district_lot',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='District Lot'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='legal_lot',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Lot'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='legal_plan',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='legal_range',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Range'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='legal_section',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='legal_township',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Township'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='other_drilling_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Specify Other Drilling Method'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='other_screen_bottom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Specify Other Screen Bottom'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='other_screen_material',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Specify Other Screen Material'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='owner_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Town/City'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='owner_full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Owner Name'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='owner_mailing_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mailing Address'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='owner_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='owner_province_state',
            field=models.ForeignKey(blank=True, db_column='province_state_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.ProvinceStateCode', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='water_quality_colour',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Water Quality Colour'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='water_quality_odour',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Water Quality Odour'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='water_supply_system_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Water Supply System Name'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='water_supply_system_well_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Water Supply System Well Name'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='well_cap_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Well Cap Type'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='well_class',
            field=models.ForeignKey(blank=True, db_column='well_class_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.WellClassCode', verbose_name='Well Class'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='well_location_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Well Location Description'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='well_plate_attached',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Well Identification Plate Is Attached'),
        ),
    ]
