# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-19 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0030_auto_20181119_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='consultant_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Consultant Name'),
        ),
    ]
