# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-19 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0032_auto_20181119_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='driller_responsible',
            field=models.ForeignKey(blank=True, db_column='driller_responsible_guid', null=True, on_delete=django.db.models.deletion.PROTECT, to='registries.Person', verbose_name='Person Responsible for Drilling'),
        ),
    ]
