# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0034_auto_20181127_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='owner_tel',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telephone number'),
        ),
    ]
