# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0034_auto_20181127_0230'),
        ('wells', '0035_auto_20181130_1812'),
    ]

    operations = [
    ]
