# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 17:22
from __future__ import unicode_literals

from django.utils import timezone
import pytz
import logging

from django.db import migrations, models
import django.db.models.deletion


logger = logging.getLogger(__name__)


DATA = {
    'A': '(10 m accuracy)  ICF cadastre and good location sketch',
    'B': '(20 m accuracy) Digitized from 1:5,000 mapping',
    'C': '(50 m accuracy) Digitized from 1:20,000 mapping',
    'D': '(100 m accuracy) Digitized from old Dept. of Lands, Forests and Water Resources maps',
    'E': '(200 m accuracy) Digitized from 1:50,000 maps',
    'F': '(1 m accuracy) CDGPS',
    'G': ('(unknown, accuracy based on parcel size) No ICF cadastre, poor or no location sketch; site ' +
          'located in center of primary parcel'),
    'H': '(10 m accuracy) Handheld GPS with accuracy of +/- 10 metres',
    'I': '(20 m accuracy) No ICF cadastre but good location sketch or good written description',
    'J': ('unknown, accuracy based on parcel size) ICF cadastre, poor or no location sketch, ' +
          'arbitrarily located in center of parcel'),
}


def load_data(apps, schema_editor):
    CoordinateAcquisitionCode = apps.get_model(
        'wells', 'CoordinateAcquisitionCode')
    for (key, value) in DATA.items():
        code = CoordinateAcquisitionCode()
        code.code = key
        code.create_user = "DATALOAD_USER"
        code.create_date = timezone.now()
        code.description = value
        code.effective_date = timezone.now()
        code.save()


def unload_data(apps, schema_editor):
    CoordinateAcquisitionCode = apps.get_model(
        'wells', 'CoordinateAcquisitionCode')
    for key in DATA:
        try:
            code = CoordinateAcquisitionCode.objects.get(code=key)
            code.delete()
        except:
            # We don't panic too much if this fails, the table is going to be dropped!
            logger.error('failed to delete {}'.format(key))


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0037_merge_20181204_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinateAcquisitionCode',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='coordinate_acquisition_code', editable=False, max_length=1,
                                          primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('effective_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coordinate_acquisition_code',
                'ordering': ['code'],
            },
        ),
        migrations.RunPython(load_data, reverse_code=unload_data),
        migrations.RenameField(
            model_name='well',
            old_name='utm_accuracy_code',
            new_name='coordinate_acquisition_code',
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='coordinate_acquisition_code',
            field=models.ForeignKey(blank=True, db_column='coordinate_acquisition_code', null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='wells.CoordinateAcquisitionCode',
                                    verbose_name='Location Accuracy Code'),
        ),
        migrations.AlterField(
            model_name='well',
            name='coordinate_acquisition_code',
            field=models.ForeignKey(blank=True, db_column='coordinate_acquisition_code', null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='wells.CoordinateAcquisitionCode',
                                    verbose_name='Location Accuracy Code'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='coordinate_acquisition_code',
            field=models.ForeignKey(blank=True, db_column='coordinate_acquisition_code', null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='wells.CoordinateAcquisitionCode',
                                    verbose_name='Location Accuracy Code'),
        ),
        migrations.AlterField(
            model_name='well',
            name='coordinate_acquisition_code',
            field=models.ForeignKey(blank=True, db_column='coordinate_acquisition_code', null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='wells.CoordinateAcquisitionCode',
                                    verbose_name='Location Accuracy Code'),
        ),
    ]
