# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from wells import data_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0037_merge_20181204_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinateAcquisitionCode',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='coordinate_acquisition_code', editable=False, max_length=1,
                                          primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('effective_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coordinate_acquisition_code',
                'ordering': ['code'],
            },
        ),
        migrations.RunPython(data_migrations.load_coordinate_aquisition_data, reverse_code=data_migrations.unload_coordinate_aquisition_data),
        migrations.RenameField(
            model_name='well',
            old_name='utm_accuracy_code',
            new_name='coordinate_acquisition_code',
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='coordinate_acquisition_code',
            field=models.ForeignKey(blank=True, db_column='coordinate_acquisition_code', null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='wells.CoordinateAcquisitionCode',
                                    verbose_name='Location Accuracy Code'),
        ),
        migrations.AlterField(
            model_name='well',
            name='coordinate_acquisition_code',
            field=models.ForeignKey(blank=True, db_column='coordinate_acquisition_code', null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='wells.CoordinateAcquisitionCode',
                                    verbose_name='Location Accuracy Code'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='coordinate_acquisition_code',
            field=models.ForeignKey(blank=True, db_column='coordinate_acquisition_code', null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='wells.CoordinateAcquisitionCode',
                                    verbose_name='Location Accuracy Code'),
        ),
        migrations.AlterField(
            model_name='well',
            name='coordinate_acquisition_code',
            field=models.ForeignKey(blank=True, db_column='coordinate_acquisition_code', null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='wells.CoordinateAcquisitionCode',
                                    verbose_name='Location Accuracy Code'),
        ),
    ]
