# Generated by Django 2.1.4 on 2018-12-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0037_merge_20181204_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='id_plate_attached_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Well identification plate attached by'),
        ),
        migrations.AddField(
            model_name='well',
            name='id_plate_attached_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Well identification plate attached by'),
        ),
    ]
