# Generated by Django 2.1.4 on 2018-12-06 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0038_auto_20181206_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitysubmission',
            old_name='well_plate_attached',
            new_name='well_identification_plate_attached',
        ),
    ]
