# Generated by Django 2.1.4 on 2018-12-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0040_activitysubmission_well_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='backfill_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Backfill Depth'),
        ),
        migrations.AddField(
            model_name='well',
            name='surface_seal_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Surface Seal Depth'),
        ),
    ]
