# Generated by Django 2.1.4 on 2018-12-10 22:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0040_activitysubmission_well_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='screen_information',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Screen Information'),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='recommended_pump_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Recommended pump depth'),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='recommended_pump_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Recommended pump rate'),
        ),
        migrations.AddField(
            model_name='well',
            name='screen_information',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Screen Information'),
        ),
    ]
