# Generated by Django 2.1.4 on 2018-12-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0041_auto_20181211_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='backfill_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Backfill Material Above Surface Seal'),
        ),
    ]
