# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 16:56
from __future__ import unicode_literals

from django.db import migrations
import json
from io import open
import os
from wells import data_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0042_activitysubmission_backfill_type'),
    ]

    operations = [
        migrations.RunPython(data_migrations.load_filter_pack_codes, reverse_code=data_migrations.unload_filter_pack_codes),
    ]
