# Generated by Django 2.1.4 on 2018-12-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0044_auto_20181210_2209'),
        ('wells', '0038_coordinate_acquisition_code'),
    ]

    operations = [
    ]
