# Generated by Django 2.1.4 on 2018-12-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0045_merge_20181213_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='internal_comments',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='internal_comments',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
