# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-10 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0047_auto_20190108_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='observation_well_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Observation Well Number'),
        ),
        migrations.AlterField(
            model_name='well',
            name='observation_well_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Observation Well Number'),
        ),
    ]
