# Generated by Django 2.1.4 on 2018-12-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0047_activitysubmission_aquifer'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='analytic_solution_type',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Analytic Solution Type'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='avi',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='AVI'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='boundary_effect',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Boundary Effect'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='hydraulic_conductivity',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Hydraulic Conductivity'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='specific_storage',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Specific Storage'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='specific_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Specific Yield'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='storativity',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True, verbose_name='Storativity'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='testing_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='testing_method',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Testing Method'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='transmissivity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Transmissivity'),
        ),
        migrations.AddField(
            model_name='well',
            name='analytic_solution_type',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Analytic Solution Type'),
        ),
        migrations.AddField(
            model_name='well',
            name='avi',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='AVI'),
        ),
        migrations.AddField(
            model_name='well',
            name='boundary_effect',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Boundary Effect'),
        ),
        migrations.AddField(
            model_name='well',
            name='hydraulic_conductivity',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Hydraulic Conductivity'),
        ),
        migrations.AddField(
            model_name='well',
            name='specific_storage',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Specific Storage'),
        ),
        migrations.AddField(
            model_name='well',
            name='specific_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Specific Yield'),
        ),
        migrations.AddField(
            model_name='well',
            name='storativity',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True, verbose_name='Storativity'),
        ),
        migrations.AddField(
            model_name='well',
            name='testing_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='testing_method',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Testing Method'),
        ),
        migrations.AddField(
            model_name='well',
            name='transmissivity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Transmissivity'),
        ),
    ]
