# Generated by Django 2.1.4 on 2019-01-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0048_auto_20190110_1755'),
        ('wells', '0049_auto_20190107_2334'),
    ]

    operations = [
    ]
