# Generated by Django 2.1.4 on 2019-01-11 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0038_decommission_material_codes'),
        ('wells', '0050_merge_20190110_1944'),
    ]

    operations = [
    ]
