# Generated by Django 2.1.5 on 2019-01-14 19:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0050_merge_20190110_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productiondata',
            name='activity_submission',
        ),
        migrations.RemoveField(
            model_name='productiondata',
            name='well',
        ),
        migrations.RemoveField(
            model_name='productiondata',
            name='well_yield_unit',
        ),
        migrations.RemoveField(
            model_name='productiondata',
            name='yield_estimation_method',
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='drawdown',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='hydro_fracturing_performed',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Hydro-fracturing Performed?'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='hydro_fracturing_yield_increase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Well Yield Increase Due to Hydro-fracturing'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='recommended_pump_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Recommended pump depth'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='recommended_pump_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Recommended pump rate'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='static_level_before_test',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='SWL Before Test'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='yield_estimation_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Estimation Duration'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='yield_estimation_method',
            field=models.ForeignKey(blank=True, db_column='yield_estimation_method_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.YieldEstimationMethodCode', verbose_name='Estimation Method'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='yield_estimation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Estimation Rate'),
        ),
        migrations.AddField(
            model_name='well',
            name='drawdown',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='well',
            name='hydro_fracturing_performed',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Hydro-fracturing Performed?'),
        ),
        migrations.AddField(
            model_name='well',
            name='hydro_fracturing_yield_increase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Well Yield Increase Due to Hydro-fracturing'),
        ),
        migrations.AddField(
            model_name='well',
            name='recommended_pump_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Recommended pump depth'),
        ),
        migrations.AddField(
            model_name='well',
            name='recommended_pump_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Recommended pump rate'),
        ),
        migrations.AddField(
            model_name='well',
            name='static_level_before_test',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='SWL Before Test'),
        ),
        migrations.AddField(
            model_name='well',
            name='yield_estimation_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Estimation Duration'),
        ),
        migrations.AddField(
            model_name='well',
            name='yield_estimation_method',
            field=models.ForeignKey(blank=True, db_column='yield_estimation_method_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.YieldEstimationMethodCode', verbose_name='Estimation Method'),
        ),
        migrations.AddField(
            model_name='well',
            name='yield_estimation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Estimation Rate'),
        ),
        migrations.DeleteModel(
            name='ProductionData',
        ),
    ]
