# Generated by Django 2.1.4 on 2019-01-16 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0051_auto_20190114_1903'),
        ('wells', '0051_merge_20190111_2347'),
    ]

    operations = [
    ]
