# Generated by Django 2.1.4 on 2019-01-25 02:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0053_auto_20190118_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3005, verbose_name='Lat/Long'),
        ),
    ]
