# Generated by Django 2.1.5 on 2019-01-29 21:44

from django.db import migrations
from django.utils import timezone


def forwards(apps, schema):
    CoordinateAcquisitionCode = apps.get_model('wells', 'CoordinateAcquisitionCode')
    CoordinateAcquisitionCode.objects.create(
        code='0',
        description='Not Specified',
        effective_date=timezone.now(),
        create_user='Django Migration')


def backwards(apps, schema):
    CoordinateAcquisitionCode = apps.get_model('wells', 'CoordinateAcquisitionCode')
    codes = CoordinateAcquisitionCode.objects.filter(code='0')
    for code in codes:
        code.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0053_auto_20190118_1838'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=backwards)
    ]
