# Generated by Django 2.1.5 on 2019-01-29 21:44

from django.db import migrations
from django.utils import timezone

from wells import data_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0053_auto_20190118_1838'),
    ]

    operations = [
        migrations.RunPython(data_migrations.load_unspecified_coordinate_aquisition_code, reverse_code=data_migrations.unload_unspecified_coordinate_aquisition_code)
    ]
