# Generated by Django 2.1.4 on 2019-01-31 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0009_auto_20181116_2316'),
        ('wells', '0053_auto_20190118_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='LithologyMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('material_order', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='lithologydescription',
            name='lithology_material',
            field=models.ForeignKey(blank=True, db_column='lithology_material_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lithology_records', to='gwells.LithologyMaterialCode', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='lithologymaterial',
            name='description_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.LithologyDescription'),
        ),
        migrations.AddField(
            model_name='lithologymaterial',
            name='material_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwells.LithologyMaterialCode'),
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='materials',
            field=models.ManyToManyField(through='wells.LithologyMaterial', to='gwells.LithologyMaterialCode'),
        ),
        migrations.AlterUniqueTogether(
            name='lithologymaterial',
            unique_together={('description_id', 'material_order')},
        ),
    ]
