# Generated by Django 2.1.5 on 2019-02-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0054_aquisition_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysubmission',
            name='drilling_method',
        ),
        migrations.RemoveField(
            model_name='activitysubmission',
            name='other_drilling_method',
        ),
        migrations.RemoveField(
            model_name='well',
            name='drilling_method',
        ),
        migrations.RemoveField(
            model_name='well',
            name='other_drilling_method',
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='drilling_methods',
            field=models.ManyToManyField(blank=True, to='wells.DrillingMethodCode', verbose_name='Drilling Methods'),
        ),
        migrations.AddField(
            model_name='well',
            name='drilling_methods',
            field=models.ManyToManyField(blank=True, to='wells.DrillingMethodCode', verbose_name='Drilling Methods'),
        ),
    ]
