# Generated by Django 2.1.5 on 2019-02-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0055_auto_20190204_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysubmission',
            name='development_method',
        ),
        migrations.RemoveField(
            model_name='well',
            name='development_method',
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='development_methods',
            field=models.ManyToManyField(blank=True, to='wells.DevelopmentMethodCode', verbose_name='Development Methods'),
        ),
        migrations.AddField(
            model_name='well',
            name='development_methods',
            field=models.ManyToManyField(blank=True, to='wells.DevelopmentMethodCode', verbose_name='Development Methods'),
        ),
    ]
