# Generated by Django 2.1.7 on 2019-02-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0056_auto_20190205_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitysubmission',
            old_name='backfill_material',
            new_name='decommission_backfill_material',
        ),
        migrations.RenameField(
            model_name='activitysubmission',
            old_name='sealant_material',
            new_name='decommission_sealant_material',
        ),
        migrations.RemoveField(
            model_name='well',
            name='backfill_material',
        ),
        migrations.RemoveField(
            model_name='well',
            name='sealant_material',
        ),
        migrations.AddField(
            model_name='well',
            name='decommission_backfill_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Decommission Backfill Material'),
        ),
        migrations.AddField(
            model_name='well',
            name='decommission_sealant_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Decommission Sealant Material'),
        ),
    ]
