# Generated by Django 2.1.5 on 2019-02-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0056_auto_20190205_1710'),
        ('wells', '0055_auto_20190208_0042'),
    ]

    operations = [
    ]
