# Generated by Django 2.1.7 on 2019-02-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0058_auto_20190213_2128'),
        ('wells', '0057_merge_20190212_1839'),
    ]

    operations = [
    ]
