# Generated by Django 2.1.7 on 2019-02-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0059_merge_20190214_1715'),
        ('wells', '0059_other_code_values'),
    ]

    operations = [
    ]
