# Generated by Django 2.1.7 on 2019-02-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0060_merge_20190215_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='alternative_specs_submitted',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Alternative specs submitted (if required)'),
        ),
    ]
