# Generated by Django 2.1.7 on 2019-02-25 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0010_aquifer_lithology_codes'),
        ('wells', '0061_auto_20190215_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='aquifer_lithology',
            field=models.ForeignKey(blank=True, db_column='aquifer_lithology_code', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='aquifers.AquiferLithologyCode',
                                    verbose_name='Aquifer Lithology'),
        ),
        migrations.AddField(
            model_name='well',
            name='aquifer_lithology',
            field=models.ForeignKey(blank=True, db_column='aquifer_lithology_code', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='aquifers.AquiferLithologyCode',
                                    verbose_name='Aquifer Lithology'),
        ),
    ]
