# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 14:51
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema):
    schema.execute("UPDATE well SET geom = ST_SetSRID(ST_MakePoint(longitude, latitude),3005) "\
    "WHERE geom IS NOT NULL AND longitude IS NOT NULL AND latitude IS NOT NULL ;")

def backwards(apps, schema):
    # It's no big deal if we don't go back
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0062_well_geom'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=backwards)
    ]