# Generated by Django 2.1.7 on 2019-02-22 22:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0062_aquifer_lithology_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3005, verbose_name='Geo-referenced Location of the Well'),
        ),
    ]
