# Generated by Django 2.1.7 on 2019-02-28 22:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0063_well_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysubmission',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='activitysubmission',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='well',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='well',
            name='longitude',
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3005, verbose_name='Geo-referenced Location of the Well'),
        ),
    ]
