# Generated by Django 2.1.7 on 2019-03-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0064_auto_20190228_2236'),
        ('wells', '0065_auto_20190309_0017'),
    ]

    operations = [
    ]
