# Generated by Django 2.1.7 on 2019-03-18 22:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0065_auto_20190309_0017'),
    ]

    operations = [
        # # Values are BC Albers. but we are using WGS84 Lat Lon to avoid rounding errors
        migrations.RunSQL(
            "SELECT UpdateGeometrySRID('well','geom',4326);"
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Geo-referenced Location of the Well'),
        ),
        migrations.AlterField(
            model_name='well',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Geo-referenced Location of the Well'),
        ),
    ]
