# Generated by Django 2.1.7 on 2019-03-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0066_auto_20190318_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='geohash_l5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
