# Generated by Django 2.1.7 on 2019-03-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0066_auto_20190318_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intendedwaterusecode',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Intented Water Use'),
        ),
        migrations.AlterField(
            model_name='licencedstatuscode',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Licenced Status'),
        ),
        migrations.AlterField(
            model_name='wellclasscode',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Well Class'),
        ),
        migrations.AlterField(
            model_name='wellstatuscode',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Well Status'),
        ),
        migrations.AlterField(
            model_name='wellyieldunitcode',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Well Yield Unit'),
        ),
    ]
