# Generated by Django 2.1.7 on 2019-03-14 16:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0066_merge_20190312_1632'),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT UpdateGeometrySRID('well','geom',4326);"
        ),
        migrations.AlterField(
            model_name='well',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Geo-referenced Location of the Well'),
        ),
    ]
