# Generated by Django 2.1.7 on 2019-03-18 22:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0066_auto_20190318_2257'),
    ]

    operations = [
        migrations.RunSQL(
            "update well set geom = ST_SetSrid(ST_MakePoint(longitude, latitude), 4326);"
        ),
        migrations.RunSQL(
            "update activity_submission set geom = ST_SetSrid(ST_MakePoint(longitude, latitude), 4326);"
        ),
        migrations.RemoveField(
            model_name='activitysubmission',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='activitysubmission',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='well',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='well',
            name='longitude',
        ),
    ]
