# Generated by Django 2.1.7 on 2019-03-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0067_geom_updates'),
        ('wells', '0067_auto_20190326_1914'),
    ]

    operations = [
    ]
