# Generated by Django 2.1.7 on 2019-03-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0067_well_geohash_l5'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='geohash_l8',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='geohash_l5',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
