# Generated by Django 2.1.8 on 2019-04-05 22:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_squashed_0069_auto_20190409_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitysubmission',
            old_name='ems_id',
            new_name='ems',
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='aquifer',
            field=models.ForeignKey(blank=True, db_column='aquifer_id', null=True, on_delete=models.deletion.PROTECT,
                                    related_name='wells', to='aquifers.Aquifer', verbose_name='Aquifer ID Number'),
        ),
    ]
