# Generated by Django 2.1.8 on 2019-04-07 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0068_merge_20190328_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='aquifer',
            field=models.ForeignKey(blank=True, db_column='aquifer_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wells', to='aquifers.Aquifer', verbose_name='Aquifer ID Number'),
        ),
    ]
