# Generated by Django 2.1.8 on 2019-04-07 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0019_remove_waterrightslicence_well'),
        ('wells', '0069_auto_20190407_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='aquifers.WaterRightsLicence'),
        ),
    ]
