# Generated by Django 2.1.8 on 2019-04-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_squashed_0069_auto_20190409_1634'),
        ('wells', '0070_ems_id'),
    ]

    operations = [
    ]
