# Generated by Django 2.1.8 on 2019-04-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0002_auto_20190410_1850'),
        ('wells', '0071_merge_20190409_2102'),
    ]

    operations = [
    ]
