# Generated by Django 2.1.7 on 2019-04-16 23:39

from django.db import migrations, models
from django.db.models import F

def migrate_work_dates(apps, schema_editor):
    activity_submission = apps.get_model('wells', 'ActivitySubmission')

    activity_submission.objects.filter(well_activity_type__code__contains="CON").update(
        construction_start_date=F('work_start_date'))
    activity_submission.objects.filter(well_activity_type__code__contains="CON").update(
        construction_end_date=F('work_end_date'))

    activity_submission.objects.filter(well_activity_type__code__contains="LEGACY").update(
        construction_start_date=F('work_start_date'))
    activity_submission.objects.filter(well_activity_type__code__contains="LEGACY").update(
        construction_end_date=F('work_end_date'))

    activity_submission.objects.filter(well_activity_type__code__contains="ALT").update(
        alteration_start_date=F('work_start_date'))
    activity_submission.objects.filter(well_activity_type__code__contains="ALT").update(
        alteration_end_date=F('work_end_date'))

    activity_submission.objects.filter(well_activity_type__code__contains="DEC").update(
        decommission_start_date=F('work_start_date'))
    activity_submission.objects.filter(well_activity_type__code__contains="DEC").update(
        decommission_end_date=F('work_end_date'))


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0072_merge_20190410_2303'),
    ]

    operations = [
        migrations.RunPython(),
        migrations.AddField(
            model_name='activitysubmission',
            name='alteration_end_date',
            field=models.DateField(null=True, verbose_name='Alteration Date'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='alteration_start_date',
            field=models.DateField(null=True, verbose_name='Alteration Start Date'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='construction_end_date',
            field=models.DateField(null=True, verbose_name='Construction Date'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='construction_start_date',
            field=models.DateField(null=True, verbose_name='Construction Start Date'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='decommission_end_date',
            field=models.DateField(null=True, verbose_name='Decommission Date'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='decommission_start_date',
            field=models.DateField(null=True, verbose_name='Decommission Start Date'),
        ),
    ]
