# Generated by Django 2.1.8 on 2019-04-29 21:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gwells.db_comments.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0008_auto_20190409_1634'),
        ('wells', '0073_fix_well_audit_data_and_submissions_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LithologyMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_user', models.CharField(max_length=60)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ordering', models.IntegerField()),
                ('lithology_description_guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.LithologyDescription')),
                ('lithology_material_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwells.LithologyMaterialCode', verbose_name='Material')),
            ],
            options={
                'db_table': 'lithology_material_xref',
                'ordering': ['ordering'],
            },
            bases=(models.Model, gwells.db_comments.model_mixins.DBComments),
        ),
        migrations.CreateModel(
            name='LithologySignificanceCode',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_user', models.CharField(max_length=60)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(db_column='lithology_significance_code', max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, gwells.db_comments.model_mixins.DBComments),
        ),
        migrations.AddField(
            model_name='lithologymaterial',
            name='significance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wells.LithologySignificanceCode'),
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='lithology_materials',
            field=models.ManyToManyField(related_name='materials', through='wells.LithologyMaterial', to='gwells.LithologyMaterialCode'),
        ),
    ]
