# Generated by Django 2.1.8 on 2019-05-01 16:12
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


# NOTE: Don't bother squashing this - once it's run in production this code can be deleted.
def perforation_cleanup(apps, schema_editor):
    # When a well record has a 0 value for liner_from, liner_to, liner_diameter, 
    # And a NULL value for liner_perforation_from, liner_perforation_to, liner_thickness
    # Then remove/delete row(s) of data
    Perforation = apps.get_model('wells', 'Perforation')
    index = 0
    for perforation in\
            Perforation.objects.filter(
                liner_from=0, liner_to=0, liner_diameter=0, liner_perforation_from=None,
                liner_perforation_to=None, liner_thickness=None):
        perforation.delete()
        index += 1
    if index > 0:
        logger.info('{} perforations deleted'.format(index))


def revert_perforation_cleanup(apps, schema_editor):
    # Nothing to do here
    pass


# NOTE: Don't bother squashing this - once it's run in production this code can be deleted.
def casing_cleanup(apps, schema_editor):
    # When a well record has a 0 value for casing_from, casing_to, diameter, 
    # wall_thickness
    # And a NULL value for casing_matieral_code and drive_shoe
    # Then remove/delete row(s) of data
    Casing = apps.get_model('wells', 'Casing')
    index = 0
    for casing in\
            Casing.objects.filter(
                start=0, end=0, diameter=0, wall_thickness=0, casing_material=None, drive_shoe=None):
        casing.delete()
        index += 1
    if index > 0:
        logger.info('{} casings deleted'.format(index))


def revert_casing_cleanup(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=perforation_cleanup,
            reverse_code=revert_perforation_cleanup,
        ),
        migrations.RunPython(
            code=casing_cleanup,
            reverse_code=revert_casing_cleanup,
        ),
    ]
