# Generated by Django 2.1.8 on 2019-05-01 21:58

from django.db import migrations

# squashable because we no longer need this table
class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0074_perforations_cleanup_20190501_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquiferwell',
            name='well_tag_number',
        ),
        migrations.DeleteModel(
            name='AquiferWell',
        ),
    ]
