# Generated by Django 2.1.8 on 2019-05-01 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0074_perforations_cleanup_20190501_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ltsaowner',
            name='province_state',
        ),
        migrations.RemoveField(
            model_name='ltsaowner',
            name='well',
        ),
        migrations.DeleteModel(
            name='LtsaOwner',
        ),
    ]
