# Generated by Django 2.1.8 on 2019-05-02 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0075_auto_20190501_2344'),
        ('wells', '0075_auto_20190501_2158'),
    ]

    operations = [
    ]
