# Generated by Django 2.1.8 on 2019-05-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0075_load_lithology_significance_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lithologydescription',
            name='lithology_materials',
            field=models.ManyToManyField(related_name='lithology_records', through='wells.LithologyMaterial', to='gwells.LithologyMaterialCode'),
        ),
    ]
