# Generated by Django 2.2.1 on 2019-05-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0076_auto_20190502_2322'),
        ('wells', '0076_merge_20190502_2358'),
        ('wells', '0075_update_work_dates'),
    ]

    operations = [
    ]
