# Generated by Django 2.2.1 on 2019-05-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0077_merge_20190506_1715'),
        ('wells', '0077_auto_20190503_1917'),
    ]

    operations = [
    ]
