# Generated by Django 2.1.8 on 2019-05-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_squashed_0079_auto_20190506_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perforation',
            name='well_tag_number',
        ),
        migrations.DeleteModel(
            name='Perforation',
        ),
    ]
