# Generated by Django 2.2.1 on 2019-05-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0077_auto_20190503_1917'),
        ('wells', '0079_update_well_disinfect_values'),
    ]

    operations = [
    ]
