# Generated by Django 2.2.1 on 2019-05-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0080_fix_bad_idir'),
        ('wells', '0081_update_well_disinfect_values'),
    ]

    operations = [
    ]
