# Generated by Django 2.2.1 on 2019-05-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0082_merge_20190509_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='licence',
        ),
    ]
