# Generated by Django 2.2.1 on 2019-05-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0084_merge_20190514_0212'),
        ('wells', '0084_update_intended_water_use'),
    ]

    operations = [
    ]
