# Generated by Django 2.2.1 on 2019-05-14 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0084_move_liner_perforations'),
        ('wells', '0083_merge_20190513_1939'),
    ]

    operations = [
    ]
