# Generated by Django 2.2.1 on 2019-05-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0084_merge_20190514_0212'),
        ('wells', '0086_remove_linerperforation_activity_submission'),
    ]

    operations = [
    ]
