# Generated by Django 2.2.1 on 2019-05-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0087_merge_20190514_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='ems_id',
        ),
    ]
