# Generated by Django 2.2.1 on 2019-05-17 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0088_fieldsprovided'),
        ('wells', '0088_remove_well_ems_id'),
    ]

    operations = [
    ]
