# Generated by Django 2.2.1 on 2019-05-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0088_remove_well_ems_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screen',
            old_name='internal_diameter',
            new_name='diameter',
        ),
    ]
