# Generated by Django 2.2.1 on 2019-05-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0089_auto_20190515_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='well_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Well Yield'),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Well Yield'),
        ),
    ]
