# Generated by Django 2.2.1 on 2019-05-21 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0090_auto_20190521_2033'),
        ('wells', '0089_auto_20190515_2359'),
    ]

    operations = [
    ]
