# Generated by Django 2.2.1 on 2019-05-22 23:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0091_merge_20190521_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lithologydescription',
            old_name='lithology_to',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='lithologydescription',
            old_name='lithology_from',
            new_name='start',
        ),
        migrations.AlterField(
            model_name='lithologydescription',
            name='end',
            field=models.DecimalField(blank=True, db_column='lithology_to', decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='lithologydescription',
            name='start',
            field=models.DecimalField(blank=True, db_column='lithology_from', decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='From'),
        ),
    ]
