# Generated by Django 2.2.2 on 2019-06-18 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0099_update_well_orientation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='coordinate_acquisition_code',
            field=models.ForeignKey(blank=True, null=True, db_column='coordinate_acquisition_code', default='H', on_delete=django.db.models.deletion.PROTECT, to='wells.CoordinateAcquisitionCode', verbose_name='Location Accuracy Code'),
        ),
        migrations.AlterField(
            model_name='well',
            name='coordinate_acquisition_code',
            field=models.ForeignKey(blank=True, null=True, db_column='coordinate_acquisition_code', default='H', on_delete=django.db.models.deletion.PROTECT, to='wells.CoordinateAcquisitionCode', verbose_name='Location Accuracy Code'),
        ),
    ]
