# Generated by Django 2.2.6 on 2019-10-16 21:37

from django.db import migrations
import wells.data_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0102_auto_20190724_1954'),
    ]

    operations = [
        migrations.RunPython(
            code=wells.data_migrations.unload_filter_pack_codes,
            reverse_code=wells.data_migrations.load_filter_pack_codes,
        ),
        migrations.RunPython(
            code=wells.data_migrations.load_filter_pack_codes,
            reverse_code=wells.data_migrations.unload_filter_pack_codes,
        )
    ]
