# Generated by Django 2.2.9 on 2020-01-09 00:31

from django.db import migrations

updateWellUTMValues = """
    UPDATE well SET
    utm_zone_code =
    CASE WHEN ST_X(geom) > -180 AND ST_X(geom) < 180
        THEN Floor((ST_X(geom) + 180) / 6) + 1
        ELSE NULL END,
    utm_easting =
    CASE WHEN ST_X(geom) > -180 AND ST_X(geom) < 180
        THEN ST_X(ST_Transform(geom, (32600 + (Floor(((ST_X(geom) + 180) / 6) + 1))::integer)))
        ELSE NULL END,
    utm_northing =
    CASE WHEN ST_X(geom) > -180 AND ST_X(geom) < 180
        THEN ST_Y(ST_Transform(geom, (32600 + (Floor(((ST_X(geom) + 180) / 6) + 1))::integer)))
        ELSE NULL END;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0104_auto_20191121_2152'),
    ]

    operations = [
        migrations.RunSQL(
            [updateWellUTMValues],
        )
    ]
