# Generated by Django 2.2.9 on 2020-01-16 23:27

from django.db import migrations

# gwells=# \d registries_organization
#            Table "public.registries_organization"
#        Column        |           Type           | Modifiers
# ---------------------+--------------------------+-----------
#  create_user         | character varying(60)    | not null
#  create_date         | timestamp with time zone | not null
#  update_user         | character varying(60)    | not null
#  update_date         | timestamp with time zone | not null
#  org_guid            | uuid                     | not null
#  name                | character varying(200)   | not null
#  street_address      | character varying(100)   |
#  city                | character varying(50)    |
#  postal_code         | character varying(10)    |
#  main_tel            | character varying(15)    |
#  fax_tel             | character varying(15)    |
#  website_url         | character varying(200)   |
#  effective_date      | timestamp with time zone | not null
#  expiry_date         | timestamp with time zone | not null
#  province_state_code | character varying(10)    | not null
#  email               | character varying(254)   |


# gwells=# \d drilling_company
#                Table "public.drilling_company"
#         Column         |           Type           | Modifiers
# -----------------------+--------------------------+-----------
#  create_user           | character varying(60)    | not null
#  create_date           | timestamp with time zone | not null
#  update_user           | character varying(60)    | not null
#  update_date           | timestamp with time zone | not null
#  drilling_company_guid | uuid                     | not null
#  drilling_company_code | character varying(10)    |
#  name                  | character varying(200)   | not null


# NOTE: Loses `drilling_company.drilling_company_code` at the moment.

insertDrillingCompaniesIntoOrg = """
    INSERT INTO registries_organization (create_user, create_date, update_user, update_date, org_guid, name)
        SELECT create_user, create_date, update_user, update_date, drilling_company_guid, name FROM drilling_company;
"""

# Update any wells to use the same GUID which will point to the drilling companies inserted above
updateWellOrgToPointToOldDrillingCompanyGUIDs = """
    UPDATE well
    SET org_of_person_responsible_guid = drilling_company_guid
    WHERE org_of_person_responsible_guid IS NULL;
"""

# Update any legacy submissions to use the same GUID which will point to the drilling companies inserted for the FK-ed well
updateLegacySubmissionToOldDrillingCompanyGUID = """
    UPDATE activity_submission s1
    SET s1.org_of_person_responsible_guid = w.drilling_company_guid
    FROM activity_submission s2
        INNER JOIN well w ON s2.well_tag_number = w.well_tag_number
    WHERE
        s1.org_of_person_responsible_guid IS NULL AND
        s1.well_activity_type_code = 'LEGACY';
"""

class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0105_auto_20200109_0031'),
    ]

    operations = [
        migrations.RunSQL(
            [
                insertDrillingCompaniesIntoOrg,
                updateWellOrgToPointToOldDrillingCompanyGUIDs,
                updateLegacySubmissionToOldDrillingCompanyGUID
            ],
        )
    ]
