# Generated by Django 2.2.11 on 2020-03-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0109_positive_longitude_20200218_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='identification_plate_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Identification Plate Number'),
        ),
    ]
