# Generated by Django 2.2.12 on 2020-05-28 14:13

from django.db import migrations


UPDATE_GWELLS_WELLS_VIEW_SQL = """
    DROP VIEW postgis_ftw.gwells_well_view;
    CREATE VIEW postgis_ftw.gwells_well_view AS
        SELECT
            well_tag_number,
            aquifer_id,
            artesian_flow > 0 AS artesian,
            street_address,
            identification_plate_number,
            ems,
            well_publication_status_code = 'Published' AS is_published,
            geom
        FROM well
        WHERE geom IS NOT NULL;
        GRANT SELECT ON postgis_ftw.gwells_well_view TO ftw_reader;
"""

UPDATE_WALLY_WELLS_VIEW_SQL = """
    DROP VIEW postgis_ftw.wally_well_view;
    CREATE VIEW postgis_ftw.wally_well_view AS
        SELECT
            well_tag_number,
            geom
        FROM well
        WHERE
            geom IS NOT NULL AND
            well_publication_status_code = 'Published';
    GRANT SELECT ON postgis_ftw.wally_well_view TO ftw_reader;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0112_vector_tileserver_wally_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='well',
            options={'verbose_name': 'A well record'},
        ),
        migrations.RunSQL(
            UPDATE_GWELLS_WELLS_VIEW_SQL,
        ),
        migrations.RunSQL(
            UPDATE_WALLY_WELLS_VIEW_SQL,
        ),
    ]
