# Generated by Django 2.2.12 on 2020-05-21 21:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


REMOVE_ZERO_WELL_YIELDS = """
    UPDATE well SET well_yield = NULL WHERE well_yield = 0;
"""
class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0112_vector_tileserver_wally_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='well',
            options={'verbose_name': 'A well record'},
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='well_yield',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Estimated Well Yield'),
        ),
        migrations.RunSQL(
            REMOVE_ZERO_WELL_YIELDS,
        ),
    ]
