# Generated by Django 2.2.13 on 2020-06-16 20:27

from django.db import migrations

ADD_NOT_APPLICABLE_INTENDED_WATER_USE_CODE = """
    INSERT INTO intended_water_use_code
        (
            create_user,
            create_date,
            update_user,
            update_date,
            display_order,
            effective_date,
            expiry_date,
            intended_water_use_code,
            description
        )
        VALUES
        (
            'WELLS',
            '2017-07-01 08:00:00+00',
            'WELLS',
            '2017-07-01 08:00:00+00',
            200,
            '2020-01-01 00:00:00+00',
            '9999-12-31 23:59:59+00',
            'NA',
            'Not Applicable'
        );
"""

UPDATE_WELLS = """
    UPDATE well SET well_class_code = 'UNK' WHERE well_class_code IS NULL;
    UPDATE well SET intended_water_use_code = 'NA' WHERE intended_water_use_code IS NULL;
    UPDATE well
        SET well_class_code = 'WATR_SPPLY'
    WHERE
        intended_water_use_code IN ('DOM', 'COM', 'DWS', 'IRR', 'OP_LP_GEO') AND
        well_class_code = 'UNK';
"""

UPDATE_SUBMISSIONS = """
    UPDATE activity_submission
        SET well_class_code = 'UNK'
    WHERE
        well_class_code IS NULL AND
        well_activity_code = 'CON';

    UPDATE activity_submission
        SET intended_water_use_code = 'NA'
    WHERE
        intended_water_use_code IS NULL AND
        well_activity_code = 'CON';

    UPDATE activity_submission
        SET well_class_code = 'WATR_SPPLY'
    WHERE
        intended_water_use_code IN ('DOM', 'COM', 'DWS', 'IRR', 'OP_LP_GEO') AND
        (well_class_code = 'UNK' OR well_class_code IS NULL);
"""

class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0113_update_tileserver_views_20200528_1413'),
    ]

    operations = [
        migrations.RunSQL([
            ADD_NOT_APPLICABLE_INTENDED_WATER_USE_CODE,
            UPDATE_WELLS,
            UPDATE_SUBMISSIONS,
        ]),
    ]
