# Generated by Django 2.2.18 on 2021-03-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This migration was created to resolve an issue that was found when editing a well.
    If the user sets one of these values to True and saves, then sets a different field value to blank this
        field will default back to False as it doesn't allow null.
    The fields provided tracks changes, and if this cannot be null it will use the default value of False
        that was originally present in the model/ddl
    If we change the fieldsprovided we must also change the activitysubmission as that table only tracks changes
    """
    dependencies = [
        ('wells', '0124_create_artesian_conditions_col_update_data_water_639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldsprovided',
            name='alternative_specs_submitted',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')],
                                      null=True,
                                      verbose_name='Alternative specs submitted (if required)')
        ),
        migrations.AlterField(
            model_name='fieldsprovided',
            name='hydro_fracturing_performed',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')],
                                      null=True,
                                      verbose_name='Hydro-fracturing Performed?')
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='alternative_specs_submitted',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')],
                                      null=True,
                                      verbose_name='Alternative specs submitted (if required)')
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='hydro_fracturing_performed',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')],
                                      null=True,
                                      verbose_name='Hydro-fracturing Performed?')
        )
    ]
