# Generated by Django 2.2.18 on 2021-03-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0126_alter_well_submission_transmissivity_water_1444'),
        ('wells', '0125_refactor_inline_sql_export_wells_water_1545'),
    ]

    operations = [
    ]
