# Generated by Django 2.2.28 on 2023-02-25 00:24

from django.db import migrations

INSERT_CONDUCTOR_CASING_CODE = """
    UPDATE casing_code
    SET display_order = 4
    WHERE casing_code = 'OPEN';

    INSERT INTO casing_Code (
        casing_code,
        create_user,
        create_date,
        update_user,
        update_date,
        effective_date,
        expiry_date,
        description,
        display_order
    )
    VALUES (
        'CONDUCTOR',
        'DATALOAD_USER',
        '2020-01-01T08:00:00Z',
        'DATALOAD_USER',
        '2020-01-01T08:00:00Z',
        '2020-01-01T08:00:00Z',
        '9999-12-31T23:59:59Z',
        'Conductor casing',
        2
    );
"""

REMOVE_CONDUCTOR_CASING_CODE = """
    DELETE FROM casing_code
    WHERE casing_code = 'CONDUCTOR';

    UPDATE casing_code
    SET display_order = 2
    WHERE casing_code = 'OPEN';
"""

class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0137_add_hydraulic_info_postgis_well_view'),
    ]

    operations = [
        migrations.RunSQL(
          INSERT_CONDUCTOR_CASING_CODE,
          REMOVE_CONDUCTOR_CASING_CODE
        )
    ]
