# Generated by Django 2.2.28 on 2023-08-11 18:10

from django.db import migrations, models
import django.db.models.deletion
import datetime
from django.utils.timezone import utc
import gwells.db_comments.model_mixins
import wells.data_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0141_add_drinking_water_protection_area_ind'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLabelCode',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_user', models.CharField(max_length=60)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=utc))),
                ('code', models.CharField(db_column='document_label_code', editable=False, max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'document_label_code',
                'ordering': ['display_order', 'description'],
            },
            bases=(models.Model, gwells.db_comments.model_mixins.DBComments),
        ),
        migrations.RunPython(
            code=wells.data_migrations.load_document_label_codes,
            reverse_code=wells.data_migrations.unload_document_label_codes,
        )
    ]
