# Generated by Django 2.2.28 on 2023-11-09 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0141_add_drinking_water_protection_area_ind'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellAttachment',
            fields=[
                ('well_construction', models.PositiveSmallIntegerField(default=0)),
                ('well_alteration', models.PositiveSmallIntegerField(default=0)),
                ('well_decommission', models.PositiveSmallIntegerField(default=0)),
                ('photo', models.PositiveSmallIntegerField(default=0)),
                ('well_pump_installation', models.PositiveSmallIntegerField(default=0)),
                ('pumping_test', models.PositiveSmallIntegerField(default=0)),
                ('map', models.PositiveSmallIntegerField(default=0)),
                ('additional_well_details', models.PositiveSmallIntegerField(default=0)),
                ('well_inspection', models.PositiveSmallIntegerField(default=0)),
                ('alternative_specs', models.PositiveSmallIntegerField(default=0)),
                ('water_quality', models.PositiveSmallIntegerField(default=0)),
                ('health_authority', models.PositiveSmallIntegerField(default=0)),
                ('consultants_report', models.PositiveSmallIntegerField(default=0)),
                ('well_tag_number', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='wells.Well')),
            ],
            options={
                'db_table': 'well_attachment_count',
            },
        ),
    ]
