# Generated by Django 2.2.28 on 2023-11-23 22:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid

###############
# Update WellAttachment Model to new fields
###############
class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0143_attach_attachments_to_wells'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellattachment',
            old_name='additional_well_details',
            new_name='additional_details',
        ),
        migrations.RenameField(
            model_name='wellattachment',
            old_name='pumping_test',
            new_name='pumping_test_data',
        ),
        migrations.AddField(
            model_name='wellattachment',
            name='directions_artesian_conditions',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wellattachment',
            name='pumping_test_info',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wellattachment',
            name='sharing_agreement',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wellattachment',
            name='artesianmgmtreport',
            field=models.PositiveSmallIntegerField(default=0)
        )
    ]
