# Generated by Django 2.2.28 on 2024-01-05 02:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0146_add_aquifer_parameters_to_wells_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='distance_to_pid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Distance to PID'),
        ),
        migrations.AddField(
            model_name='well',
            name='geocode_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Geocode Distance'),
        ),
        migrations.AddField(
            model_name='well',
            name='score_address',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Score for Address'),
        ),
        migrations.AddField(
            model_name='well',
            name='score_city',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Score for City'),
        ),
        migrations.AddField(
            model_name='well',
            name='cross_referenced',
            field=models.BooleanField(default=False, verbose_name='Cross Referenced'),
        ),
        migrations.AddField(
            model_name='well',
            name='cross_referenced_date',
            field=models.DateTimeField(null=True, default=None),
        ),
        migrations.AddField(
            model_name='well',
            name='cross_referenced_by',
            field=models.CharField(null=True, blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='well',
            name='natural_resource_region',
            field=models.CharField(null=True, blank=True, max_length=200),
        ),
    ]
