# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('street_number', models.IntegerField()),
                ('street_name', models.CharField(max_length=100)),
                ('site_area', models.CharField(max_length=50)),
                ('lot_number', models.CharField(max_length=10)),
                ('legal_plan', models.CharField(max_length=20)),
                ('legal_district_lot', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('identification_plate_number', models.IntegerField()),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=7)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=7)),
                ('well_yield', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WellOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('given_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('street_number', models.IntegerField()),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province_state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwells.ProvinceState')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WellYieldUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='well',
            name='well_owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwells.WellOwner'),
        ),
        migrations.AddField(
            model_name='well',
            name='well_yield_unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwells.WellYieldUnit'),
        ),
    ]
