# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-03 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='intended_water_use',
            field=models.ForeignKey(blank=True, db_column='intended_water_use_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.IntendedWaterUse', verbose_name='Intended Water Use'),
        ),
        migrations.AlterField(
            model_name='well',
            name='ems',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Environmental Monitoring System (EMS) ID'),
        ),
        migrations.AlterField(
            model_name='well',
            name='identification_plate_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Identification Plate Number'),
        ),
        migrations.AlterField(
            model_name='well',
            name='observation_well_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Observation Well Number'),
        ),
        migrations.AlterField(
            model_name='well',
            name='observation_well_status',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Observation Well Status'),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_tag_number',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Well Tag Number'),
        ),
    ]
