# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='well_owner_id',
            field=models.ForeignKey(db_column='gwells_well_owner_id', on_delete=django.db.models.deletion.CASCADE, to='gwells.WellOwner'),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_yield_unit_id',
            field=models.ForeignKey(db_column='gwells_well_yield_unit_id', on_delete=django.db.models.deletion.CASCADE, to='gwells.WellYieldUnit'),
        ),
        migrations.AlterField(
            model_name='wellowner',
            name='province_state_id',
            field=models.ForeignKey(db_column='gwells_province_state_id', on_delete=django.db.models.deletion.CASCADE, to='gwells.ProvinceState'),
        ),
        migrations.AlterModelTable(
            name='provincestate',
            table='gwells_province_state',
        ),
        migrations.AlterModelTable(
            name='wellowner',
            table='gwells_well_owner',
        ),
        migrations.AlterModelTable(
            name='wellyieldunit',
            table='gwells_well_yield_unit',
        ),
    ]
