# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineSurvey',
            fields=[
                ('survey_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('survey_introduction_text', models.TextField(blank=True, max_length=200, null=True, verbose_name='Introduction Text')),
                ('survey_link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('survey_enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('survey_page', models.CharField(choices=[('w', 'well'), ('r', 'registry'), ('s', 'search')], default='w', max_length=1, verbose_name='Page')),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'online_survey',
                'ordering': ['effective_date'],
            },
        ),
    ]
