# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysubmission',
            name='well',
        ),
    ]
