# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0002_profile'),
        ('gwells', '0002_onlinesurvey'),
    ]

    operations = [
    ]
