# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0002_remove_activitysubmission_well'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='well',
            field=models.ForeignKey(blank=True, db_column='well_tag_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.Well'),
        ),
    ]
