# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0002_auto_20170321_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='well',
            old_name='street_name',
            new_name='address_line',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='depth',
            new_name='well_drilled_depth',
        ),
        migrations.RenameField(
            model_name='wellowner',
            old_name='street_name',
            new_name='address_line',
        ),
        migrations.RemoveField(
            model_name='well',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='wellowner',
            name='street_number',
        ),
    ]
