# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0003_activitysubmission_well'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='identification_plate_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Identification Plate Number'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='owner_province_state',
            field=models.ForeignKey(db_column='province_state_guid', on_delete=django.db.models.deletion.CASCADE, to='gwells.ProvinceState', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='ltsaowner',
            name='province_state',
            field=models.ForeignKey(db_column='province_state_guid', on_delete=django.db.models.deletion.CASCADE, to='gwells.ProvinceState', verbose_name='Province'),
        ),
    ]
