# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0003_auto_20170323_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='address_line',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='well',
            name='diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='well',
            name='identification_plate_number',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='legal_district_lot',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='legal_plan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='well',
            name='lot_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='well',
            name='pid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='site_area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_drilled_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_yield',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_yield_unit_id',
            field=models.ForeignKey(blank=True, db_column='gwells_well_yield_unit_id', on_delete=django.db.models.deletion.CASCADE, to='gwells.WellYieldUnit'),
        ),
        migrations.AlterField(
            model_name='wellowner',
            name='given_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wellowner',
            name='province_state_id',
            field=models.ForeignKey(blank=True, db_column='gwells_province_state_id', on_delete=django.db.models.deletion.CASCADE, to='gwells.ProvinceState'),
        ),
    ]
