# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0003_merge_20180312_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='realm',
            field=models.CharField(default='django', max_length=10),
            preserve_default=False,
        ),
    ]
