# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-07 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0003_auto_20171107_2231'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bcgs_numbers',
            table='gwells_bcgs_number',
        ),
    ]
