# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0004_auto_20170323_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='identification_plate_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='legal_district_lot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_drilled_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_yield',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
