# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-07 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0004_auto_20171107_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenassemblytype',
            old_name='screen_assembly_code',
            new_name='screen_assembly_type_code',
        ),
    ]
