# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0004_profile_realm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='realm',
            field=models.CharField(default='Django', max_length=10),
        ),
    ]
