# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0005_auto_20180404_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='aquiferwell',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='aquiferwell',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='bcgs_numbers',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='bcgs_numbers',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='bedrockmaterialcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='bedrockmaterialcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='bedrockmaterialdescriptorcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='bedrockmaterialdescriptorcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casing',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='casing',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casingcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='casingcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casingmaterialcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='casingmaterialcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='decommissionmethodcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='decommissionmethodcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='developmentmethodcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='developmentmethodcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='driller',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='driller',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='drillingcompany',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='drillingcompany',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='drillingmethodcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='drillingmethodcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='filterpackmaterialcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='filterpackmaterialcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='filterpackmaterialsizecode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='filterpackmaterialsizecode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='groundelevationmethodcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='groundelevationmethodcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='intendedwaterusecode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='intendedwaterusecode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='landdistrictcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='landdistrictcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='licencedstatuscode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='licencedstatuscode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='linermaterialcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='linermaterialcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='linerperforation',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='linerperforation',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lithologycolourcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='lithologycolourcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lithologydescription',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='lithologydescription',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lithologydescriptioncode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='lithologydescriptioncode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lithologyhardnesscode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='lithologyhardnesscode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lithologymaterialcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='lithologymaterialcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lithologymoisturecode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='lithologymoisturecode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lithologystructurecode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='lithologystructurecode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ltsaowner',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='ltsaowner',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='obswellstatuscode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='obswellstatuscode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='perforation',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='perforation',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='provincestatecode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='provincestatecode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='screen',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='screenassemblytypecode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='screenassemblytypecode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='screenbottomcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='screenbottomcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='screenintakemethodcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='screenintakemethodcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='screenmaterialcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='screenmaterialcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='screenopeningcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='screenopeningcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='screentypecode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='screentypecode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='surfacesealmaterialcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='surfacesealmaterialcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='surfacesealmethodcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='surfacesealmethodcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='surficialmaterialcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='surficialmaterialcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='survey',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitycharacteristic',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='waterqualitycharacteristic',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='well',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='wellactivitycode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='wellactivitycode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='wellclasscode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='wellclasscode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='wellstatuscode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='wellstatuscode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='wellsubclasscode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='wellsubclasscode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='wellyieldunitcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='wellyieldunitcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='yieldestimationmethodcode',
            name='create_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='yieldestimationmethodcode',
            name='update_user',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
