# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0005_auto_20170323_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellowner',
            name='given_name',
        ),
        migrations.RemoveField(
            model_name='wellowner',
            name='surname',
        ),
        migrations.AddField(
            model_name='well',
            name='well_tag_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wellowner',
            name='full_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
