# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-03 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0005_auto_20171103_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='utm_easting',
            field=models.IntegerField(blank=True, null=True, verbose_name='UTM Eeasting'),
        ),
        migrations.AddField(
            model_name='well',
            name='utm_northing',
            field=models.IntegerField(blank=True, null=True, verbose_name='UTM Northing'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='final_casing_stick_up',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Final Casing Stick Up'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='intended_water_use',
            field=models.ForeignKey(blank=True, db_column='intended_water_use_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.IntendedWaterUse', verbose_name='Intended Water Use'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='well_orientation',
            field=models.BooleanField(choices=[(True, 'vertical'), (False, 'horizontal')], default=True, verbose_name='Orientation of Well'),
        ),
        migrations.AlterField(
            model_name='well',
            name='ems',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Environmental Monitoring System (EMS) ID'),
        ),
        migrations.AlterField(
            model_name='well',
            name='final_casing_stick_up',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Final Casing Stick Up'),
        ),
        migrations.AlterField(
            model_name='well',
            name='identification_plate_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Identification Plate Number'),
        ),
        migrations.AlterField(
            model_name='well',
            name='intended_water_use',
            field=models.ForeignKey(blank=True, db_column='intended_water_use_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.IntendedWaterUse', verbose_name='Intended Water Use'),
        ),
        migrations.AlterField(
            model_name='well',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='well',
            name='legal_pid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Property Identification Description (PID)'),
        ),
        migrations.AlterField(
            model_name='well',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='well',
            name='observation_well_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Observation Well Number'),
        ),
        migrations.AlterField(
            model_name='well',
            name='observation_well_status',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Observation Well Status'),
        ),
        migrations.AlterField(
            model_name='well',
            name='utm_zone_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_disinfected',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Well Disinfected'),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_location_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description of Well Location'),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_orientation',
            field=models.BooleanField(choices=[(True, 'vertical'), (False, 'horizontal')], default=True, verbose_name='Orientation of Well'),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_tag_number',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Well Tag Number'),
        ),
    ]
