# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0006_auto_20170614_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedrockMaterial',
            fields=[
                ('bedrock_material_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gwells_bedrock_material',
                'ordering': ['sort_order', 'description'],
            },
        ),
        migrations.CreateModel(
            name='BedrockMaterialDescriptor',
            fields=[
                ('bedrock_material_descriptor_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gwells_bedrock_material_descriptor',
                'ordering': ['sort_order', 'description'],
            },
        ),
        migrations.CreateModel(
            name='LithologyColour',
            fields=[
                ('lithology_colour_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gwells_lithology_colour',
                'ordering': ['sort_order', 'description'],
            },
        ),
        migrations.CreateModel(
            name='LithologyDescription',
            fields=[
                ('lithology_description_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lithology_from', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='From')),
                ('lithology_to', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='To')),
                ('water_bearing_estimated_flow', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Water Bearing Estimated Flow')),
                ('lithology_observation', models.CharField(blank=True, max_length=250, verbose_name='Observations')),
            ],
            options={
                'db_table': 'gwells_lithology_description',
            },
        ),
        migrations.CreateModel(
            name='LithologyHardness',
            fields=[
                ('lithology_hardness_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gwells_lithology_hardness',
                'ordering': ['sort_order', 'description'],
            },
        ),
        migrations.CreateModel(
            name='LithologyMoisture',
            fields=[
                ('lithology_moisture_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gwells_lithology_moisture',
                'ordering': ['sort_order', 'description'],
            },
        ),
        migrations.CreateModel(
            name='LithologyStructure',
            fields=[
                ('lithology_structure_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gwells_lithology_structure',
                'ordering': ['sort_order', 'description'],
            },
        ),
        migrations.CreateModel(
            name='LithologyWeathering',
            fields=[
                ('lithology_weathering_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gwells_lithology_weathering',
                'ordering': ['sort_order', 'description'],
            },
        ),
        migrations.CreateModel(
            name='SurficialMaterial',
            fields=[
                ('surficial_material_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gwells_surficial_material',
                'ordering': ['sort_order', 'description'],
            },
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='ground_elevation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ground Elevation'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='orientation_vertical',
            field=models.BooleanField(choices=[(True, 'vertical'), (False, 'horizontal')], default=True, verbose_name='Well Orientation'),
        ),
        migrations.AlterField(
            model_name='ltsaowner',
            name='well',
            field=models.ForeignKey(blank=True, db_column='well_tag_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.Well'),
        ),
        migrations.AlterField(
            model_name='well',
            name='ground_elevation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ground Elevation'),
        ),
        migrations.AlterField(
            model_name='well',
            name='orientation_vertical',
            field=models.BooleanField(default=True, verbose_name='Well Orientation'),
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='activity_submission',
            field=models.ForeignKey(blank=True, db_column='filing_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.ActivitySubmission'),
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='bedrock_material',
            field=models.ForeignKey(blank=True, db_column='bedrock_material_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.BedrockMaterial', verbose_name='Bedrock Material'),
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='bedrock_material_descriptor',
            field=models.ForeignKey(blank=True, db_column='bedrock_material_descriptor_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.BedrockMaterialDescriptor', verbose_name='Descriptor'),
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='lithology_colour',
            field=models.ForeignKey(blank=True, db_column='lithology_colour_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LithologyColour', verbose_name='Colour'),
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='lithology_hardness',
            field=models.ForeignKey(blank=True, db_column='lithology_hardness_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LithologyHardness', verbose_name='Hardness'),
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='lithology_moisture',
            field=models.ForeignKey(blank=True, db_column='lithology_moisture_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LithologyMoisture', verbose_name='Moisture'),
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='lithology_structure',
            field=models.ForeignKey(blank=True, db_column='lithology_structure_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LithologyStructure', verbose_name='Structure'),
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='lithology_weathering',
            field=models.ForeignKey(blank=True, db_column='lithology_weathering_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LithologyWeathering', verbose_name='Weathering'),
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='surficial_material',
            field=models.ForeignKey(blank=True, db_column='surficial_material_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.SurficialMaterial', verbose_name='Surficial Material'),
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='well',
            field=models.ForeignKey(blank=True, db_column='well_tag_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.Well'),
        ),
    ]
