# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0006_auto_20170329_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField()),
            ],
            options={
                'db_table': 'gwells_land_district',
            },
        ),
        migrations.RenameField(
            model_name='well',
            old_name='address_line',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='well',
            name='finished_well_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_yield_unit_id',
            field=models.ForeignKey(blank=True, db_column='gwells_well_yield_unit_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellYieldUnit'),
        ),
        migrations.AddField(
            model_name='well',
            name='land_district_id',
            field=models.ForeignKey(blank=True, db_column='gwells_land_district_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LandDistrict'),
        ),
    ]
