# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-03 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0006_auto_20171103_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='utm_accuracy_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Location Accuracy Code'),
        ),
        migrations.AlterField(
            model_name='well',
            name='utm_easting',
            field=models.IntegerField(blank=True, null=True, verbose_name='UTM Easting'),
        ),
    ]
