# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0007_auto_20180404_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_gwells_admin',
            field=models.BooleanField(default=False),
        ),
    ]
