# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0007_auto_20170331_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellowner',
            old_name='address_line',
            new_name='street_address',
        ),
    ]
