# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-03 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0007_auto_20171103_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCGS_Numbers',
            fields=[
                ('who_created', models.CharField(max_length=30)),
                ('when_created', models.DateTimeField(blank=True, null=True)),
                ('who_updated', models.CharField(max_length=30, null=True)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('bcgs_id', models.BigIntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bcgs_number', models.CharField(max_length=20, verbose_name='BCGS Mapsheet Number')),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gwells_bcgs_numbers',
                'ordering': ['sort_order', 'bcgs_number'],
            },
        ),
        migrations.AddField(
            model_name='well',
            name='bcgs_id',
            field=models.ForeignKey(blank=True, db_column='bcgs_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.BCGS_Numbers', verbose_name='BCGS Mapsheet Number'),
        ),
    ]
