# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0008_auto_20171109_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productiondata',
            old_name='well',
            new_name='well_tag_number',
        ),
        migrations.RenameField(
            model_name='yieldestimationmethod',
            old_name='code',
            new_name='yield_estimated_method_code',
        ),
    ]
