# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 23:00
from __future__ import unicode_literals

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0008_auto_20170707_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysubmission',
            name='created',
        ),
        migrations.RemoveField(
            model_name='activitysubmission',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='ltsaowner',
            name='created',
        ),
        migrations.RemoveField(
            model_name='ltsaowner',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='well',
            name='created',
        ),
        migrations.RemoveField(
            model_name='well',
            name='modified',
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 53, 46, 180011)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedrockmaterial',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 54, 30, 909484)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedrockmaterial',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bedrockmaterial',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedrockmaterial',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedrockmaterialdescriptor',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 55, 2, 854678)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedrockmaterialdescriptor',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bedrockmaterialdescriptor',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedrockmaterialdescriptor',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driller',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 55, 21, 247517)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driller',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driller',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driller',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drillingcompany',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 55, 56, 321024)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drillingcompany',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drillingcompany',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drillingcompany',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drillingmethod',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 56, 13, 705763)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drillingmethod',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drillingmethod',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drillingmethod',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groundelevationmethod',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 56, 30, 66398)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groundelevationmethod',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groundelevationmethod',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groundelevationmethod',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intendedwateruse',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 56, 46, 156007)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intendedwateruse',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intendedwateruse',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intendedwateruse',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landdistrict',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 56, 59, 443336)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landdistrict',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landdistrict',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landdistrict',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lithologycolour',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 57, 14, 604852)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lithologycolour',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lithologycolour',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lithologycolour',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 57, 30, 349426)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lithologyhardness',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 57, 41, 269518)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lithologyhardness',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lithologyhardness',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lithologyhardness',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lithologymoisture',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 57, 55, 662957)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lithologymoisture',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lithologymoisture',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lithologymoisture',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lithologystructure',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 58, 14, 686859)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lithologystructure',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lithologystructure',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lithologystructure',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lithologyweathering',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 58, 28, 640255)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lithologyweathering',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lithologyweathering',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lithologyweathering',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ltsaowner',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 58, 45, 856976)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ltsaowner',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ltsaowner',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ltsaowner',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provincestate',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 58, 55, 200910)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provincestate',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provincestate',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provincestate',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surficialmaterial',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 59, 5, 328923)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surficialmaterial',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surficialmaterial',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surficialmaterial',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 59, 15, 641954)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellactivitytype',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 59, 30, 730463)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellactivitytype',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wellactivitytype',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellactivitytype',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellclass',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 59, 41, 51495)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellclass',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wellclass',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellclass',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellsubclass',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 16, 0, 8, 915281)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellsubclass',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wellsubclass',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellsubclass',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellyieldunit',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 16, 0, 23, 332723)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellyieldunit',
            name='when_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wellyieldunit',
            name='who_created',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellyieldunit',
            name='who_updated',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='drilling_method',
            field=models.ForeignKey(db_column='drilling_method_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.DrillingMethod', verbose_name='Drilling Method'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='lithologydescription',
            name='lithology_from',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='lithologydescription',
            name='lithology_to',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='To'),
        ),
    ]
