# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-03 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0008_auto_20171103_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillingcompany',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
