# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0009_auto_20170404_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landdistrict',
            name='sort_order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='provincestate',
            name='sort_order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='well',
            name='identification_plate_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='pid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wellyieldunit',
            name='sort_order',
            field=models.PositiveIntegerField(),
        ),
    ]
