# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-03 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0009_auto_20171103_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bcgs_numbers',
            options={'ordering': ['bcgs_number']},
        ),
        migrations.RemoveField(
            model_name='bcgs_numbers',
            name='sort_order',
        ),
    ]
