# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0010_auto_20171109_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondata',
            name='yield_estimation_units',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
