# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-06 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0010_auto_20171103_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeMethod',
            fields=[
                ('who_created', models.CharField(max_length=30)),
                ('when_created', models.DateTimeField(blank=True, null=True)),
                ('who_updated', models.CharField(max_length=30, null=True)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('intake_method_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gwells_intake_method',
                'ordering': ['sort_order', 'description'],
            },
        ),
        migrations.RemoveField(
            model_name='activitysubmission',
            name='screen_intake',
        ),
        migrations.RemoveField(
            model_name='well',
            name='bcgs_id',
        ),
        migrations.RemoveField(
            model_name='well',
            name='screen_intake',
        ),
        migrations.RemoveField(
            model_name='well',
            name='utm_accuracy_code',
        ),
        migrations.RemoveField(
            model_name='well',
            name='utm_easting',
        ),
        migrations.RemoveField(
            model_name='well',
            name='utm_northing',
        ),
        migrations.RemoveField(
            model_name='well',
            name='utm_zone_code',
        ),
        migrations.AlterField(
            model_name='drillingcompany',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='BCGS_Numbers',
        ),
        migrations.DeleteModel(
            name='ScreenIntake',
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='intake_method',
            field=models.ForeignKey(blank=True, db_column='intake_method_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.IntakeMethod', verbose_name='Intake'),
        ),
        migrations.AddField(
            model_name='well',
            name='intake_method',
            field=models.ForeignKey(blank=True, db_column='intake_method_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.IntakeMethod', verbose_name='Intake'),
        ),
    ]
