# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0010_auto_20170405_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='well',
            old_name='land_district_id',
            new_name='land_district',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='well_drilled_depth',
            new_name='total_depth_drilled',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='well_owner_id',
            new_name='well_owner',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='well_yield_unit_id',
            new_name='well_yield_unit',
        ),
        migrations.RenameField(
            model_name='wellowner',
            old_name='province_state_id',
            new_name='province_state',
        ),
    ]
