# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0011_productiondata_yield_estimation_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casing',
            old_name='well',
            new_name='well_tag_number',
        ),
        migrations.RenameField(
            model_name='casingmaterial',
            old_name='code',
            new_name='casing_material_code',
        ),
        migrations.AlterField(
            model_name='casing',
            name='drive_shoe',
            field=models.NullBooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Drive Shoe'),
        ),
    ]
