# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-06 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0011_auto_20171106_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intakemethod',
            old_name='code',
            new_name='screen_intake_code',
        ),
    ]
