# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-06 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0012_auto_20171106_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakemethod',
            name='status_flag',
            field=models.BooleanField(choices=[(False, 'N'), (True, 'Y')], default=False),
        ),
    ]
