# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 23:42
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0012_auto_20171109_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casing',
            name='casing_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='From'),
        ),
    ]
