# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 21:41
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0012_auto_20170724_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casing',
            name='wall_thickness',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Wall Thickness'),
        ),
    ]
