# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0013_auto_20170524_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('is_user_selectable', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gwells_well_activity_type',
            },
        ),
        migrations.RenameField(
            model_name='wellactivity',
            old_name='district_lot',
            new_name='legal_district_lot',
        ),
        migrations.RenameField(
            model_name='wellactivity',
            old_name='lot',
            new_name='legal_lot',
        ),
        migrations.RenameField(
            model_name='wellactivity',
            old_name='pid',
            new_name='legal_pid',
        ),
        migrations.RenameField(
            model_name='wellactivity',
            old_name='plan',
            new_name='legal_plan',
        ),
        migrations.RemoveField(
            model_name='wellactivity',
            name='land_district',
        ),
        migrations.AddField(
            model_name='wellactivity',
            name='legal_block',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='wellactivity',
            name='legal_land_district',
            field=models.ForeignKey(blank=True, db_column='gwells_legal_land_district_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LandDistrict'),
        ),
        migrations.AddField(
            model_name='wellactivity',
            name='legal_range',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='wellactivity',
            name='legal_section',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='wellactivity',
            name='legal_township',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='wellactivity',
            name='well_location_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='wellowner',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='wellowner',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Owner Name'),
        ),
        migrations.AlterField(
            model_name='wellowner',
            name='mailing_address',
            field=models.CharField(max_length=100, verbose_name='Mailing Address'),
        ),
        migrations.AlterField(
            model_name='wellowner',
            name='province_state',
            field=models.ForeignKey(blank=True, db_column='gwells_province_state_id', on_delete=django.db.models.deletion.CASCADE, to='gwells.ProvinceState', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='wellactivity',
            name='well_activity_type',
            field=models.ForeignKey(blank=True, db_column='gwells_well_activity_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellActivityType', verbose_name='Type of Work'),
        ),
    ]
