# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-25 23:02
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0014_auto_20170725_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='drilling_method',
            field=models.ForeignKey(blank=True, db_column='drilling_method_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.DrillingMethod', verbose_name='Drilling Method'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='surface_seal_thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Surface Seal Thickness'),
        ),
    ]
