# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-06 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0014_auto_20171106_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitysubmission',
            old_name='intake_method',
            new_name='screen_intake_method',
        ),
    ]
