# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0014_auto_20170525_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOfWell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gwells_class_of_well',
            },
        ),
        migrations.CreateModel(
            name='Driller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gwells_driller',
            },
        ),
        migrations.CreateModel(
            name='DrillingCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gwells_drilling_company',
            },
        ),
        migrations.CreateModel(
            name='SubclassOfWell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
                ('class_of_well', models.ForeignKey(blank=True, db_column='gwells_class_of_well_id', on_delete=django.db.models.deletion.CASCADE, to='gwells.ClassOfWell')),
            ],
            options={
                'db_table': 'gwells_subclass_of_well',
            },
        ),
        migrations.CreateModel(
            name='WellUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gwells_well_use',
            },
        ),
        migrations.RenameField(
            model_name='wellactivitytype',
            old_name='is_user_selectable',
            new_name='is_hidden',
        ),
        migrations.AddField(
            model_name='wellactivity',
            name='activity_end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellactivity',
            name='activity_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellactivity',
            name='consultant_company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wellactivity',
            name='consultant_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wellactivity',
            name='worker_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name of Person Who Did the Work'),
        ),
        migrations.AlterField(
            model_name='wellactivity',
            name='legal_block',
            field=models.CharField(blank=True, max_length=10, verbose_name='Block'),
        ),
        migrations.AlterField(
            model_name='wellactivity',
            name='legal_district_lot',
            field=models.CharField(blank=True, max_length=20, verbose_name='District Lot'),
        ),
        migrations.AlterField(
            model_name='wellactivity',
            name='legal_land_district',
            field=models.ForeignKey(blank=True, db_column='gwells_legal_land_district_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LandDistrict', verbose_name='PID'),
        ),
        migrations.AlterField(
            model_name='wellactivity',
            name='legal_lot',
            field=models.CharField(blank=True, max_length=10, verbose_name='Lot'),
        ),
        migrations.AlterField(
            model_name='wellactivity',
            name='legal_plan',
            field=models.CharField(blank=True, max_length=20, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='wellactivity',
            name='legal_range',
            field=models.CharField(blank=True, max_length=10, verbose_name='Range'),
        ),
        migrations.AlterField(
            model_name='wellactivity',
            name='legal_section',
            field=models.CharField(blank=True, max_length=10, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='wellactivity',
            name='legal_township',
            field=models.CharField(blank=True, max_length=20, verbose_name='Township'),
        ),
        migrations.AlterField(
            model_name='wellactivity',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='wellowner',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='driller',
            name='drilling_company',
            field=models.ForeignKey(db_column='gwells_drilling_company_id', on_delete=django.db.models.deletion.CASCADE, to='gwells.DrillingCompany', verbose_name='Drilling Company'),
        ),
        migrations.AddField(
            model_name='wellactivity',
            name='class_of_well',
            field=models.ForeignKey(db_column='gwells_class_of_well_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='gwells.ClassOfWell', verbose_name='Class of Well'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellactivity',
            name='driller',
            field=models.ForeignKey(db_column='gwells_driller_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='gwells.Driller', verbose_name='Person Responsible for Drilling'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellactivity',
            name='subclass_of_well',
            field=models.ForeignKey(blank=True, db_column='gwells_subclass_of_well_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.SubclassOfWell', verbose_name='Subclass of Well'),
        ),
        migrations.AddField(
            model_name='wellactivity',
            name='well_use',
            field=models.ForeignKey(blank=True, db_column='gwells_well_use_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellUse', verbose_name='Water Supply Well Intended Water Use'),
        ),
    ]
