# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0015_auto_20171109_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casing',
            name='casing_type',
            field=models.ForeignKey(db_column='casing_type_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.CasingType', verbose_name='Casing Type'),
        ),
    ]
