# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-06 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0015_auto_20171106_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screentype',
            old_name='code',
            new_name='screen_type_code',
        ),
    ]
