# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0015_auto_20170525_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellactivity',
            old_name='worker_name',
            new_name='driller_name',
        ),
        migrations.RemoveField(
            model_name='wellactivity',
            name='driller',
        ),
        migrations.AddField(
            model_name='wellactivity',
            name='driller_responsible',
            field=models.ForeignKey(db_column='gwells_driller_responsible_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='gwells.Driller', verbose_name='Person Responsible for Drilling'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wellactivity',
            name='activity_end_date',
            field=models.DateField(verbose_name='End Date of Work'),
        ),
        migrations.AlterField(
            model_name='wellactivity',
            name='activity_start_date',
            field=models.DateField(verbose_name='Start Date of Work'),
        ),
        migrations.AlterField(
            model_name='wellactivity',
            name='consultant_company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Consultant Company'),
        ),
        migrations.AlterField(
            model_name='wellactivity',
            name='consultant_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Consultant Name'),
        ),
    ]
