# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-07 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0016_auto_20171106_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenmaterial',
            old_name='code',
            new_name='screen_material_code',
        ),
    ]
