# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0016_auto_20170525_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellactivity',
            name='well_activity_type',
            field=models.ForeignKey(db_column='gwells_well_activity_type_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellActivityType', verbose_name='Type of Work'),
            preserve_default=False,
        ),
    ]
