# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0016_auto_20170726_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitysubmission',
            old_name='backfill_depth',
            new_name='backfill_above_surface_seal_depth',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='backfill_depth',
            new_name='backfill_above_surface_seal_depth',
        ),
    ]
