# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0017_auto_20170526_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classofwell',
            options={'ordering': ['sort_order', 'description']},
        ),
        migrations.AlterModelOptions(
            name='drillingcompany',
            options={'verbose_name_plural': 'Drilling Companies'},
        ),
        migrations.AlterModelOptions(
            name='landdistrict',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='provincestate',
            options={'ordering': ['sort_order', 'description']},
        ),
        migrations.AlterModelOptions(
            name='subclassofwell',
            options={'ordering': ['sort_order', 'description']},
        ),
        migrations.AlterModelOptions(
            name='wellactivitytype',
            options={'ordering': ['sort_order', 'description']},
        ),
        migrations.AlterModelOptions(
            name='welluse',
            options={'ordering': ['sort_order', 'description']},
        ),
        migrations.AlterModelOptions(
            name='wellyieldunit',
            options={'ordering': ['sort_order', 'description']},
        ),
        migrations.AlterField(
            model_name='wellactivity',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Town/City'),
        ),
        migrations.AlterField(
            model_name='wellactivity',
            name='legal_land_district',
            field=models.ForeignKey(blank=True, db_column='gwells_legal_land_district_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LandDistrict', verbose_name='Land District'),
        ),
        migrations.AlterField(
            model_name='wellactivity',
            name='legal_pid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='PID'),
        ),
        migrations.AlterField(
            model_name='wellowner',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Town/City'),
        ),
        migrations.AlterModelTable(
            name='wellactivity',
            table='gwells_well_activity',
        ),
    ]
