# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-07 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0017_auto_20171107_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenopening',
            old_name='code',
            new_name='screen_opening_code',
        ),
    ]
