# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 22:30
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0017_auto_20170727_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinerMaterial',
            fields=[
                ('who_created', models.CharField(max_length=30)),
                ('when_created', models.DateTimeField(blank=True, null=True)),
                ('who_updated', models.CharField(max_length=30)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('liner_material_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gwells_liner_material',
                'ordering': ['sort_order', 'description'],
            },
        ),
        migrations.CreateModel(
            name='LinerPerforation',
            fields=[
                ('who_created', models.CharField(max_length=30)),
                ('when_created', models.DateTimeField(blank=True, null=True)),
                ('who_updated', models.CharField(max_length=30)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('liner_perforation_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('liner_perforation_from', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Perforated From')),
                ('liner_perforation_to', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Perforated To')),
            ],
            options={
                'db_table': 'gwells_liner_perforation',
            },
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='liner_diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Liner Diameter'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='liner_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Liner From'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='liner_thickness',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Liner Thickness'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='liner_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Liner To'),
        ),
        migrations.AddField(
            model_name='well',
            name='liner_diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Liner Diameter'),
        ),
        migrations.AddField(
            model_name='well',
            name='liner_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Liner From'),
        ),
        migrations.AddField(
            model_name='well',
            name='liner_thickness',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Liner Thickness'),
        ),
        migrations.AddField(
            model_name='well',
            name='liner_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Liner To'),
        ),
        migrations.AddField(
            model_name='linerperforation',
            name='activity_submission',
            field=models.ForeignKey(blank=True, db_column='filing_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.ActivitySubmission'),
        ),
        migrations.AddField(
            model_name='linerperforation',
            name='well',
            field=models.ForeignKey(blank=True, db_column='well_tag_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.Well'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='liner_material',
            field=models.ForeignKey(blank=True, db_column='liner_material_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LinerMaterial', verbose_name='Liner Material'),
        ),
        migrations.AddField(
            model_name='well',
            name='liner_material',
            field=models.ForeignKey(blank=True, db_column='liner_material_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LinerMaterial', verbose_name='Liner Material'),
        ),
    ]
