# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0018_well_backfill_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='well',
            old_name='backfill_above_surface_seal_depth',
            new_name='backfill_depth',
        ),
        migrations.RemoveField(
            model_name='well',
            name='backfill_above_surface_seal',
        ),
    ]
