# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0019_auto_20170530_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysubmission',
            name='well',
        ),
    ]
