# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0019_auto_20170728_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='identification_plate_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Identification Plate Number'),
        ),
    ]
