# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-07 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0019_auto_20171107_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCGS_Numbers',
            fields=[
                ('who_created', models.CharField(max_length=30)),
                ('when_created', models.DateTimeField(blank=True, null=True)),
                ('who_updated', models.CharField(max_length=30, null=True)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('bcgs_id', models.BigIntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bcgs_number', models.CharField(max_length=20, verbose_name='BCGS Mapsheet Number')),
            ],
            options={
                'ordering': ['bcgs_number'],
                'db_table': 'gwells_bcgs_numbers',
            },
        ),
        migrations.CreateModel(
            name='ScreenIntake',
            fields=[
                ('who_created', models.CharField(max_length=30)),
                ('when_created', models.DateTimeField(blank=True, null=True)),
                ('who_updated', models.CharField(max_length=30, null=True)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('screen_intake_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['sort_order', 'description'],
                'db_table': 'gwells_screen_intake',
            },
        ),
        migrations.RenameField(
            model_name='screenbottom',
            old_name='screen_bottom_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='screenmaterial',
            old_name='screen_material_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='screenopening',
            old_name='screen_opening_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='screentype',
            old_name='screen_type_code',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='activitysubmission',
            name='screen_intake_method',
        ),
        migrations.RemoveField(
            model_name='well',
            name='screen_intake_method',
        ),
        migrations.AddField(
            model_name='well',
            name='utm_accuracy_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Location Accuracy Code'),
        ),
        migrations.AddField(
            model_name='well',
            name='utm_easting',
            field=models.IntegerField(blank=True, null=True, verbose_name='UTM Easting'),
        ),
        migrations.AddField(
            model_name='well',
            name='utm_northing',
            field=models.IntegerField(blank=True, null=True, verbose_name='UTM Northing'),
        ),
        migrations.AddField(
            model_name='well',
            name='utm_zone_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='drillingcompany',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='ScreenIntakeMethod',
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='screen_intake',
            field=models.ForeignKey(blank=True, db_column='screen_intake_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.ScreenIntake', verbose_name='Intake'),
        ),
        migrations.AddField(
            model_name='well',
            name='bcgs_id',
            field=models.ForeignKey(blank=True, db_column='bcgs_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.BCGS_Numbers', verbose_name='BCGS Mapsheet Number'),
        ),
        migrations.AddField(
            model_name='well',
            name='screen_intake',
            field=models.ForeignKey(blank=True, db_column='screen_intake_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.ScreenIntake', verbose_name='Intake'),
        ),
    ]
