# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0019_auto_20171113_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='other_drilling_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Specify Other Drilling Method'),
        ),
    ]
