# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0020_remove_activitysubmission_well'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysubmission',
            name='id',
        ),
        migrations.RemoveField(
            model_name='driller',
            name='id',
        ),
        migrations.RemoveField(
            model_name='drillingcompany',
            name='id',
        ),
        migrations.RemoveField(
            model_name='intendedwateruse',
            name='id',
        ),
        migrations.RemoveField(
            model_name='landdistrict',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ltsaowner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='provincestate',
            name='id',
        ),
        migrations.RemoveField(
            model_name='well',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wellactivitytype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wellclass',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wellsubclass',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wellyieldunit',
            name='id',
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='activity_submission_guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='filing_number',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driller',
            name='driller_guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='drillingcompany',
            name='drilling_company_guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='intendedwateruse',
            name='intended_water_use_guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='landdistrict',
            name='land_district_guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='ltsaowner',
            name='lsts_owner_guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='provincestate',
            name='province_state_guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='well',
            name='well_guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='wellactivitytype',
            name='well_activity_type_guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='wellclass',
            name='well_class_guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='wellsubclass',
            name='well_subclass_guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='wellyieldunit',
            name='well_yield_unit_guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='well',
            field=models.ForeignKey(blank=True, db_column='well_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.Well'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='driller_responsible',
            field=models.ForeignKey(db_column='driller_responsible_guid', on_delete=django.db.models.deletion.CASCADE, to='gwells.Driller', verbose_name='Person Responsible for Drilling'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='intended_water_use',
            field=models.ForeignKey(blank=True, db_column='intended_water_use_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.IntendedWaterUse', verbose_name='Water Supply Well Intended Water Use'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='legal_land_district',
            field=models.ForeignKey(blank=True, db_column='legal_land_district_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LandDistrict', verbose_name='Land District'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='owner_province_state',
            field=models.ForeignKey(blank=True, db_column='province_state_guid', on_delete=django.db.models.deletion.CASCADE, to='gwells.ProvinceState', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='well_activity_type',
            field=models.ForeignKey(db_column='well_activity_type_guid', on_delete=django.db.models.deletion.CASCADE, to='gwells.WellActivityType', verbose_name='Type of Work'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='well_class',
            field=models.ForeignKey(db_column='well_class_guid', on_delete=django.db.models.deletion.CASCADE, to='gwells.WellClass', verbose_name='Well Class'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='well_subclass',
            field=models.ForeignKey(blank=True, db_column='well_subclass_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellSubclass', verbose_name='Well Subclass'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='well_yield_unit',
            field=models.ForeignKey(blank=True, db_column='well_yield_unit_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellYieldUnit'),
        ),
        migrations.AlterField(
            model_name='driller',
            name='drilling_company',
            field=models.ForeignKey(db_column='drilling_company_guid', on_delete=django.db.models.deletion.CASCADE, to='gwells.DrillingCompany', verbose_name='Drilling Company'),
        ),
        migrations.AlterField(
            model_name='ltsaowner',
            name='province_state',
            field=models.ForeignKey(blank=True, db_column='province_state_guid', on_delete=django.db.models.deletion.CASCADE, to='gwells.ProvinceState', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='ltsaowner',
            name='well',
            field=models.ForeignKey(blank=True, db_column='well_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.Well'),
        ),
        migrations.AlterField(
            model_name='well',
            name='intended_water_use',
            field=models.ForeignKey(blank=True, db_column='intended_water_use_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.IntendedWaterUse', verbose_name='Water Supply Well Intended Water Use'),
        ),
        migrations.AlterField(
            model_name='well',
            name='legal_land_district',
            field=models.ForeignKey(blank=True, db_column='legal_land_district_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LandDistrict', verbose_name='Land District'),
        ),
        migrations.AlterField(
            model_name='well',
            name='owner_province_state',
            field=models.ForeignKey(blank=True, db_column='province_state_guid', on_delete=django.db.models.deletion.CASCADE, to='gwells.ProvinceState', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_class',
            field=models.ForeignKey(db_column='well_class_guid', on_delete=django.db.models.deletion.CASCADE, to='gwells.WellClass', verbose_name='Well Class'),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_subclass',
            field=models.ForeignKey(blank=True, db_column='well_subclass_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellSubclass', verbose_name='Well Subclass'),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_yield_unit',
            field=models.ForeignKey(blank=True, db_column='well_yield_unit_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellYieldUnit'),
        ),
        migrations.AlterField(
            model_name='wellsubclass',
            name='well_class',
            field=models.ForeignKey(blank=True, db_column='well_class_guid', on_delete=django.db.models.deletion.CASCADE, to='gwells.WellClass'),
        ),
    ]
