# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0022_auto_20171113_2050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peforation',
            new_name='Perforation',
        ),
    ]
