# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0022_auto_20170802_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='where_plate_attached',
            field=models.CharField(blank=True, max_length=500, verbose_name='Where Identification Plate Is Attached'),
        ),
        migrations.AddField(
            model_name='well',
            name='where_plate_attached',
            field=models.CharField(blank=True, max_length=500, verbose_name='Where Identification Plate Is Attached'),
        ),
    ]
