# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0022_auto_20170531_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='driller_responsible',
            field=models.ForeignKey(db_column='driller_responsible_guid', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='gwells.Driller', verbose_name='Person Responsible for Drilling'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='intended_water_use',
            field=models.ForeignKey(blank=True, db_column='intended_water_use_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.IntendedWaterUse', verbose_name='Water Supply Well Intended Water Use'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='legal_land_district',
            field=models.ForeignKey(blank=True, db_column='legal_land_district_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LandDistrict', verbose_name='Land District'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='owner_province_state',
            field=models.ForeignKey(blank=True, db_column='province_state_guid', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='gwells.ProvinceState', verbose_name='Province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='well',
            field=models.ForeignKey(blank=True, db_column='well_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.Well'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='well_activity_type',
            field=models.ForeignKey(db_column='well_activity_type_guid', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellActivityType', verbose_name='Type of Work'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='well_class',
            field=models.ForeignKey(db_column='well_class_guid', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellClass', verbose_name='Well Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='well_subclass',
            field=models.ForeignKey(blank=True, db_column='well_subclass_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellSubclass', verbose_name='Well Subclass'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='well_yield_unit',
            field=models.ForeignKey(blank=True, db_column='well_yield_unit_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellYieldUnit'),
        ),
        migrations.AddField(
            model_name='driller',
            name='drilling_company',
            field=models.ForeignKey(db_column='drilling_company_guid', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='gwells.DrillingCompany', verbose_name='Drilling Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ltsaowner',
            name='province_state',
            field=models.ForeignKey(blank=True, db_column='province_state_guid', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='gwells.ProvinceState', verbose_name='Province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ltsaowner',
            name='well',
            field=models.ForeignKey(blank=True, db_column='well_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.Well'),
        ),
        migrations.AddField(
            model_name='well',
            name='intended_water_use',
            field=models.ForeignKey(blank=True, db_column='intended_water_use_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.IntendedWaterUse', verbose_name='Water Supply Well Intended Water Use'),
        ),
        migrations.AddField(
            model_name='well',
            name='legal_land_district',
            field=models.ForeignKey(blank=True, db_column='legal_land_district_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LandDistrict', verbose_name='Land District'),
        ),
        migrations.AddField(
            model_name='well',
            name='owner_province_state',
            field=models.ForeignKey(blank=True, db_column='province_state_guid', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='gwells.ProvinceState', verbose_name='Province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well',
            name='well_class',
            field=models.ForeignKey(db_column='well_class_guid', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellClass', verbose_name='Well Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well',
            name='well_subclass',
            field=models.ForeignKey(blank=True, db_column='well_subclass_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellSubclass', verbose_name='Well Subclass'),
        ),
        migrations.AddField(
            model_name='well',
            name='well_yield_unit',
            field=models.ForeignKey(blank=True, db_column='well_yield_unit_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellYieldUnit'),
        ),
        migrations.AddField(
            model_name='wellsubclass',
            name='well_class',
            field=models.ForeignKey(blank=True, db_column='well_class_guid', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellClass'),
            preserve_default=False,
        ),
    ]
