# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0023_auto_20170531_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysubmission',
            name='filing_number',
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
