# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0023_auto_20171113_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='well_identification_plate_attached',
        ),
    ]
