# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0024_auto_20170531_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysubmission',
            name='id',
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='filing_number',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
