# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0025_well_where_identification_plate_attached'),
    ]

    operations = [
        migrations.RenameField(
            model_name='well',
            old_name='licenced_status_guid',
            new_name='licenced_status',
        ),
    ]
