# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0026_auto_20170816_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityCharacteristic',
            fields=[
                ('who_created', models.CharField(max_length=30)),
                ('when_created', models.DateTimeField(blank=True, null=True)),
                ('who_updated', models.CharField(max_length=30)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('water_quality_characteristic_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gwells_water_quality_characteristic',
                'ordering': ['sort_order', 'description'],
            },
        ),
        migrations.CreateModel(
            name='WellWaterQuality',
            fields=[
                ('well_water_quality_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_submission', models.ForeignKey(blank=True, db_column='filing_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.ActivitySubmission')),
                ('water_quality_characteristic', models.ForeignKey(db_column='water_quality_characteristic_guid', on_delete=django.db.models.deletion.CASCADE, to='gwells.WaterQualityCharacteristic')),
                ('well', models.ForeignKey(blank=True, db_column='well_tag_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.Well')),
            ],
            options={
                'db_table': 'gwells_well_water_quality',
            },
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='water_quality_characteristics',
            field=models.ManyToManyField(through='gwells.WellWaterQuality', to='gwells.WaterQualityCharacteristic'),
        ),
        migrations.AddField(
            model_name='well',
            name='water_quality_characteristics',
            field=models.ManyToManyField(through='gwells.WellWaterQuality', to='gwells.WaterQualityCharacteristic'),
        ),
    ]
