# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-15 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0026_auto_20171114_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productiondata',
            name='well_tag_number',
        ),
        migrations.AddField(
            model_name='productiondata',
            name='well_id',
            field=models.ForeignKey(blank=True, db_column='well_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.Well'),
        ),
    ]
