# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0027_auto_20170817_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='water_quality_colour',
            field=models.CharField(blank=True, max_length=60, verbose_name='Water Quality Colour'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='water_quality_odour',
            field=models.CharField(blank=True, max_length=60, verbose_name='Water Quality Odour'),
        ),
        migrations.AddField(
            model_name='well',
            name='water_quality_colour',
            field=models.CharField(blank=True, max_length=60, verbose_name='Water Quality Colour'),
        ),
        migrations.AddField(
            model_name='well',
            name='water_quality_odour',
            field=models.CharField(blank=True, max_length=60, verbose_name='Water Quality Odour'),
        ),
    ]
