# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0028_auto_20170817_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellwaterquality',
            name='activity_submission',
        ),
        migrations.RemoveField(
            model_name='wellwaterquality',
            name='water_quality_characteristic',
        ),
        migrations.RemoveField(
            model_name='wellwaterquality',
            name='well',
        ),
        migrations.RemoveField(
            model_name='activitysubmission',
            name='water_quality_characteristics',
        ),
        migrations.RemoveField(
            model_name='well',
            name='water_quality_characteristics',
        ),
        migrations.DeleteModel(
            name='WellWaterQuality',
        ),
    ]
