# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-15 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0028_auto_20171115_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondata',
            name='well_guid',
            field=models.ForeignKey(blank=True, db_column='well_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.Well', verbose_name='Well GUID'),
        ),
    ]
