# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0029_auto_20170817_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='water_quality_characteristics',
            field=models.ManyToManyField(db_table='gwells_activity_submission_water_quality', to='gwells.WaterQualityCharacteristic'),
        ),
        migrations.AddField(
            model_name='well',
            name='water_quality_characteristics',
            field=models.ManyToManyField(db_table='gwells_well_water_quality', to='gwells.WaterQualityCharacteristic'),
        ),
    ]
