# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0030_auto_20170817_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='water_quality_characteristics',
            field=models.ManyToManyField(blank=True, db_table='gwells_activity_submission_water_quality', to='gwells.WaterQualityCharacteristic', verbose_name='Obvious Water Quality Characteristics'),
        ),
        migrations.AlterField(
            model_name='well',
            name='water_quality_characteristics',
            field=models.ManyToManyField(blank=True, db_table='gwells_well_water_quality', to='gwells.WaterQualityCharacteristic', verbose_name='Obvious Water Quality Characteristics'),
        ),
    ]
