# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-20 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0031_auto_20171115_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='AquiferWell',
            fields=[
                ('who_created', models.CharField(max_length=30)),
                ('when_created', models.DateTimeField(blank=True, null=True)),
                ('who_updated', models.CharField(max_length=30, null=True)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('aquifer_well_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aquifer_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Aquifer Number')),
                ('well_tag_number', models.ForeignKey(db_column='well_tag_number', on_delete=django.db.models.deletion.CASCADE, to='gwells.Well')),
            ],
            options={
                'db_table': 'gwells_aquifer_well',
            },
        ),
    ]
