# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-20 23:50
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0032_aquiferwell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productiondata',
            name='yield_estimation_units',
        ),
        migrations.AddField(
            model_name='productiondata',
            name='well_yield_unit',
            field=models.ForeignKey(blank=True, db_column='well_yield_unit_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellYieldUnit'),
        ),
        migrations.AlterField(
            model_name='well',
            name='development_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Development Total Duration (hours)'),
        ),
        migrations.AlterField(
            model_name='well',
            name='identification_plate_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Well Identification Plate Number'),
        ),
    ]
