# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0032_auto_20170818_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='alternative_specs_submitted',
            field=models.BooleanField(default=False, verbose_name='Alternative specs submitted (if required)'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='comments',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='well',
            name='alternative_specs_submitted',
            field=models.BooleanField(default=False, verbose_name='Alternative specs submitted (if required)'),
        ),
        migrations.AddField(
            model_name='well',
            name='comments',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='well_disinfected',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Well Disinfected?'),
        ),
        migrations.AlterField(
            model_name='casing',
            name='drive_shoe',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Drive Shoe'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='hydro_fracturing_performed',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Hydro-fracturing Performed?'),
        ),
        migrations.AlterField(
            model_name='well',
            name='orientation_vertical',
            field=models.BooleanField(choices=[(True, 'vertical'), (False, 'horizontal')], default=True, verbose_name='Well Orientation'),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_disinfected',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Well Disinfected?'),
        ),
    ]
