# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0033_auto_20170818_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='comments',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='well',
            name='comments',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
