# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0034_auto_20170821_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lithologydescription',
            name='lithology_weathering',
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='secondary_surficial_material',
            field=models.ForeignKey(blank=True, db_column='secondary_surficial_material_guid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_surficial_material_set', to='gwells.SurficialMaterial', verbose_name='Secondary Surficial Material'),
        ),
        migrations.AlterField(
            model_name='lithologydescription',
            name='lithology_structure',
            field=models.ForeignKey(blank=True, db_column='lithology_structure_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LithologyStructure', verbose_name='Bedding'),
        ),
        migrations.AlterField(
            model_name='lithologydescription',
            name='surficial_material',
            field=models.ForeignKey(blank=True, db_column='surficial_material_guid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surficial_material_set', to='gwells.SurficialMaterial', verbose_name='Surficial Material'),
        ),
        migrations.DeleteModel(
            name='LithologyWeathering',
        ),
    ]
