# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-12 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0035_auto_20170830_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOfWell',
            fields=[
                ('who_created', models.CharField(max_length=30)),
                ('when_created', models.DateTimeField(blank=True, null=True)),
                ('who_updated', models.CharField(max_length=30)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('status_of_well_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gwells_status_of_well',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='well',
            name='status_of_well',
            field=models.ForeignKey(blank=True, db_column='status_of_well_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.StatusOfWell', verbose_name='Status of Well'),
        ),
    ]
