# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-12 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0036_auto_20171012_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensedStatus',
            fields=[
                ('who_created', models.CharField(max_length=30)),
                ('when_created', models.DateTimeField(blank=True, null=True)),
                ('who_updated', models.CharField(max_length=30)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('well_licensed_status_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['sort_order', 'code'],
                'db_table': 'gwells_licensed_status',
            },
        ),
        migrations.AlterField(
            model_name='statusofwell',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='well',
            name='licensed_status',
            field=models.ForeignKey(blank=True, db_column='licensed_status_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LicensedStatus', verbose_name='Licensed Status'),
        ),
    ]
