# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-23 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0036_auto_20171013_2104'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='provincestate',
            table='gwells.province_state',
        ),
    ]
