# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-22 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0036_auto_20171122_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='where_plate_attached',
            field=models.CharField(blank=True, max_length=500, verbose_name='Well Identification Plate Is Attached'),
        ),
    ]
