# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-16 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0036_auto_20171013_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='well_cap_type',
            field=models.CharField(blank=True, max_length=40, verbose_name='Well Cap'),
        ),
    ]
