# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-22 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0037_auto_20171122_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='where_identification_plate_attached',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Well Identification Plate Is Attached'),
        ),
    ]
