# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-16 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0037_auto_20171016_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitysubmission',
            old_name='final_casing_stick_up',
            new_name='final_stick_up',
        ),
    ]
