# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-22 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0038_auto_20171122_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitysubmission',
            old_name='where_plate_attached',
            new_name='well_plate_attached',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='where_identification_plate_attached',
            new_name='well_identification_plate_attached',
        ),
    ]
