# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-16 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0038_auto_20171016_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitysubmission',
            old_name='artestian_flow',
            new_name='artesian_flow',
        ),
        migrations.RenameField(
            model_name='activitysubmission',
            old_name='artestian_pressure',
            new_name='artesian_pressure',
        ),
        migrations.RenameField(
            model_name='activitysubmission',
            old_name='orientation_vertical',
            new_name='orientation',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='artestian_flow',
            new_name='artesian_flow',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='artestian_pressure',
            new_name='artesian_pressure',
        ),
    ]
