# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-16 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0039_auto_20171016_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='water_suplly_system_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Water Supply System Name'),
        ),
    ]
