# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0039_auto_20171023_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='water_quality_characteristics',
            field=models.ManyToManyField(blank=True, db_table='activity_submission_water_quality', to='gwells.WaterQualityCharacteristic', verbose_name='Obvious Water Quality Characteristics'),
        ),
        migrations.AlterField(
            model_name='well',
            name='water_quality_characteristics',
            field=models.ManyToManyField(blank=True, db_table='well_water_quality', to='gwells.WaterQualityCharacteristic', verbose_name='Obvious Water Quality Characteristics'),
        ),
    ]
