# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-22 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0039_auto_20171122_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='ground_elevation_method',
            field=models.ForeignKey(blank=True, db_column='ground_elevation_method_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.GroundElevationMethod', verbose_name='Elevation Determined By'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='static_water_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Static Water Level (BTOC)'),
        ),
    ]
