# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-16 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0040_activitysubmission_water_suplly_system_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitysubmission',
            old_name='water_suplly_system_name',
            new_name='water_supply_system_name',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='final_casing_stick_up',
            new_name='final_stick_up',
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='water_supply_system_well_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Water Supply System Well Name'),
        ),
    ]
