# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-16 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0041_auto_20171016_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='where_plate_attached',
        ),
        migrations.AddField(
            model_name='well',
            name='well_identification_plate_attached',
            field=models.CharField(blank=True, max_length=500, verbose_name='Well Identification Plate Is Attached'),
        ),
    ]
