# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-23 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0041_auto_20171122_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='screen_bottom',
            field=models.ForeignKey(blank=True, db_column='screen_bottom_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.ScreenBottom', verbose_name='Bottom'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='screen_material',
            field=models.ForeignKey(blank=True, db_column='screen_material_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.ScreenMaterial', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='screen_opening',
            field=models.ForeignKey(blank=True, db_column='screen_opening_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.ScreenOpening', verbose_name='Opening'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='screen_type',
            field=models.ForeignKey(blank=True, db_column='screen_type_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.ScreenType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='well',
            name='screen_bottom',
            field=models.ForeignKey(blank=True, db_column='screen_bottom_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.ScreenBottom', verbose_name='Bottom'),
        ),
        migrations.AlterField(
            model_name='well',
            name='screen_intake_method',
            field=models.ForeignKey(blank=True, db_column='screen_intake_method_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.ScreenIntakeMethod', verbose_name='Intake Method'),
        ),
        migrations.AlterField(
            model_name='well',
            name='screen_material',
            field=models.ForeignKey(blank=True, db_column='screen_material_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.ScreenMaterial', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='well',
            name='screen_opening',
            field=models.ForeignKey(blank=True, db_column='screen_opening_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.ScreenOpening', verbose_name='Opening'),
        ),
        migrations.AlterField(
            model_name='well',
            name='screen_type',
            field=models.ForeignKey(blank=True, db_column='screen_type_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.ScreenType', verbose_name='Type'),
        ),
    ]
