# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-28 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0043_auto_20171123_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casing',
            options={'ordering': ['casing_from', 'casing_to']},
        ),
        migrations.AlterModelOptions(
            name='lithologydescription',
            options={'ordering': ['lithology_from']},
        ),
        migrations.AlterModelOptions(
            name='perforation',
            options={'ordering': ['liner_from', 'liner_to', 'liner_perforation_from', 'liner_perforation_to', 'perforation_guid']},
        ),
        migrations.AlterModelOptions(
            name='screen',
            options={'ordering': ['screen_from', 'screen_to']},
        ),
        migrations.RenameField(
            model_name='lithologydescription',
            old_name='well',
            new_name='well_tag_number',
        ),
        migrations.RemoveField(
            model_name='well',
            name='legal_land_district',
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='lithology_raw_data',
            field=models.CharField(blank=True, max_length=250, verbose_name='Raw Data'),
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='water_bearing_estimated_flow_units',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='well',
            name='land_district',
            field=models.ForeignKey(blank=True, db_column='land_district_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LandDistrict', verbose_name='Land District'),
        ),
    ]
