# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0040_auto_20171024_1627'),
        ('gwells', '0043_auto_20171016_2113'),
    ]

    operations = [
    ]
