# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0044_merge_20171025_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitysubmission',
            old_name='final_stick_up',
            new_name='final_casing_stick_up',
        ),
        migrations.RenameField(
            model_name='activitysubmission',
            old_name='orientation',
            new_name='well_orientation',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='final_stick_up',
            new_name='final_casing_stick_up',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='orientation_vertical',
            new_name='well_orientation',
        ),
        migrations.RemoveField(
            model_name='well',
            name='alteration_date',
        ),
        migrations.RemoveField(
            model_name='well',
            name='construction_date',
        ),
        migrations.RemoveField(
            model_name='well',
            name='decommission_date',
        ),
        migrations.RemoveField(
            model_name='well',
            name='well_identification_plate_attached',
        ),
        migrations.AddField(
            model_name='well',
            name='alteration_end_date',
            field=models.DateField(null=True, verbose_name='Alteration End Date'),
        ),
        migrations.AddField(
            model_name='well',
            name='alteration_start_date',
            field=models.DateField(null=True, verbose_name='Alteration Start Date'),
        ),
        migrations.AddField(
            model_name='well',
            name='construction_end_date',
            field=models.DateField(null=True, verbose_name='Construction End Date'),
        ),
        migrations.AddField(
            model_name='well',
            name='construction_start_date',
            field=models.DateField(null=True, verbose_name='Construction Start Date'),
        ),
        migrations.AddField(
            model_name='well',
            name='decommission_end_date',
            field=models.DateField(null=True, verbose_name='Decommission End Date'),
        ),
        migrations.AddField(
            model_name='well',
            name='decommission_start_date',
            field=models.DateField(null=True, verbose_name='Decommission Start Date'),
        ),
        migrations.AddField(
            model_name='well',
            name='where_plate_attached',
            field=models.CharField(blank=True, max_length=500, verbose_name='Where Identification Plate Is Attached'),
        ),
    ]
