# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-28 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0044_auto_20171128_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licencedstatus',
            old_name='well_licenced_status_guid',
            new_name='licenced_status_guid',
        ),
    ]
