# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-29 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0046_auto_20171129_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lithologydescription',
            name='water_bearing_estimated_flow_units',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
