# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-29 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0047_auto_20171129_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lithologydescription',
            name='lithology_observation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Observations'),
        ),
    ]
