# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-29 22:03
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0048_auto_20171129_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lithologydescription',
            name='lithology_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='lithologydescription',
            name='lithology_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='To'),
        ),
    ]
