# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-29 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0050_auto_20171129_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lithologydescription',
            name='water_bearing_estimated_flow_units',
            field=models.ForeignKey(blank=True, db_column='well_yield_unit_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellYieldUnit', verbose_name='Units'),
        ),
    ]
