# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-29 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0052_well_reason_for_decommission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='reason_for_decommission',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Reason for Decomission'),
        ),
    ]
