# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-30 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0055_auto_20171130_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='decommission_details',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Decomission Details'),
        ),
    ]
