# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-30 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0056_well_decommission_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lithologydescription',
            options={'ordering': ['lithology_from', 'lithology_to']},
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='lithology_sequence_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
