# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-30 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0057_auto_20171130_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lithologydescription',
            options={'ordering': ['lithology_sequence_number']},
        ),
    ]
