# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-30 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0058_auto_20171130_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='LithologyMaterial',
            fields=[
                ('who_created', models.CharField(max_length=30)),
                ('when_created', models.DateTimeField(blank=True, null=True)),
                ('who_updated', models.CharField(max_length=30, null=True)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('lithology_material_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('sort_order', models.PositiveIntegerField()),
                ('status_flag', models.BooleanField()),
            ],
            options={
                'db_table': 'gwells_lithology_material',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='lithologydescription',
            name='lithology_material',
            field=models.ForeignKey(blank=True, db_column='lithology_material_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LithologyMaterial', verbose_name='Material'),
        ),
    ]
