# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-01 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0059_auto_20171130_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysubmission',
            name='legal_land_district',
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='land_district',
            field=models.ForeignKey(blank=True, db_column='land_district_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.LandDistrict', verbose_name='Land District'),
        ),
    ]
