# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-04 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0060_auto_20171201_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='comments',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
