# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-08 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0062_auto_20171204_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casing',
            old_name='internal_diameter',
            new_name='diameter',
        ),
    ]
