# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-08 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0063_auto_20171208_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='backfill_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Backfill Material Above Surface Seal'),
        ),
    ]
