# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-13 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0064_auto_20171208_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='decommission_details',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Decommission Details'),
        ),
        migrations.AlterField(
            model_name='well',
            name='decommission_reason',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Reason for Decommission'),
        ),
    ]
