# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-18 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0065_auto_20171213_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='well_class',
            field=models.ForeignKey(db_column='well_class_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellClass', verbose_name='Well Class'),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_class',
            field=models.ForeignKey(db_column='well_class_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellClass', verbose_name='Well Class'),
        ),
    ]
