# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-18 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0065_auto_20171213_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='observation_well_number',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Observation Well Number'),
        ),
    ]
