# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-19 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0067_auto_20171218_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellsubclass',
            name='well_class',
            field=models.ForeignKey(blank=True, db_column='well_class_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.WellClass'),
        ),
    ]
