# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-03 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0069_well_observation_well_in_map_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='observation_well_in_map_hub',
            field=models.NullBooleanField(choices=[(False, 'No'), (True, 'Yes')], default='False', verbose_name='Available in Map Hub'),
        ),
    ]
