# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-04 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0070_auto_20180103_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquiferwell',
            name='aquifer_has_report',
            field=models.NullBooleanField(choices=[(False, 'No'), (True, 'Yes')], default='False', verbose_name='Available in Map Hub'),
        ),
    ]
