apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: gwells-pipeline
    name: gwells-pipeline
    template: gwells-pipeline
  name: gwells-pipeline
  namespace: moe-gwells-tools
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Parallel
  source:
    git:
      ref: master
      uri: 'https://github.com/bcgov/gwells.git'
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  triggers: []
