# Generated by Django 2.2.28 on 2022-12-09 23:25

import django.contrib.gis.db.models.fields
from django.db import migrations
import registries.data_migrations

class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0005_auto_20200317_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.RunPython(
            code=registries.data_migrations.populate_empty_geometries,
            reverse_code=lambda a,b: None #no action needed to reverse
        ),        
    ]
