---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: jenkins
metadata:
  creationTimestamp: null
  name: jenkins
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      as-copy-of: template.${NAME}-slave-user
      as-copy-of/preserve: password
    name: ${NAME}-slave-user
  stringData:
    metadata.name: ${NAME}-slave-user
    password: ${SLAVE_USER_PASSWORD}
    username: jenkins-slave
  type: kubernetes.io/basic-auth
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      as-copy-of: template.${NAME}-github
    name: ${NAME}-github
  stringData:
    metadata.name: ${NAME}-github
    password: ${GH_PASSWORD}
    username: ${GH_USERNAME}
  type: kubernetes.io/basic-auth
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: netapp-file-standard
    name: ${NAME}${SUFFIX}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"${NAME}-controller${SUFFIX}"}}'
    name: ${NAME}${SUFFIX}
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    name: ${NAME}${SUFFIX}_admin
  roleRef:
    name: admin
  subjects:
  - kind: ServiceAccount
    name: ${NAME}${SUFFIX}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    creationTimestamp: null
    name: ${NAME}-controller${SUFFIX}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: ${NAME}-controller${SUFFIX}
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: ${NAME}-controller${SUFFIX}
      spec:
        containers:
        - command:
          - /usr/local/bin/container-entrypoint
          - /usr/local/bin/jenkins-run
          env:
          - name: USE_JAVA_DIAGNOSTICS
            value: "true"
          - name: JENKINS_URL
            value: "https://gwells-${NAME}${SUFFIX}.${ROUTE_HOST_SUFFIX}${ROUTE_PATH}"
          - name: JENKINS_TUNNEL
            value: "${NAME}-controller${SUFFIX}:50000"
          - name: ENV_NAME
            value: ${ENV_NAME}
          - name: ENV_ID
            value: ${ENV_ID}
          - name: APP_TOOLS_NAMESPACE
            valueFrom:
              configMapKeyRef:
                name: ns-config
                key: project.tools
          - name: APP_DEV_NAMESPACE
            valueFrom:
              configMapKeyRef:
                name: ns-config
                key: project.dev
          - name: APP_STAGING_NAMESPACE
            valueFrom:
              configMapKeyRef:
                name: ns-config
                key: project.test
          - name: APP_PROD_NAMESPACE
            valueFrom:
              configMapKeyRef:
                name: ns-config
                key: project.prod
          - name: OCP_PLATFORM
            value: '4'
          - name: JENKINS_DATA
            value: '/var/jenkins-data'
          image: ' '
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 420
            periodSeconds: 360
            timeoutSeconds: 240
          name: jenkins
          ports:
          - containerPort: 50000
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 240
          resources:
            limits:
              cpu: "${CPU_LIMIT}"
              memory: "${MEMORY_LIMIT}"
            requests:
              cpu: "${CPU_REQUEST}"
              memory: "${MEMORY_REQUEST}"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/jenkins-data
            name: jenkins-data
            readOnly: false
          - mountPath: /var/run/pod
            name: pod-metadata
          - mountPath: /run/secrets/jenkins-slave-user
            name: jenkins-slave-user
            readOnly: true
          - mountPath: /run/secrets/github
            name: github
            readOnly: true
          - mountPath: /run/configs/ns
            name: ns-config
            readOnly: true
          - mountPath: /run/configs/jobs
            name: jobs-config
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: ${NAME}${SUFFIX}
        serviceAccountName: ${NAME}${SUFFIX}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: ${NAME}${SUFFIX}
        - downwardAPI:
            items:
            - fieldRef:
                fieldPath: metadata.name
              name: name
              path: name
            - fieldRef:
                fieldPath: metadata.namespace
              name: namespace
              path: namespace
            - fieldRef:
                fieldPath: metadata.labels
              name: labels
              path: labels
            - fieldRef:
                fieldPath: metadata.annotations
              name: annotations
              path: annotations
          name: pod-metadata
        - name: jenkins-slave-user
          secret:
            defaultMode: 420
            secretName: ${NAME}-slave-user
        - name: github
          secret:
            defaultMode: 420
            secretName: ${NAME}-github
        - name: ns-config
          configMap:
            defaultMode: 420
            name: ns-config
        - name: jobs-config
          configMap:
            defaultMode: 420
            name: jobs-config
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - jenkins
        from:
          kind: ImageStreamTag
          name: ${JENKINS_IMAGE_STREAM_NAME}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}-agent${SUFFIX}
  spec:
    replicas: "${{AGENT_REPLICAS}}"
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: ${NAME}-agent${SUFFIX}
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: ${NAME}-agent${SUFFIX}
      spec:
        containers:
        - command:
          - bash
          - -c
          - cd $HOME && java -XshowSettings:vm -version && exec java -jar /usr/lib/jenkins/swarm-client.jar
            -name "$(cat /etc/hostname)" -deleteExistingClients -fsroot "$JENKINS_HOME/$(cat
            /etc/hostname)" -master http://$JENKINS_MASTER_SERVICE:8080 -disableSslVerification
            -username  "$(cat /var/run/secrets/jenkins-slave-user/username)" -passwordFile
            /var/run/secrets/jenkins-slave-user/password -description "$(cat /etc/hostname)"
            -executors ${AGENT_EXECUTORS} -labels '${AGENT_LABELS}' -mode
            'normal' -retry 10 -tunnel $JENKINS_MASTER_SERVICE:50000 -disableClientsUniqueId
          env:
          - name: JENKINS_MASTER_SERVICE
            value: ${NAME}-controller${SUFFIX}
          - name: JAVA_TOOL_OPTIONS
            value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
              -XX:MaxRAMFraction=5 -XX:MaxHeapFreeRatio=20 -XX:MinHeapFreeRatio=10
              -XX:+UseParallelGC -XX:ParallelGCThreads=2
          - name: ENV_NAME
            value: ${ENV_NAME}
          - name: ENV_ID
            value: ${ENV_ID}
          - name: APP_TOOLS_NAMESPACE
            valueFrom:
              configMapKeyRef:
                name: ns-config
                key: project.tools
          - name: APP_DEV_NAMESPACE
            valueFrom:
              configMapKeyRef:
                name: ns-config
                key: project.dev
          - name: APP_STAGING_NAMESPACE
            valueFrom:
              configMapKeyRef:
                name: ns-config
                key: project.test
          - name: APP_PROD_NAMESPACE
            valueFrom:
              configMapKeyRef:
                name: ns-config
                key: project.prod
          - name: APP_PROD_NAMESPACE
            valueFrom:
              configMapKeyRef:
                name: ns-config
                key: project.prod
          - name: OCP_PLATFORM
            value: '4'
          image: ' '
          imagePullPolicy: Always
          name: jenkins
          ports:
          - containerPort: 50000
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/run/pod
            name: pod-metadata
          - mountPath: /run/secrets/jenkins-slave-user
            name: jenkins-slave-user
            readOnly: true
          - mountPath: /run/secrets/github
            name: github
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: ${NAME}${SUFFIX}
        serviceAccountName: ${NAME}${SUFFIX}
        terminationGracePeriodSeconds: 30
        volumes:
        - downwardAPI:
            items:
            - fieldRef:
                fieldPath: metadata.name
              name: name
              path: name
            - fieldRef:
                fieldPath: metadata.namespace
              name: namespace
              path: namespace
            - fieldRef:
                fieldPath: metadata.labels
              name: labels
              path: labels
            - fieldRef:
                fieldPath: metadata.annotations
              name: annotations
              path: annotations
          name: pod-metadata
        - name: jenkins-slave-user
          secret:
            defaultMode: 420
            secretName: ${NAME}-slave-user
        - name: github
          secret:
            defaultMode: 420
            secretName: ${NAME}-github
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - jenkins
          - init
        from:
          kind: ImageStreamTag
          name: ${JENKINS_IMAGE_STREAM_NAME}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${NAME}-controller${SUFFIX}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 50000-tcp
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      deploymentconfig: ${NAME}-controller${SUFFIX}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: ${NAME}-controller${SUFFIX}
  spec:
    host: "gwells-${NAME}${SUFFIX}.${ROUTE_HOST_SUFFIX}"
    path: ${ROUTE_PATH}
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${NAME}-controller${SUFFIX}
      weight: 100
    wildcardPolicy: None
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
- name: SUFFIX
- description: A version used for the image tags
  displayName: version
  name: JENKINS_IMAGE_STREAM_NAME
  required: true
  value: "jenkins-main:v2-latest"
- description: ROUTE_HOST_SUFFIX
  displayName: ROUTE_HOST_SUFFIX
  name: ROUTE_HOST_SUFFIX
  required: true
  value: "apps.silver.devops.gov.bc.ca"
- description: ROUTE_PATH
  displayName: ROUTE_PATH
  name: ROUTE_PATH
  required: true
  value: /
- description: Environment Name
  displayName: ENV_NAME
  name: ENV_NAME
  required: true
  value: prod
- description: Environment ID
  displayName: ENV_ID
  name: ENV_ID
  required: true
  value: prod
- description: SLAVE_USER_PASSWORD
  displayName: SLAVE_USER_PASSWORD
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: SLAVE_USER_PASSWORD
- description: GitHub Username (Same as github secret)
  displayName: GH_USERNAME
  name: GH_USERNAME
  required: true
  value: ""
- description: GitHub Personal Access Token (Same as github secret)
  displayName: GH_PASSWORD
  name: GH_PASSWORD
  required: true
- name: CPU_REQUEST
  description: Minimal CPU needed to run
  displayName: CPU Request
  value: 100m
- name: CPU_LIMIT
  description: Maximum CPU allowed to use
  displayName: CPU Limit
  value: 2000m
- name: MEMORY_REQUEST
  description: Minimal amount of memory needed to run
  displayName: Memory Request
  value: 1Gi
- name: MEMORY_LIMIT
  description: Maximum amount of memory allowed to use
  displayName: Memory Limit
  value: 4Gi
- name: AGENT_REPLICAS
  value: "2"
- name: AGENT_EXECUTORS
  value: "3"
- name: AGENT_LABELS
  value: "Linux rhel rhel7 main build test deploy light"