# Generated by Django 2.2.1 on 2019-05-10 00:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gwells.db_comments.model_mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0081_update_well_disinfect_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linerperforation',
            name='activity_submission',
            field=models.PositiveIntegerField(blank=True, db_column='filing_number', null=True),
        ),
        migrations.CreateModel(
            name='ActivitySubmissionLinerPerforation',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_user', models.CharField(max_length=60)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('liner_perforation_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DecimalField(db_column='liner_perforation_from', decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Perforated From')),
                ('end', models.DecimalField(db_column='liner_perforation_to', decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Perforated To')),
                ('activity_submission', models.ForeignKey(blank=True, db_column='filing_number', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linerperforation_set', to='wells.ActivitySubmission')),
            ],
            options={
                'ordering': ['start', 'end'],
            },
            bases=(models.Model, gwells.db_comments.model_mixins.DBComments),
        ),
    ]
