# Generated by Django 2.2.1 on 2019-05-09 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0081_update_well_disinfect_values'),
        ('wells', '0080_well_licence'),
    ]

    operations = [
    ]
