# Generated by Django 2.2.1 on 2019-05-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0082_merge_20190510_1926'),
        ('wells', '0082_auto_20190509_1930'),
        ('wells', '0080_auto_20190507_2011'),
    ]

    operations = [
    ]
