# Generated by Django 2.2.1 on 2019-05-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0082_auto_20190510_0000'),
        ('wells', '0082_merge_20190510_1926'),
    ]

    operations = [
    ]
