# Generated by Django 2.2.1 on 2019-05-14 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0082_update_ground_elevation'),
        ('wells', '0083_merge_20190513_1939'),
    ]

    operations = [
    ]
