# Generated by Django 2.2.1 on 2019-05-15 23:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0088_remove_well_ems_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='internal_diameter',
            field=models.DecimalField(blank=True, db_column='screen_diameter', decimal_places=2, max_digits=7,
                                      null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))],
                                      verbose_name='Diameter'),
        ),
        migrations.RenameField(
            model_name='screen',
            old_name='internal_diameter',
            new_name='diameter',
        ),
    ]
