# Generated by Django 2.2.1 on 2019-05-23 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0092_auto_20190522_2315'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fieldsprovided',
            table='fields_provided',
        ),
    ]
