# Generated by Django 2.2.1 on 2019-05-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0084_well_licences'),
        ('wells', '0093_auto_20190523_2101'),
    ]

    operations = [
    ]
