# Generated by Django 2.2.1 on 2019-06-04 18:28

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc
import gwells.db_comments.model_mixins
import wells.data_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0096_update_drive_shoe_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundaryEffectCode',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_user', models.CharField(max_length=60)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=utc))),
                ('boundary_effect_code', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'boundary_effect_code',
                'ordering': ['display_order', 'description'],
            },
            bases=(models.Model, gwells.db_comments.model_mixins.DBComments),
        ),
        migrations.RunPython(
            code=wells.data_migrations.load_boundary_effect_codes,
            reverse_code=wells.data_migrations.unload_boundary_effect_codes,
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='boundary_effect',
            field=models.ForeignKey(blank=True, db_column='boundary_effect_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.BoundaryEffectCode', verbose_name='Boundary Effect'),
        ),
        migrations.AlterField(
            model_name='well',
            name='boundary_effect',
            field=models.ForeignKey(blank=True, db_column='boundary_effect_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.BoundaryEffectCode', verbose_name='Boundary Effect'),
        ),
    ]
