# Generated by Django 2.2.2 on 2019-06-19 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0099_update_well_orientation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casing',
            name='drive_shoe',
        ),
    ]
