# Generated by Django 2.2.2 on 2019-06-24 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0100_remove_casing_drive_shoe'),
        ('wells', '0100_auto_20190618_1901'),
    ]

    operations = [
    ]
