# Generated by Django 2.2.9 on 2020-01-31 08:35

from django.db import migrations

# 0106_auto_20200116_2327 needed to be done as it's own migration / transaction
# otherwise PostgreSQL complains: "cannot ALTER TABLE "well" because it has
# pending trigger events"

class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0106_auto_20200116_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='drilling_company',
        ),
        migrations.DeleteModel(
            name='DrillingCompany',
        ),
    ]
