# Generated by Django 2.2.10 on 2020-02-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0107_auto_20200116_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmissionlinerperforation',
            name='activity_submission',
            field=models.ForeignKey(blank=True, db_column='filing_number', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linerperforation_set', to='wells.ActivitySubmission'),
        ),
        migrations.AlterField(
            model_name='casing',
            name='activity_submission',
            field=models.ForeignKey(blank=True, db_column='filing_number', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casing_set', to='wells.ActivitySubmission'),
        ),
        migrations.AlterField(
            model_name='casing',
            name='well',
            field=models.ForeignKey(blank=True, db_column='well_tag_number', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casing_set', to='wells.Well'),
        ),
        migrations.AlterField(
            model_name='decommissiondescription',
            name='activity_submission',
            field=models.ForeignKey(blank=True, db_column='filing_number', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decommission_description_set', to='wells.ActivitySubmission'),
        ),
        migrations.AlterField(
            model_name='decommissiondescription',
            name='well',
            field=models.ForeignKey(blank=True, db_column='well_tag_number', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decommission_description_set', to='wells.Well'),
        ),
        migrations.AlterField(
            model_name='fieldsprovided',
            name='activity_submission',
            field=models.OneToOneField(db_column='filing_number', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='fields_provided', serialize=False, to='wells.ActivitySubmission'),
        ),
        migrations.AlterField(
            model_name='hydraulicproperty',
            name='well',
            field=models.ForeignKey(db_column='well_tag_number', on_delete=django.db.models.deletion.PROTECT, to='wells.Well'),
        ),
        migrations.AlterField(
            model_name='linerperforation',
            name='well',
            field=models.ForeignKey(blank=True, db_column='well_tag_number', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linerperforation_set', to='wells.Well'),
        ),
        migrations.AlterField(
            model_name='lithologydescription',
            name='activity_submission',
            field=models.ForeignKey(blank=True, db_column='filing_number', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lithologydescription_set', to='wells.ActivitySubmission'),
        ),
        migrations.AlterField(
            model_name='lithologydescription',
            name='well',
            field=models.ForeignKey(blank=True, db_column='well_tag_number', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lithologydescription_set', to='wells.Well'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='activity_submission',
            field=models.ForeignKey(blank=True, db_column='filing_number', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='screen_set', to='wells.ActivitySubmission'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='well',
            field=models.ForeignKey(blank=True, db_column='well_tag_number', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='screen_set', to='wells.Well'),
        ),
    ]
