# Generated by Django 2.2.12 on 2020-04-30 19:41

from django.db import migrations

CREATE_GWELLS_WELLS_VIEW_SQL = """
    CREATE VIEW postgis_ftw.gwells_well_view AS
        SELECT
            well_tag_number,
            aquifer_id,
            artesian_flow > 0 AS artesian,
            street_address,
            identification_plate_number,
            ems,
            geom
        FROM well;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0110_delete_legacy_dupes_20200401_2244'),
        ('gwells', '0007_create_postgis_ftw_schema_20200501_2146'),
    ]

    operations = [
        migrations.RunSQL(
            CREATE_GWELLS_WELLS_VIEW_SQL,
        ),
    ]
