# Generated by Django 2.2.13 on 2020-07-28 20:27

from django.db import migrations

ADD_DEWATERING_DRAINAGE_WATER_CLASS_CODE = """
    INSERT INTO well_class_code
        (
            create_user,
            create_date,
            update_user,
            update_date,
            display_order,
            effective_date,
            expiry_date,
            well_class_code,
            description
        )
        VALUES
        (
            'WELLS',
            '2017-07-01 08:00:00+00',
            'WELLS',
            '2017-07-01 08:00:00+00',
            20,
            '2020-01-01 00:00:00+00',
            '9999-12-31 23:59:59+00',
            'DEW_DRA',
            'Dewatering/drainage'
        );
"""

ADD_WELL_SUBCLASS_ENTRIES = """
    INSERT INTO well_subclass_code
        (
            create_user,
            create_date,
            update_user,
            update_date,
            well_subclass_guid,
            well_subclass_code,
            description,
            display_order,
            effective_date,
            expiry_date,
            well_class_code
        )
        VALUES
        (
            'WELLS',
            '2017-07-01 08:00:00+00',
            'WELLS',
            '2017-07-01 08:00:00+00',
            '46300f40-fc6b-4c77-a58e-74472cd69f5d',
            'PERMANENT',
            'Permanent',
            100,
            '2020-01-01 00:00:00+00',
            '9999-12-31 23:59:59+00',
            'DEW_DRA'
        ),
        (
            'WELLS',
            '2017-07-01 08:00:00+00',
            'WELLS',
            '2017-07-01 08:00:00+00',
            '6f124222-ab9e-43c7-89e4-a2b8673611cf',
            'TEMPORARY',
            'Temporary',
            100,
            '2020-01-01 00:00:00+00',
            '9999-12-31 23:59:59+00',
            'DEW_DRA'
        );
"""

class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0117_no_default_coord_code_20200626_2053'),
    ]

    operations = [
        migrations.RunSQL([
            ADD_DEWATERING_DRAINAGE_WATER_CLASS_CODE,
            ADD_WELL_SUBCLASS_ENTRIES,
        ]),
    ]