# Generated by Django 2.2.13 on 2020-07-28 20:28

from django.db import migrations

UPDATE_INTENDED_WATER_USE_CODES = """
    UPDATE well SET intended_water_use_code = 'NA' 
    WHERE well_class_code = 'MONITOR' and intended_water_use_code = 'UNK';
    
    UPDATE well SET 
    intended_water_use_code = 'NA',
    well_class_code = 'MONITOR',
    well_subclass_guid = subquery.well_subclass_guid
    FROM (select well_subclass_guid from well_subclass_code where well_subclass_code = 'PERMANENT' and well_class_code = 'MONITOR') as subquery
    WHERE observation_well_number is not null and obs_well_status_code is not null;

    UPDATE well SET intended_water_use_code = 'NA' 
    WHERE well_class_code = 'MONITOR' and intended_water_use_code = 'OBS'
    and observation_well_number is null and obs_well_status_code is null;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0120_update_water_supply_codes'),
    ]

    operations = [
        migrations.RunSQL([
            UPDATE_INTENDED_WATER_USE_CODES
        ]),
    ]