# Generated by Django 2.2.17 on 2021-02-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0121_update_intended_water_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='licenced_status',
        ),
    ]
