# Generated by Django 2.2.18 on 2021-03-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0127_merge_20210325_2228'),
        ('wells', '0127_remove_null_well_class_code_subclasses_water_1634'),
    ]

    operations = [
    ]
