# Generated by Django 2.2.18 on 2021-04-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    JIRA Ticket WATER-1308
        Description:
            This ticket discusses issues when saving activity submissions.
            An activity submission simply stores the "changes" and only the changes, like a ledger.
            Example: a user edits a well, setting a value such as artesian conditions to false instead of true. Only this
                change would wind up ammending the well record, and the activity submission
                    would only have this (plus auditing/2 others) record.
                If this field was not nullable and the user saved, they would default it to a value of true or false,
                thereby overwriting the well value
            This means all fields except for the auditing columns, filing_number and activity_submission_guid must be nullable.
            If they're not nullable they will default to a value whether they're selected or not, therefore overwriting
            the actual well record data.
        Testing:
            save a well edit on each field, saving after each change. inspect the activity_submission record for that wtn
            ensuring its the only recorded value.
            test this for each field individually!
    """
    dependencies = [
        ('wells', '0131_remove_surface_seal_length_col_water_1687'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='well_orientation',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')],
                                      null=True,
                                      verbose_name='Orientation of Well')
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='well_disinfected',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')],
                                      null=True,
                                      verbose_name='Well Disinfected?')
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='well_activity_type',
            field=models.ForeignKey(blank=True, db_column='well_activity_code', null=True,
                                    on_delete=models.deletion.PROTECT, to='submissions.WellActivityCode',
                                    verbose_name='Type of Work'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='well_publication_status',
            field=models.ForeignKey(blank=True, db_column='well_publication_status_code', null=True,
                                    on_delete=models.deletion.PROTECT, to='wells.WellPublicationStatusCode',
                                    verbose_name='Well Publication Status'),
        )
    ]
