# Generated by Django 2.2.18 on 2021-04-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0132_allow_nulls_activity_submission_water_1308'),
        ('wells', '0132_fix_bad_artesian_conditions_postgis_view_water_1753'),
    ]

    operations = [
    ]
