# Generated by Django 2.2.24 on 2021-08-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0134_alter_well_export_views_water_1545_v2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lithologydescription',
            options={'ordering': ['start', 'end']},
        )
    ]
