# Generated by Django 2.2.28 on 2022-12-15 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0135_auto_20210804_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='technical_report',
            field=models.BooleanField(default=False, verbose_name='Technical Report'),
        ),
        migrations.AddField(
            model_name='fieldsprovided',
            name='technical_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='well',
            name='technical_report',
            field=models.BooleanField(default=False, verbose_name='Technical Report'),
        ),
    ]
