# Generated by Django 2.2.28 on 2023-11-27 21:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0144_auto_20231123_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellattachment',
            old_name='directions_artesian_conditions',
            new_name='directions_artesianconditions',
        ),
    ]
