# Generated by Django 2.2.9 on 2020-01-20 16:17

from django.db import migrations, models
import django.db.models.deletion


def add_not_provided_proof_of_age(apps, schema_editor):
    ProofOfAgeCode = apps.get_model('registries', 'ProofOfAgeCode')

    proof_of_age_code = ProofOfAgeCode(
        create_user='DATALOAD_USER',
        update_user='DATALOAD_USER',
        code='NOTPROVIDED',
        description='Not Provided',
        display_order=3,
        effective_date='2020-01-01T08:00:00Z',
        expiry_date='9999-12-31T23:59:59Z'
    )

    proof_of_age_code.save()


def remove_not_provided_proof_of_age(apps, schema_editor):
    ProofOfAgeCode = apps.get_model('registries', 'ProofOfAgeCode')

    ProofOfAgeCode.objects.get(code='NOTPROVIDED').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('registries', '0001_initial'),
    ]

    operations = [
        # Change max length of proof of age code to 15 to allow longer "NOTPROVIDED" PK
        migrations.AlterField(
            model_name='proofofagecode',
            name='code',
            field=models.CharField(db_column='registries_proof_of_age_code', editable=False, max_length=15, primary_key=True, serialize=False),
        ),
        migrations.RunPython(add_not_provided_proof_of_age, remove_not_provided_proof_of_age),
        migrations.AlterField(
            model_name='registriesapplication',
            name='proof_of_age',
            field=models.ForeignKey(db_column='registries_proof_of_age_code', default='NOTPROVIDED', on_delete=django.db.models.deletion.PROTECT, to='registries.ProofOfAgeCode', verbose_name='Proof of age.'),
            preserve_default=False,
        ),
    ]
