# Generated by Django 2.2.9 on 2020-01-20 16:17

from django.db import migrations, models
import django.db.models.deletion


def add_unknown_proof_of_age(apps, schema_editor):
    ProofOfAgeCode = apps.get_model('registries', 'ProofOfAgeCode')

    proof_of_age_code = ProofOfAgeCode(
        create_user='DATALOAD_USER',
        update_user='DATALOAD_USER',
        code='UNKNOWN',
        description='Unknown',
        display_order=3,
        effective_date='2020-01-01T08:00:00Z',
        expiry_date='9999-12-31T23:59:59Z'
    )

    proof_of_age_code.save()


def remove_unknown_proof_of_age(apps, schema_editor):
    ProofOfAgeCode = apps.get_model('registries', 'ProofOfAgeCode')

    ProofOfAgeCode.objects.get(code='UNKNOWN').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('registries', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_unknown_proof_of_age, remove_unknown_proof_of_age),
        migrations.AlterField(
            model_name='registriesapplication',
            name='proof_of_age',
            field=models.ForeignKey(db_column='registries_proof_of_age_code', default='UNKNOWN', on_delete=django.db.models.deletion.PROTECT, to='registries.ProofOfAgeCode', verbose_name='Proof of age.'),
            preserve_default=False,
        ),
    ]
