# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 00:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationNote',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('org_note_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Company note UUID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(max_length=2000)),
                ('author', models.ForeignKey(db_column='user_guid', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Author reference')),
            ],
            options={
                'db_table': 'registries_organization_note',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email adddress'),
        ),
        migrations.AddField(
            model_name='organizationnote',
            name='organization',
            field=models.ForeignKey(db_column='org_guid', on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='registries.Organization', verbose_name='Company reference'),
        ),
    ]
