# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0002_auto_20180517_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='contact_email',
            new_name='email',
        ),
    ]
