# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 17:11
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):
    engine = settings.DATABASES.get('default').get('engine')
    atomic = engine == 'django.db.backends.postgresql' or engine == 'django.contrib.gis.db.backends.postgis'

    dependencies = [
        ('registries', '0002_auto_20180517_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='contact_email',
            new_name='email',
        ),
    ]
