# Generated by Django 2.2.9 on 2020-01-30 21:21

from django.db import migrations

NS_CERT_GUID = 'e6c6ab53-7ae0-4549-ad2c-d45fce8afc7f'
NB_CERT_GUID = '625af649-28e9-4f79-9154-b7079e0c56ee'

def add_more_certs(apps, schema_editor):
    CertifyingAuthorityCode = apps.get_model('registries', 'CertifyingAuthorityCode')
    AccreditedCertificateCode = apps.get_model('registries', 'AccreditedCertificateCode')
    ActivityCode = apps.get_model('registries', 'ActivityCode')

    new_brunswick = CertifyingAuthorityCode(
        create_user='DATALOAD_USER',
        update_user='DATALOAD_USER',
        cert_auth_code='NB',
        description='Province of New Brunswick',
        effective_date='1970-01-01T08:00:00Z',
        expiry_date='9999-12-31T23:59:59Z'
    )
    new_brunswick.save()

    nova_scotia = CertifyingAuthorityCode(
        create_user='DATALOAD_USER',
        update_user='DATALOAD_USER',
        cert_auth_code='NS',
        description='Province of Nova Scotia',
        effective_date='1970-01-01T08:00:00Z',
        expiry_date='9999-12-31T23:59:59Z'
    )
    nova_scotia.save()

    nb_driller_permit = AccreditedCertificateCode(
        acc_cert_guid=NB_CERT_GUID,
        create_user='DATALOAD_USER',
        update_user='DATALOAD_USER',
        cert_auth=new_brunswick,
        registries_activity=ActivityCode.objects.get(registries_activity_code='DRILL'),
        name='Well Driller’s Permit',
        description='',
        effective_date='2020-01-01T08:00:00Z',
        expiry_date='9999-12-31T23:59:59Z'
    )
    nb_driller_permit.save()

    ns_pump_cert = AccreditedCertificateCode(
        acc_cert_guid=NS_CERT_GUID,
        create_user='DATALOAD_USER',
        update_user='DATALOAD_USER',
        cert_auth=nova_scotia,
        registries_activity=ActivityCode.objects.get(registries_activity_code='PUMP'),
        name='Certificate of Qualification Pump Installer Class I',
        description='',
        effective_date='2020-01-01T08:00:00Z',
        expiry_date='9999-12-31T23:59:59Z'
    )
    ns_pump_cert.save()

def remove_nb_ns_certs(apps, schema_editor):
    CertifyingAuthorityCode = apps.get_model('registries', 'CertifyingAuthorityCode')
    AccreditedCertificateCode = apps.get_model('registries', 'AccreditedCertificateCode')

    AccreditedCertificateCode.objects.get(acc_cert_guid=NB_CERT_GUID).delete()
    AccreditedCertificateCode.objects.get(acc_cert_guid=NS_CERT_GUID).delete()

    CertifyingAuthorityCode.objects.get(cert_auth_code='NB').delete()
    CertifyingAuthorityCode.objects.get(cert_auth_code='NS').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0003_initial_activity_codes_20200130_2121'),
    ]

    operations = [
        migrations.RunPython(add_more_certs, remove_nb_ns_certs),
    ]
