# Generated by Django 2.2.11 on 2020-03-17 17:46

from django.db import migrations

# This query:
#   `SELECT COUNT(*) FROM registries_organization WHERE update_user = 'PROXY_WELLS' or update_user = 'WELLS';`
# Shows there were 531 records found which match the number of companies in:
#   https://apps.nrs.gov.bc.ca/int/jira/secure/attachment/38873/drilling_company.csv
# See: https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-816

# Updates all the old `drilling_company` records that were moved into registries_organization in
# 0106_auto_20200116_2327. Sets the `expiry_date` column to '2020-01-01 00:00:00' and the
# `province_state_code` column to 'OTHER'

UPDATE_OLD_DRILLING_COMPANIES_TO_EXPIRED = """
    UPDATE registries_organization
    SET
        expiry_date = '2020-01-01 00:00:00',
        province_state_code = 'OTHER'
    WHERE
        update_user = 'PROXY_WELLS' OR
        update_user = 'WELLS';
"""

class Migration(migrations.Migration):
    dependencies = [
        ('registries', '0004_add_nb_ns_certs_20200130_2121'),
    ]

    operations = [
        migrations.RunSQL(
            UPDATE_OLD_DRILLING_COMPANIES_TO_EXPIRED,
        ),
    ]
