# Generated by Django 2.1.7 on 2019-03-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0015_auto_20190309_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitycode',
            old_name='expired_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='applicationstatuscode',
            old_name='expired_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='proofofagecode',
            old_name='expired_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='expired_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='registriesremovalreason',
            old_name='expired_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='subactivitycode',
            old_name='expired_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='wellclasscode',
            old_name='expired_date',
            new_name='expiry_date',
        ),
    ]
