# Generated by Django 2.1.7 on 2019-03-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0016_auto_20190326_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accreditedcertificatecode',
            old_name='expired_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='certifyingauthoritycode',
            old_name='expired_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='expired_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='expired_date',
            new_name='expiry_date',
        ),
    ]
