# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 22:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0003_auto_20180517_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfAgeCode',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('registries_proof_of_age_code', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateField(default=datetime.date.today)),
                ('expired_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'ProofOfAgeCodes',
                'db_table': 'registries_proof_of_age_code',
                'ordering': ['display_order', 'description'],
            },
        ),
        migrations.RemoveField(
            model_name='registriesapplication',
            name='over19_ind',
        ),
        migrations.AddField(
            model_name='registriesapplication',
            name='proof_of_age',
            field=models.ForeignKey(db_column='registries_proof_of_age_code', null=True, on_delete=django.db.models.deletion.PROTECT, to='registries.ProofOfAgeCode', verbose_name='Proof of age.'),
        ),
    ]
