# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0004_auto_20180524_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registriesapplicationstatus',
            name='application',
        ),
        migrations.RemoveField(
            model_name='registriesapplicationstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='registriesapplication',
            name='application_outcome_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registriesapplication',
            name='application_outcome_notification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registriesapplication',
            name='application_recieved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registriesapplication',
            name='current_status',
            field=models.ForeignKey(blank=True, db_column='registries_application_status_code', null=True, on_delete=django.db.models.deletion.PROTECT, to='registries.ApplicationStatusCode', verbose_name='Application Status Code Reference'),
        ),
        migrations.DeleteModel(
            name='RegistriesApplicationStatus',
        ),
    ]
