# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0008_auto_20180613_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registriesapplicationstatus',
            name='application',
        ),
        migrations.RemoveField(
            model_name='registriesapplicationstatus',
            name='status',
        ),
        migrations.RemoveField(
            model_name='register',
            name='register_removal_date',
        ),
        migrations.RemoveField(
            model_name='register',
            name='register_removal_reason',
        ),
        migrations.RemoveField(
            model_name='register',
            name='status',
        ),
        migrations.DeleteModel(
            name='RegistriesApplicationStatus',
        ),
        migrations.DeleteModel(
            name='RegistriesStatusCode',
        ),
    ]
