# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 23:15
from __future__ import unicode_literals

from django.db import migrations


def update_application_status(apps, schema_editor):
    ApplicationStatusCode = apps.get_model('registries', 'ApplicationStatusCode')

    code = ApplicationStatusCode.objects.get(code='A')
    code.description = 'Registered'
    code.save()


def revert(apps, schema_editor):
    ApplicationStatusCode = apps.get_model('registries', 'ApplicationStatusCode')

    code = ApplicationStatusCode.objects.get(code='A')
    code.description = 'Approved'
    code.save()


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0009_auto_20180618_2119'),
    ]

    operations = [
        migrations.RunPython(update_application_status, revert)
    ]
