# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 21:19
from __future__ import unicode_literals

from django.db import migrations


def insert_remove_reasons(apps, schema_editor):
    data = {
        'FAILTM': {
            'description': 'Fails to maintain a requirement for registration',
            'display_order': 1
        },
        'NLACT': {
            'description': 'No longer actively working in Canada',
            'display_order': 2
        },
        'NMEET': {
            'description': 'Fails to meet a requirement for registration',
            'display_order': 3
        }
    }
    RegistriesRemovalReason = apps.get_model('registries', 'RegistriesRemovalReason')

    for (key, value) in data.items():
        RegistriesRemovalReason.objects.update_or_create(code=key, defaults=value)


def revert(apps, schema_editor):
    # We don't need to do anything on revert
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0009_auto_20180616_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registriesapplicationstatus',
            name='application',
        ),
        migrations.RemoveField(
            model_name='registriesapplicationstatus',
            name='status',
        ),
        migrations.RemoveField(
            model_name='register',
            name='register_removal_date',
        ),
        migrations.RemoveField(
            model_name='register',
            name='register_removal_reason',
        ),
        migrations.RemoveField(
            model_name='register',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='register',
            name='status',
        ),
        migrations.DeleteModel(
            name='RegistriesApplicationStatus',
        ),
        migrations.DeleteModel(
            name='RegistriesStatusCode',
        ),
        migrations.RunPython(insert_remove_reasons, revert),
    ]
