# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-17 18:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aquifer',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('aquifer_id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, verbose_name='Aquifer ID Number')),
                ('aquifer_name', models.CharField(max_length=100)),
                ('location_description', models.CharField(blank=True, max_length=100, verbose_name='Description of Location')),
                ('area', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Size (square km)')),
                ('litho_stratographic_unit', models.CharField(blank=True, max_length=100, verbose_name='Lithographic Stratographic Unit')),
                ('mapping_year', models.PositiveIntegerField(blank=True, help_text='Use the following format: <YYYY>', null=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2018)], verbose_name='Date of Mapping')),
                ('notes', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Notes on Aquifer, for internal use only.')),
            ],
            options={
                'verbose_name_plural': 'Aquifers',
                'db_table': 'aquifer',
                'ordering': ['aquifer_id'],
            },
        ),
        migrations.CreateModel(
            name='AquiferDemand',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='aquifer_demand_code', max_length=1, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Aquifer Demand Codes',
                'db_table': 'aquifer_demand_code',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AquiferMaterial',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='aquifer_material_code', max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Aquifer Material Codes',
                'db_table': 'aquifer_material_code',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AquiferProductivity',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='aquifer_productivity_code', max_length=1, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Aquifer Productivity Codes',
                'db_table': 'aquifer_productivity_code',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AquiferSubtype',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='aquifer_subtype_code', max_length=3, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aquifer_subtype_code',
            },
        ),
        migrations.CreateModel(
            name='AquiferVulnerability',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='aquifer_vulnerability_code', max_length=1, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Aquifer Vulnerability Codes',
                'db_table': 'aquifer_vulnerability_code',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='QualityConcern',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='quality_concern_code', max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Aquifer Quality Concern Codes',
                'db_table': 'quality_concern_code',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WaterUse',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='water_use_code', max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Aquifer Water Use Codes',
                'db_table': 'water_use_code',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='aquifer',
            name='demand',
            field=models.ForeignKey(blank=True, db_column='aquifer_demand_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aquifers', to='aquifers.AquiferDemand', verbose_name='Demand Reference'),
        ),
        migrations.AddField(
            model_name='aquifer',
            name='known_water_use',
            field=models.ForeignKey(blank=True, db_column='water_use_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aquifers', to='aquifers.WaterUse', verbose_name='Known Water Use Reference'),
        ),
        migrations.AddField(
            model_name='aquifer',
            name='material',
            field=models.ForeignKey(blank=True, db_column='aquifer_material_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aquifers', to='aquifers.AquiferMaterial', verbose_name='Material Reference'),
        ),
        migrations.AddField(
            model_name='aquifer',
            name='productivity',
            field=models.ForeignKey(blank=True, db_column='aquifer_productivity_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aquifers', to='aquifers.AquiferProductivity', verbose_name='Productivity Reference'),
        ),
        migrations.AddField(
            model_name='aquifer',
            name='quality_concert',
            field=models.ForeignKey(blank=True, db_column='quality_concern_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aquifers', to='aquifers.QualityConcern', verbose_name='Quality Concern Reference'),
        ),
        migrations.AddField(
            model_name='aquifer',
            name='subtype',
            field=models.ForeignKey(blank=True, db_column='aquifer_subtype_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aquifers', to='aquifers.AquiferSubtype', verbose_name='Subtype Reference'),
        ),
        migrations.AddField(
            model_name='aquifer',
            name='vulnerability',
            field=models.ForeignKey(blank=True, db_column='aquifer_vulnerability_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aquifers', to='aquifers.AquiferVulnerability', verbose_name='Vulnerability Reference'),
        ),
    ]
