# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 17:02
from __future__ import unicode_literals

from django.db import migrations
import json
from io import open
import os

from aquifers import data_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            data_migrations.load_aquifer_codes, reverse_code=data_migrations.unload_aquifer_codes),
    ]
