# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-03 18:20
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):
    atomic = settings.DATABASES.get('default').get('engine') == 'django.db.backends.postgresql'

    dependencies = [
        ('aquifers', '0005_aquifer_vulnerability_codes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aquifer',
            old_name='quality_concert',
            new_name='quality_concern',
        ),
    ]
