# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0006_auto_20181003_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquifer',
            name='aquifer_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Aquifer ID Number'),
        ),
    ]
