# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0007_auto_20181031_2320'),
    ]

    operations = [
        migrations.RunSQL("alter sequence aquifer_aquifer_id_seq restart with 2000")
    ]
