# Generated by Django 2.1.4 on 2019-01-08 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0008_alter_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquifer',
            name='mapping_year',
            field=models.PositiveIntegerField(blank=True, help_text='Use the following format: <YYYY>', null=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2019)], verbose_name='Date of Mapping'),
        ),
    ]
