# Generated by Django 2.1.7 on 2019-03-07 21:31
import os
import sys

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

from aquifers import data_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0009_auto_20190108_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='AquiferResource',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(db_column='aquifer_resource_id', primary_key=True,
                                        serialize=False, verbose_name='Aquifer Resource Identifier')),
                ('name', models.CharField(max_length=255,
                                          verbose_name='Aquifer Resource Name')),
                ('url', models.URLField(
                    max_length=255,
                    help_text='A resolvable link to the PDF document associated with this aquifer resource.', verbose_name='PDF Document URL')),
                ('aquifer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='resources', to='aquifers.Aquifer')),
            ],
            options={
                'verbose_name_plural': 'Aquifer Resource',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AquiferResourceSection',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='aquifer_resource_section_code',
                                          max_length=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'aquifer_resource_section_code',
                'verbose_name_plural': 'Aquifer Resource Sections',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='aquiferresource',
            name='section',
            field=models.ForeignKey(db_column='aquifer_resource_section_code', help_text='The section (category) of this resource.',
                                    on_delete=django.db.models.deletion.CASCADE, to='aquifers.AquiferResourceSection', verbose_name='Aquifer Resource Section'),
        ),
        migrations.RunPython(
            data_migrations.load_aquifer_resource_sections,
            reverse_code=data_migrations.unload_aquifer_resource_sections
        ),
        migrations.RunPython(
            data_migrations.generate_aquifer_resource,
            reverse_code=data_migrations.generate_aquifer_resource_reverse
        )
    ]
