# Generated by Django 2.1.7 on 2019-03-11 18:20

import django.contrib.gis.db.models.fields
from django.db import migrations
from aquifers.models import Aquifer as NewAquifer


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0011_auto_20190309_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquifer',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(
                null=True, srid=3005),
        ),
    ]
