# Generated by Django 2.1.7 on 2019-03-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0011_auto_20190309_0017'),
        ('aquifers', '0010_auto_20190307_2131'),
    ]

    operations = [
    ]
