# Generated by Django 2.1.7 on 2019-03-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0012_aquifer_geom'),
        ('aquifers', '0012_merge_20190313_1742'),
    ]

    operations = [
    ]
