# Generated by Django 2.1.7 on 2019-03-15 05:02
import datetime

from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc

from aquifers import data_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0013_merge_20190313_1801'),
    ]

    operations = [
        migrations.RunPython(data_migrations.update_aquifer_resource_fields),
    ]
