# Generated by Django 2.1.7 on 2019-03-15 05:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0014_auto_20190315_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquiferresourcesection',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aquiferresourcesection',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=utc)),
        ),
    ]
