# Generated by Django 2.1.7 on 2019-03-15 05:02
from django.db import migrations, models
import django.utils.timezone


from aquifers import data_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0014_auto_20190315_0502'),
    ]

    operations = [
        migrations.RunPython(data_migrations.update_aquifer_resource_fields),
        migrations.AlterField(
            model_name='aquiferresource',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquiferresource',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquiferresource',
            name='update_user',
            field=models.CharField(default='DATALOAD_USER', max_length=60),
        ),
        migrations.AlterField(
            model_name='aquiferresourcesection',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquiferresourcesection',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquiferresourcesection',
            name='update_user',
            field=models.CharField(default='DATALOAD_USER', max_length=60),
        ),
    ]
