# Generated by Django 2.1.7 on 2019-03-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0015_auto_20190315_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquiferresourcesection',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
