# Generated by Django 2.1.8 on 2019-04-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0017_auto_20190326_0240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aquifermaterial',
            options={'ordering': ['code'], 'verbose_name_plural': 'Aquifer Material Codes'},
        ),
        migrations.RemoveField(
            model_name='waterrightslicence',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='waterrightslicence',
            name='aquifer_licence_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Aquifer Licence ID Number'),
        ),
        migrations.AlterField(
            model_name='waterrightspurpose',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
