# Generated by Django 2.1.7 on 2019-03-07 21:31
import os
import sys

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

from aquifers.models import AquiferResource, Aquifer
from gwells.codes import CodeFixture


TESTING = len(sys.argv) > 1 and sys.argv[1] == 'test'


# NOTE: this is unused. It must have been part of an old migration to load data which is no longer needed.
# def aquifer_resources():
#     fixture = '0010_aquifer_resources.json'
#     fixture_path = os.path.join(os.path.dirname(
#         os.path.realpath(__file__)), fixture)
#     return CodeFixture(fixture_path)


# def generate_aquifer_resource_reverse(apps, schema_editor):
#     AquiferResource.objects.filter(
#         url='https://onlinelibrary.wiley.com/doi/abs/10.1002/hyp.7724').delete()


# def generate_aquifer_resource(apps, schema_editor):
#     for aquifer in Aquifer.objects.all():
#         AquiferResource.create(
#             aquifer=aqufier,
#             section_id='I',
#             url='https://onlinelibrary.wiley.com/doi/abs/10.1002/hyp.7724',
#             name='Evaluating the use of a gridded climate surface for modelling groundwater recharge in a semi-arid region',
#         )


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0021_auto_20190502_0551'),
    ]

    # removing operations from this migration...TODO: squash this migration.
    operations = []
