# Generated by Django 2.2.8 on 2019-12-16 21:35

from django.db import migrations


insertGWSWInteractionsSection = """
    INSERT INTO aquifer_resource_section_code (
        aquifer_resource_section_code,
        create_user,
        create_date,
        update_user,
        update_date,
        effective_date,
        expiry_date,
        name,
        description
    )
    VALUES (
        'G',
        'DATALOAD_USER',
        '2020-01-01T08:00:00Z',
        'DATALOAD_USER',
        '2020-01-01T08:00:00Z',
        '1970-01-01T08:00:00Z',
        '9999-12-31T23:59:59Z',
        'Groundwater surface water interactions',
        ''
    )
"""

class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0025_auto_20191121_2152'),
    ]

    operations = [
        migrations.RunSQL(
            [insertGWSWInteractionsSection],
        )
    ]
