# Generated by Django 2.2.10 on 2020-03-02 17:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone
import gwells.db_comments.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0030_vertical_aquifer_extents'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalAquiferExtentsHistory',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_user', models.CharField(max_length=60)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(db_column='vertical_aquifer_extents_history_id', primary_key=True, serialize=False, verbose_name='Vertical Aquifer Extents History Id')),
                ('well_tag_number', models.IntegerField(blank=True, db_column='well_tag_number', null=True)),
                ('aquifer_id', models.IntegerField(db_column='aquifer_id')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name="Geo-referenced location of aquifer's depth")),
                ('start', models.DecimalField(db_column='vertical_aquifer_extent_from', decimal_places=2, max_digits=7, verbose_name='From')),
                ('end', models.DecimalField(blank=True, db_column='vertical_aquifer_extent_to', decimal_places=2, max_digits=7, null=True, verbose_name='To')),
            ],
            options={
                'db_table': 'vertical_aquifer_extents_history',
                'ordering': ['-create_date'],
            },
            bases=(models.Model, gwells.db_comments.model_mixins.DBComments),
        ),
    ]
