# Generated by Django 2.2.12 on 2020-04-30 19:41

from django.db import migrations

CREATE_GWELLS_AQUIFER_VIEW_SQL = """
    CREATE VIEW postgis_ftw.gwells_aquifer_view AS
        SELECT
            aquifer_id,
            aquifer_name,
            area,
            geom
        FROM aquifer;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0032_multi_polygon_20200403_2018'),
        ('gwells', '0007_create_postgis_ftw_schema_20200501_2146'),
    ]

    operations = [
        migrations.RunSQL(
            CREATE_GWELLS_AQUIFER_VIEW_SQL,
        ),
    ]
