# Generated by Django 2.2.12 on 2020-05-22 21:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone

UPDATE_AQUIFER_EFFECTIVE_DATE_SQL = """
    UPDATE aquifer SET effective_date = '2000-01-01';
"""

UPDATE_GWELLS_AQUIFER_VIEW_SQL = """
    DROP VIEW postgis_ftw.gwells_aquifer_view;
    CREATE VIEW postgis_ftw.gwells_aquifer_view AS
        SELECT
            aquifer_id,
            aquifer_name,
            area,
            retire_date <= NOW() AS is_retired,
            effective_date <= NOW() AND expiry_date >= NOW() AS is_published,
            geom
        FROM aquifer;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0034_vector_tile_wally_aquifers_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquifer',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aquifer',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='aquifer',
            name='retire_date',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=utc)),
        ),
        migrations.RunSQL(
            UPDATE_AQUIFER_EFFECTIVE_DATE_SQL,
        ),
        migrations.RunSQL(
            UPDATE_GWELLS_AQUIFER_VIEW_SQL,
        ),
    ]
