# Generated by Django 2.2.17 on 2021-02-02 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0035_aquifer_retire_date_20200522_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquifer',
            name='mapping_year',
            field=models.PositiveIntegerField(blank=True, help_text='Use the following format: <YYYY>', null=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2021)], verbose_name='Date of Mapping'),
        ),
    ]
