# Generated by Django 2.2.18 on 2021-02-24 23:43

import aquifers.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0036_auto_20210202_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquifer',
            name='mapping_year',
            field=models.PositiveIntegerField(blank=True, help_text='Use the following format: <YYYY>', null=True, validators=[django.core.validators.MinValueValidator(1990), aquifers.models.DynamicMaxValueValidator(aquifers.models.get_current_year)], verbose_name='Date of Mapping'),
        ),
    ]
