/* Additional updates to DB stucture, as Python's model.py has limited abilities to do this */

DROP INDEX IF EXISTS bcgs_number_idx CASCADE;
CREATE INDEX bcgs_number_idx ON bcgs_number (bcgs_number);

COMMENT ON TABLE activity_submission IS 'Submission of data and information related to a groundwater wells.';
COMMENT ON TABLE activity_submission_water_quality IS 'Water quality characteristic of the well.';
COMMENT ON TABLE aquifer IS 'A geological formation, a group of geological formations, or a part of one or more geological formations that is groundwater bearing and capable of storing, transmitting and yielding groundwater.';
COMMENT ON TABLE aquifer_demand_code IS 'Describes the level of groundwater use at the time aquifer was mapped; i.e., High, Moderate, Low.';
COMMENT ON TABLE aquifer_material_code IS 'Describes the broad grouping of geological material found in the aquifer, i.e., Sand and Gravel, Sand, Gravel, Bedrock';
COMMENT ON TABLE aquifer_productivity_code IS 'Describes the aquifer''s productivity which represent an aquifers ability to transmit and yield groundwater; i.e., Low, Moderate, High';
COMMENT ON TABLE aquifer_subtype_code IS 'Categorizes an aquifer based on how it was formed geologically (depositional description). Understanding of how aquifers were formed governs important attributes such as their productivity, vulnerability to contamination as well as proximity and likelihood of hydraulic connection to streams.  The code value is a combination of an aquifer type represented by a number and an optional letter representing a more specific aquifer sub-type. E.g. aquifer sub-type code 6b is comprised of the aquifer type number (6: Crystalline bedrock aquifers) and subtype letter (b) specifically described as: Fractured crystalline (igneous intrusive or metamorphic, meta-sedimentary, meta-volcanic, volcanic) rock aquifers.  Code values range from 1a to 6b. ';
COMMENT ON TABLE aquifer_vulnerability_code IS 'Describes an aquifer’s relative intrinsic vulnerability to impacts from human activities on the land surface. Vulnerability is based on: the type, thickness, and extent of geologic materials above the aquifer, depth to water table (or to top of confined aquifer), and type of aquifer materials, i.e., Low, Moderate, High. ';
COMMENT ON TABLE aquifer_well IS 'Cross reference table that connects the well to the aquifer.  It resolves the many to many relationship between wells and aquifers.  One well can be in 1-many aquifers, and one aquifer can have 1-many wells in it.';
COMMENT ON TABLE bcgs_number IS 'Placeholder table comment.';
COMMENT ON TABLE bedrock_material_code IS 'Bedrock material encountered during drilling and reported in lithologic description.';
COMMENT ON TABLE bedrock_material_descriptor_code IS 'An adjective that describes the characteristics of the bedrock material in more detail.';
COMMENT ON TABLE casing IS 'Piping or tubing installed in a well to support the sides of the well.  The casing is comprised of a production (inner tube) and surface (outer tube) and can be made of a variety of materials. ';
COMMENT ON TABLE casing_code IS 'Describes the casing component (piping or tubing installed in a well) as either production (inner tube), surface (outer tube), or open hole.';
COMMENT ON TABLE casing_material_code IS 'Describes the material that the casing is made of.';
COMMENT ON TABLE decommission_method_code IS 'Describes the method used to fill the well to close it permanently.';
COMMENT ON TABLE development_method_code IS 'The methods used to remove the fine sediment and other organic or inorganic material that immediately surrounds the well screen, the drill hole or the intake area at the bottom of the well.  E.g. Air Lifting, Bailing, Jetting, Pumping, Surging.  ''Other'' can also be specified.';
COMMENT ON TABLE drilling_company IS 'Placeholder table comment.';
COMMENT ON TABLE drilling_method_code IS 'Placeholder table comment.';
COMMENT ON TABLE filter_pack_material_code IS 'Placeholder table comment.';
COMMENT ON TABLE filter_pack_material_size_code IS 'Placeholder table comment.';
COMMENT ON TABLE ground_elevation_method_code IS 'Placeholder table comment.';
COMMENT ON TABLE intended_water_use_code IS 'Placeholder table comment.';
COMMENT ON TABLE land_district_code IS 'Placeholder table comment.';
COMMENT ON TABLE licenced_status_code IS 'Placeholder table comment.';
COMMENT ON TABLE liner_material_code IS 'Placeholder table comment.';
COMMENT ON TABLE liner_perforation IS 'Placeholder table comment.';
COMMENT ON TABLE lithology_colour_code IS 'Placeholder table comment.';
COMMENT ON TABLE lithology_description IS 'Placeholder table comment.';
COMMENT ON TABLE lithology_description_code IS 'Placeholder table comment.';
COMMENT ON TABLE lithology_hardness_code IS 'Placeholder table comment.';
COMMENT ON TABLE lithology_material_code IS 'Placeholder table comment.';
COMMENT ON TABLE lithology_moisture_code IS 'Placeholder table comment.';
COMMENT ON TABLE lithology_structure_code IS 'Placeholder table comment.';
COMMENT ON TABLE ltsa_owner IS 'Placeholder table comment.';
COMMENT ON TABLE perforation IS 'Placeholder table comment.';
COMMENT ON TABLE province_state_code IS 'Province or state used for the mailing address for the company';
COMMENT ON TABLE registries_accredited_certificate_code IS 'Describes the valid qualifications or certificates (prescribed qualifications) as issued by the certifying authority; used to register a well driller or well pump installer.  Individuals registered prior to 2006 may have qualified under the grandparenting provision. E.g., Water Well Driller Certificate issued by BC to register an applicant as a Well Driller.';
COMMENT ON TABLE registries_activity_code IS 'Describes the registered individual''s allowable activity on a well; i.e. Well Driller, or Pump Installer.';
COMMENT ON TABLE registries_application_status_code IS 'Describes the statuses that the application for well driller or well pump installer registration goes through, i.e., Pending, Incomplete, Not Approved, Registered';
COMMENT ON TABLE registries_proof_of_age_code IS 'Describes options for what documentation the ministry staff reviewed to verify the applicants age to be over 19. i.e., Drivers, Birth, Passport.';
COMMENT ON TABLE registries_removal_reason_code IS 'Describes reasons why a well driller or well pump installer was removed from the registry i.e.No longer actively working in Canada, Fails to maintain a requirement for registration, Fails to meet a requirement for registration.';
COMMENT ON TABLE registries_subactivity_code IS 'Describes valid sub activities that a registered individual can carry out under each type of activity. E.g. Water Well Driller, Geoexchange Driller.';
COMMENT ON TABLE registries_well_qualification IS 'A cross reference table maintaining the list of valid combinations of registries_subactivity_code and registries_well_class_code.';
COMMENT ON TABLE screen IS 'Placeholder table comment.';
COMMENT ON TABLE screen_assembly_type_code IS 'Placeholder table comment.';
COMMENT ON TABLE screen_bottom_code IS 'Placeholder table comment.';
COMMENT ON TABLE screen_intake_method_code IS 'Placeholder table comment.';
COMMENT ON TABLE screen_material_code IS 'Placeholder table comment.';
COMMENT ON TABLE screen_opening_code IS 'Placeholder table comment.';
COMMENT ON TABLE screen_type_code IS 'Placeholder table comment.';
COMMENT ON TABLE surface_seal_material_code IS 'Placeholder table comment.';
COMMENT ON TABLE surface_seal_method_code IS 'Placeholder table comment.';
COMMENT ON TABLE surficial_material_code IS 'Placeholder table comment.';
COMMENT ON TABLE water_quality_characteristic IS 'Placeholder table comment.';
COMMENT ON TABLE well IS 'Placeholder table comment.';
COMMENT ON TABLE well_activity_code IS 'Placeholder table comment.';
COMMENT ON TABLE well_class_code IS 'Placeholder table comment.';
COMMENT ON TABLE well_status_code IS 'Placeholder table comment.';
COMMENT ON TABLE well_subclass_code IS 'Placeholder table comment.';
COMMENT ON TABLE well_water_quality IS 'Placeholder table comment.';
COMMENT ON TABLE well_yield_unit_code IS 'Placeholder table comment.';
COMMENT ON TABLE yield_estimation_method_code IS 'Placeholder table comment.';


ALTER TABLE bedrock_material_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE bedrock_material_descriptor_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE casing_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE casing_material_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE decommission_method_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE development_method_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE drilling_method_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE filter_pack_material_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE filter_pack_material_size_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE ground_elevation_method_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE intended_water_use_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE land_district_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE licenced_status_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE liner_material_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE lithology_colour_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE lithology_description_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE lithology_hardness_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE lithology_material_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE lithology_moisture_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE lithology_structure_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;
ALTER TABLE obs_well_status_code ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE;

COMMENT ON COLUMN activity_submission.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN activity_submission.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN activity_submission.identification_plate_number IS 'Steel plate with a unique number that is attached to required wells under the groundwater protection regulations such as water supply wells, recharge or injection wells made by drilling or boring, and permanent dewatering wells.';
COMMENT ON COLUMN activity_submission.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN activity_submission.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN activity_submission.water_supply_system_name IS 'Name or identifier given to a well that serves as a water supply system. Often, the name is a reflection of the community or system it serves, e.g. Town of Osoyoos or Keremeos Irrigation District.';
COMMENT ON COLUMN activity_submission.water_supply_system_well_name IS 'The specific name given to a water supply system well. Often, the name reflects which well it is within the system, e.g. Well 1 or South Well';
COMMENT ON COLUMN activity_submission.well_location_description IS 'Descriptive details of a well''s location. E.g. the well is located 20'' south west of the house; or the well is located in the pump house near the pond.';
COMMENT ON COLUMN activity_submission.work_end_date IS 'The date when an activity such as well construction, well alteration, or well decommission was ended.';
COMMENT ON COLUMN activity_submission.work_start_date IS 'The date when an activity such as well construction, well alteration, or well decommission was started.';
COMMENT ON COLUMN aquifer.aquifer_id IS 'System generated sequential number assigned to each aquifer. It is widely used by ground water administration staff as it is the only consistent unique identifier for a mapped aquifer. It is also commonly referred to as Aquifer Number.';
COMMENT ON COLUMN aquifer.aquifer_name IS 'Name assigned for a specific aquifer. Typically derived from geographic names or names in common use, but may also be lithologic or litho-stratigraphic units, e.g. Abbotsford-Sumas, McDougall Creek Deltaic.';
COMMENT ON COLUMN aquifer.area IS 'Approximate size of the aquifer in square kilometers.';
COMMENT ON COLUMN aquifer.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN aquifer.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN aquifer.litho_stratographic_unit IS 'Permeable geologic unit (where available) that comprises the aquifer. It is typically either; the era of deposition, the name of a specific formation and\or the broad material types, e.g., Paleozoic to Mesozoic Era, Cache Creek Complex, Intrusive Rock.';
COMMENT ON COLUMN aquifer.location_description IS 'Brief description of the geographic location of the aquifer. The description is usually referenced to a nearby major natural geographic area or community, e.g., Grand Forks.';
COMMENT ON COLUMN aquifer.mapping_year IS 'The year the aquifer was initially mapped or last updated.';
COMMENT ON COLUMN aquifer.notes IS 'Details about the aquifer that the province deems important to maintain e.g. local knowledge about the aquifer, and decisions for changes.';
COMMENT ON COLUMN aquifer.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN aquifer.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN aquifer_demand_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN aquifer_demand_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN aquifer_demand_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN aquifer_demand_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN aquifer_material_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN aquifer_material_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN aquifer_material_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN aquifer_material_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN aquifer_productivity_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN aquifer_productivity_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN aquifer_productivity_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN aquifer_productivity_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN aquifer_subtype_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN aquifer_subtype_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN aquifer_subtype_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN aquifer_subtype_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN aquifer_vulnerability_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN aquifer_vulnerability_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN aquifer_vulnerability_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN aquifer_vulnerability_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN aquifer_well.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN aquifer_well.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN aquifer_well.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN aquifer_well.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN bcgs_number.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN bcgs_number.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN bcgs_number.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN bcgs_number.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN bedrock_material_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN bedrock_material_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN bedrock_material_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN bedrock_material_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN bedrock_material_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN bedrock_material_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN bedrock_material_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN bedrock_material_descriptor_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN bedrock_material_descriptor_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN bedrock_material_descriptor_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN bedrock_material_descriptor_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN bedrock_material_descriptor_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN bedrock_material_descriptor_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN bedrock_material_descriptor_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN casing.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN casing.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN casing.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN casing.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN casing_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN casing_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN casing_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN casing_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN casing_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN casing_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN casing_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN casing_material_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN casing_material_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN casing_material_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN casing_material_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN casing_material_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN casing_material_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN casing_material_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN decommission_method_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN decommission_method_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN decommission_method_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN decommission_method_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN decommission_method_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN decommission_method_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN decommission_method_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN development_method_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN development_method_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN development_method_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN development_method_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN development_method_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN development_method_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN development_method_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN drilling_company.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN drilling_company.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN drilling_company.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN drilling_company.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN drilling_method_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN drilling_method_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN drilling_method_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN drilling_method_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN drilling_method_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN drilling_method_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN drilling_method_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN filter_pack_material_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN filter_pack_material_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN filter_pack_material_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN filter_pack_material_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN filter_pack_material_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN filter_pack_material_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN filter_pack_material_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN filter_pack_material_size_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN filter_pack_material_size_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN filter_pack_material_size_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN filter_pack_material_size_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN filter_pack_material_size_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN filter_pack_material_size_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN filter_pack_material_size_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN ground_elevation_method_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN ground_elevation_method_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN ground_elevation_method_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN ground_elevation_method_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN ground_elevation_method_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN ground_elevation_method_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN ground_elevation_method_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN gwells_survey.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN gwells_survey.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN gwells_survey.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN gwells_survey.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN hydraulic_property.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN hydraulic_property.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN hydraulic_property.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN intended_water_use_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN intended_water_use_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN intended_water_use_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN intended_water_use_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN intended_water_use_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN intended_water_use_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN intended_water_use_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN land_district_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN land_district_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN land_district_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN land_district_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN land_district_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN land_district_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN land_district_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN licenced_status_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN licenced_status_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN licenced_status_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN licenced_status_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN licenced_status_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN licenced_status_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN licenced_status_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN liner_material_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN liner_material_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN liner_material_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN liner_material_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN liner_material_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN liner_material_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN liner_material_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN liner_perforation.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN liner_perforation.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN liner_perforation.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN liner_perforation.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN lithology_colour_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN lithology_colour_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN lithology_colour_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN lithology_colour_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN lithology_colour_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN lithology_colour_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN lithology_colour_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN lithology_description.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN lithology_description.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN lithology_description.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN lithology_description.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN lithology_description_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN lithology_description_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN lithology_description_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN lithology_description_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN lithology_description_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN lithology_description_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN lithology_description_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN lithology_hardness_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN lithology_hardness_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN lithology_hardness_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN lithology_hardness_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN lithology_hardness_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN lithology_hardness_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN lithology_hardness_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN lithology_material_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN lithology_material_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN lithology_material_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN lithology_material_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN lithology_material_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN lithology_material_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN lithology_material_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN lithology_moisture_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN lithology_moisture_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN lithology_moisture_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN lithology_moisture_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN lithology_moisture_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN lithology_moisture_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN lithology_moisture_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN lithology_structure_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN lithology_structure_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN lithology_structure_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN lithology_structure_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN lithology_structure_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN lithology_structure_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN lithology_structure_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN ltsa_owner.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN ltsa_owner.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN ltsa_owner.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN ltsa_owner.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN obs_well_status_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN obs_well_status_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN obs_well_status_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN obs_well_status_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN obs_well_status_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN obs_well_status_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN obs_well_status_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN online_survey.effective_date IS 'The date and time that record became valid.';
COMMENT ON COLUMN online_survey.expiry_date IS 'The date and time after which the record is no longer valid and should not be used.';
COMMENT ON COLUMN perforation.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN perforation.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN perforation.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN perforation.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN province_state_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN province_state_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN province_state_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN province_state_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN province_state_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN quality_concern_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN quality_concern_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN quality_concern_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN quality_concern_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN registries_accredited_certificate_code.acc_cert_guid IS 'Unique surrogate identifier for the registries_accredited_certificate_code';
COMMENT ON COLUMN registries_accredited_certificate_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN registries_accredited_certificate_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN registries_accredited_certificate_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN registries_accredited_certificate_code.expired_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN registries_accredited_certificate_code.name IS 'Certifications that are recognized by British Columbia for the purposes of registering an individual as a well pump installer or well driller. These certifications determine what type of well the individual is allowed to construct/alter/decomission. Individuals that were registered prior to 2006 did not have to provide a certification and as such they have been Grand-parented in which means they can construct/alter/decomission any type of well. E.g. Geoexchange Driller Certificate, Ground Water Pump Technician Certificate, Grand-parent.';
COMMENT ON COLUMN registries_accredited_certificate_code.registries_activity_code IS 'Codes for valid activities that a registered individual can carry out, i.e. PUMP, DRILL';
COMMENT ON COLUMN registries_accredited_certificate_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN registries_accredited_certificate_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN registries_activity_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN registries_activity_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN registries_activity_code.description IS 'Descriptions of valid activities that a registered individual can carry out, i.e. Pump Installer, Well Driller.';
COMMENT ON COLUMN registries_activity_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN registries_activity_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN registries_activity_code.expired_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN registries_activity_code.registries_activity_code IS 'Codes for valid activities that a registered individual can carry out, i.e. PUMP, DRILL';
COMMENT ON COLUMN registries_activity_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN registries_activity_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN registries_application.application_guid IS 'Unique identifier for the registries_application record.';
COMMENT ON COLUMN registries_application.application_outcome_date IS 'Date that the comptroller decided if the application for registration of a well driller or well pump installer was approved or denied.';
COMMENT ON COLUMN registries_application.application_outcome_notification_date IS 'Date that the individual was notified of the outcome of their application for registration for well driller or well pump installer.';
COMMENT ON COLUMN registries_application.application_recieved_date IS 'Date that the province received an application for registration of a well driller or well pump installer.';
COMMENT ON COLUMN registries_application.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN registries_application.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN registries_application.file_no IS 'Operational Records Classification Systems (ORCS) number. Information schedules used to classify, file, retrieve and dispose of operational records. This number is assigned on creation of a file.';
COMMENT ON COLUMN registries_application.primary_certificate_no IS 'Unique number assigned to the certificate by the certifying organization.';
COMMENT ON COLUMN registries_application.reason_denied IS 'The reason the Comptroller did not approve an individuals application for well driller or well pump installer, for example not meeting the requirements of the application. A brief internal note.';
COMMENT ON COLUMN registries_application.register_guid IS 'Unique identifier for the registries_register record.';
COMMENT ON COLUMN registries_application.registrar_notes IS 'Internal notes documenting communication between an applicant and the province.';
COMMENT ON COLUMN registries_application.removal_date IS 'Date that a registered individual was removed from the register.';
COMMENT ON COLUMN registries_application.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN registries_application.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN registries_application_status_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN registries_application_status_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN registries_application_status_code.description IS 'Description of the status of the application for registration of a well driller or well pump installer. i.e. Registered, Incomplete, Not Approved, Pending';
COMMENT ON COLUMN registries_application_status_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN registries_application_status_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN registries_application_status_code.expired_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN registries_application_status_code.registries_application_status_code IS 'Code for the status of the application for registration of a well driller or well pump installer. i.e. A, I, NA, P';
COMMENT ON COLUMN registries_application_status_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN registries_application_status_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN registries_certifying_authority_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN registries_certifying_authority_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN registries_certifying_authority_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN registries_certifying_authority_code.expired_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN registries_certifying_authority_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN registries_certifying_authority_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN registries_organization.city IS 'City used for mailing address for the company.';
COMMENT ON COLUMN registries_organization.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN registries_organization.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN registries_organization.effective_date IS 'The date and time that record became valid.';
COMMENT ON COLUMN registries_organization.email IS 'The email address for a company, this is different from the email for the individual who is a registered driller or pump installer.';
COMMENT ON COLUMN registries_organization.expired_date IS 'The date and time after which the record is no longer valid and should not be used.';
COMMENT ON COLUMN registries_organization.fax_tel IS 'Fax number used to contact the company';
COMMENT ON COLUMN registries_organization.main_tel IS 'Telephone number used to contact the company';
COMMENT ON COLUMN registries_organization.name IS 'Company''s Doing Business As name.';
COMMENT ON COLUMN registries_organization.postal_code IS 'Postal code used for mailing address for the company';
COMMENT ON COLUMN registries_organization.province_state_code IS 'Province or state used for the mailing address for the company';
COMMENT ON COLUMN registries_organization.street_address IS 'Street address used for mailing address for the company.';
COMMENT ON COLUMN registries_organization.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN registries_organization.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN registries_organization.website_url IS 'The web address associated with the company';
COMMENT ON COLUMN registries_organization_note.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN registries_organization_note.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN registries_organization_note.note IS 'Internal note used for the purposes of conducting business with the company.';
COMMENT ON COLUMN registries_organization_note.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN registries_organization_note.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN registries_person.contact_cell IS 'Cell phone area code and 7 digit number provided by the well driller or well pump installer where they can be contacted.';
COMMENT ON COLUMN registries_person.contact_email IS 'Email address for the well driller or well pump installer.';
COMMENT ON COLUMN registries_person.contact_tel IS 'Land line area code and 7 digit phone number provided by the well driller or well pump installer where they can be contacted.';
COMMENT ON COLUMN registries_person.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN registries_person.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN registries_person.effective_date IS 'The date and time that record became valid.';
COMMENT ON COLUMN registries_person.expired_date IS 'The date and time after which the record is no longer valid and should not be used.';
COMMENT ON COLUMN registries_person.first_name IS 'Legal first name of the well driller or well pump installer who has applied and/or is registered with the province.';
COMMENT ON COLUMN registries_person.pump_installer_orcs_no IS 'Well pump installer''s unique filing number used in the BC government Operational Records Classification Systems (ORCS) filing system. Each person has an ORCS number when a file is started with their correspondence, usually with the application for being registered. Each person can have a unique ORCS number as a well pump installer and as a well driller. E.g. 3800-25/PUMP PRIC W. The standard format for this number is 3800-25/PUMP {first 4 characters of last name} {initial of first name}.';
COMMENT ON COLUMN registries_person.surname IS 'Legal last name of the well driller or well pump installer who has applied and/or is registered with the province.';
COMMENT ON COLUMN registries_person.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN registries_person.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN registries_person.well_driller_orcs_no IS 'Well driller''s unique filing number used in the BC government Operational Records Classification Systems (ORCS) filing system. Each person has an ORCS number when a file is started with their correspondence, usually with the application for being registered. E.g. 3800-25/PUMP DRI W. The standard format for this number is 3800-25/DRI {first 4 characters of last name} {initial of first name}.';
COMMENT ON COLUMN registries_person_note.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN registries_person_note.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN registries_person_note.note IS 'Internal note used for the purposes of conducting business with an applicant.';
COMMENT ON COLUMN registries_person_note.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN registries_person_note.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN registries_proof_of_age_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN registries_proof_of_age_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN registries_proof_of_age_code.description IS 'Descriptions of the valid options for documentation that the ministry staff reviewed to verify the applicants age to be over 19, i.e. Drivers Licence, Birth Certificate, Passport.';
COMMENT ON COLUMN registries_proof_of_age_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN registries_proof_of_age_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN registries_proof_of_age_code.expired_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN registries_proof_of_age_code.registries_proof_of_age_code IS 'List of valid options for what documentation the ministry staff reviewed to verify the applicants age to be over 19. I.e. Drivers, Birth, Passport.';
COMMENT ON COLUMN registries_proof_of_age_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN registries_proof_of_age_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN registries_register.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN registries_register.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN registries_register.register_guid IS 'Unique identifier for the registries_register record.';
COMMENT ON COLUMN registries_register.registration_no IS 'Unique number assigned to the well driller or well pump installer upon registration. Format used: certification type yymmddsequence where sequence is two digits starting with 01 for the first person registered in alphabetical order for that day, and certification type would be ''WD'' well driller and ''WPI'' for well pump installer. E.g. WD 18031001';
COMMENT ON COLUMN registries_register.registries_activity_code IS 'Codes for valid activities that a registered individual can carry out, i.e. PUMP, DRILL';
COMMENT ON COLUMN registries_register.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN registries_register.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN registries_register_note.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN registries_register_note.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN registries_register_note.register_guid IS 'Unique identifier for the registries_register record.';
COMMENT ON COLUMN registries_register_note.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN registries_register_note.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN registries_removal_reason_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN registries_removal_reason_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN registries_removal_reason_code.description IS 'Description of code e.g. NMEET = Fails to meet a requirement for registration.';
COMMENT ON COLUMN registries_removal_reason_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN registries_removal_reason_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN registries_removal_reason_code.expired_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN registries_removal_reason_code.registries_removal_reason_code IS 'Reason why a well driller or well pump installer was removed from the registry i.e. NMEET, FAILTM, NLACT';
COMMENT ON COLUMN registries_removal_reason_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN registries_removal_reason_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN registries_subactivity_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN registries_subactivity_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN registries_subactivity_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN registries_subactivity_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN registries_subactivity_code.expired_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN registries_subactivity_code.registries_activity_code IS 'Codes for valid activities that a registered individual can carry out, i.e. PUMP, DRILL';
COMMENT ON COLUMN registries_subactivity_code.registries_subactivity_code IS 'Codes for valid sub activities that a registered individual can carry out under each type of activity. E.g. GEOTECH, GEOXCHG';
COMMENT ON COLUMN registries_subactivity_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN registries_subactivity_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN registries_well_class_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN registries_well_class_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN registries_well_class_code.description IS 'Description for the registries_class_of_well_code that a driller is allowed to construct/alter/decommission based on the driller''s classification e.g. Closed loop geoexchange well, Dewatering well, Geotechnical well.';
COMMENT ON COLUMN registries_well_class_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN registries_well_class_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN registries_well_class_code.expired_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN registries_well_class_code.registries_well_class_code IS 'Codes for the type of well that a driller is allowed to construct/alter/decommission based on the driller''s classification e.g. CLOS, DEWAT, GEO';
COMMENT ON COLUMN registries_well_class_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN registries_well_class_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN registries_well_qualification.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN registries_well_qualification.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN registries_well_qualification.display_order IS 'The order in which the valid combinations will be displayed on the screen.';
COMMENT ON COLUMN registries_well_qualification.effective_date IS 'The date and time that record became valid.';
COMMENT ON COLUMN registries_well_qualification.expired_date IS 'The date and time after which the record is no longer valid and should not be used.';
COMMENT ON COLUMN registries_well_qualification.registries_well_qualification_guid IS 'The unique identifier for each record.';
COMMENT ON COLUMN registries_well_qualification.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN registries_well_qualification.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN reversion_revision.date_created IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN screen.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN screen.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN screen.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN screen.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN screen_assembly_type_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN screen_assembly_type_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN screen_assembly_type_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN screen_assembly_type_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN screen_assembly_type_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN screen_assembly_type_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN screen_assembly_type_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN screen_bottom_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN screen_bottom_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN screen_bottom_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN screen_bottom_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN screen_bottom_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN screen_bottom_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN screen_bottom_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN screen_intake_method_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN screen_intake_method_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN screen_intake_method_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN screen_intake_method_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN screen_intake_method_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN screen_intake_method_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN screen_intake_method_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN screen_material_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN screen_material_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN screen_material_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN screen_material_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN screen_material_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN screen_material_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN screen_material_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN screen_opening_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN screen_opening_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN screen_opening_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN screen_opening_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN screen_opening_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN screen_opening_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN screen_opening_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN screen_type_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN screen_type_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN screen_type_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN screen_type_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN screen_type_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN screen_type_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN screen_type_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN surface_seal_material_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN surface_seal_material_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN surface_seal_material_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN surface_seal_material_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN surface_seal_material_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN surface_seal_material_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN surface_seal_material_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN surface_seal_method_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN surface_seal_method_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN surface_seal_method_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN surface_seal_method_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN surface_seal_method_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN surface_seal_method_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN surface_seal_method_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN surficial_material_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN surficial_material_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN surficial_material_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN surficial_material_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN surficial_material_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN surficial_material_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN surficial_material_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN water_quality_characteristic.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN water_quality_characteristic.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN water_quality_characteristic.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN water_quality_characteristic.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN water_quality_characteristic.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN water_quality_colour_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN water_quality_colour_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN water_quality_colour_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN water_quality_colour_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN water_use_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN water_use_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN water_use_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN water_use_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN well.alteration_start_date IS 'The date when alteration on a well started.';
COMMENT ON COLUMN well.construction_end_date IS 'The date when well construction ended.';
COMMENT ON COLUMN well.construction_start_date IS 'The date when well construction started.';
COMMENT ON COLUMN well.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN well.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN well.decommission_start_date IS 'The start date of when the well was decommissioned.';
COMMENT ON COLUMN well.identification_plate_number IS 'Steel plate with a unique number that is attached to required wells under the groundwater protection regulations such as water supply wells, recharge or injection wells made by drilling or boring, and permanent dewatering wells.';
COMMENT ON COLUMN well.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN well.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN well.water_supply_system_name IS 'Name or identifier given to a well that serves as a water supply system. Often, the name is a reflection of the community or system it serves; e.g. Town of Osoyoos or Keremeos Irrigation District.';
COMMENT ON COLUMN well.water_supply_system_well_name IS 'The specific name given to a water supply system well. Often, the name reflects which well it is within the system, e.g. Well 1 or South Well';
COMMENT ON COLUMN well.well_identification_plate_attached IS 'Description of where the well identification plate has been attached on or near the well. ';
COMMENT ON COLUMN well.well_location_description IS 'Descriptive details of a well''s location. E.g. the well is located 20'' south west of the house; or the well is located in the pump house near the pond.';
COMMENT ON COLUMN well_activity_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN well_activity_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN well_activity_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN well_activity_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN well_activity_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN well_activity_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN well_activity_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN well_class_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN well_class_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN well_class_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN well_class_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN well_class_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN well_class_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN well_class_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN well_status_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN well_status_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN well_status_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN well_status_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN well_status_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN well_status_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN well_status_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN well_subclass_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN well_subclass_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN well_subclass_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN well_subclass_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN well_subclass_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN well_subclass_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN well_subclass_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN well_yield_unit_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN well_yield_unit_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN well_yield_unit_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN well_yield_unit_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN well_yield_unit_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN well_yield_unit_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN well_yield_unit_code.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN wells_decommissiondescription.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN wells_decommissiondescription.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN wells_decommissiondescription.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN wells_decommissionmaterialcode.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN wells_decommissionmaterialcode.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN wells_decommissionmaterialcode.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN wells_decommissionmaterialcode.update_user IS 'The user who last updated this record in the database.';
COMMENT ON COLUMN yield_estimation_method_code.create_date IS 'Date and time (UTC) when the physical record was created in the database.';
COMMENT ON COLUMN yield_estimation_method_code.create_user IS 'The user who created this record in the database.';
COMMENT ON COLUMN yield_estimation_method_code.display_order IS 'The order in which the codes may display on screen.';
COMMENT ON COLUMN yield_estimation_method_code.effective_date IS 'The date and time that the code became valid and could be used.';
COMMENT ON COLUMN yield_estimation_method_code.expiry_date IS 'The date and time after which the code is no longer valid and should not be used.';
COMMENT ON COLUMN yield_estimation_method_code.update_date IS 'Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.';
COMMENT ON COLUMN yield_estimation_method_code.update_user IS 'The user who last updated this record in the database.';

-- Thu  1 Mar 20:00:30 2018 GW Django doesn't support multi-column PK's
ALTER TABLE well_subclass_code DROP CONSTRAINT IF EXISTS well_subclass_code_uk CASCADE;
ALTER TABLE well_subclass_code ADD CONSTRAINT well_subclass_code_uk UNIQUE (well_class_code, well_subclass_code);
