# Generated by Django 2.2.3 on 2019-07-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0002_auto_20190619_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_page',
            field=models.CharField(choices=[('w', 'well'), ('r', 'registry'), ('s', 'search'), ('a', 'aquifer'), ('u', 'submissions'), ('e', 'staff_edit')], default='w', max_length=1, verbose_name='Page'),
        ),
    ]
