# Generated by Django 2.2.28 on 2022-11-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0007_create_postgis_ftw_schema_20200501_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='silver_keycloak_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.RunSQL(
            '''
            UPDATE profile
            SET silver_keycloak_id = auth_user.username
            FROM auth_user
            WHERE auth_user.id = profile.user_id;
            ''',
            # Column is dropped on reversal anyway, so no need to do anything
            reverse_sql=''
        ),
    ]
