kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: gwells-backend
  namespace: 26e83e-dev
  uid: bf985783-11a8-406b-bd33-4bd8b57acdfc
  resourceVersion: '13796864632'
  generation: 1
  creationTimestamp: '2025-03-25T21:26:05Z'
  labels:
    app: gwells-backend
    app-name: gwells
    appver: gwells-backend
    env-name: development
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
      pre:
        failurePolicy: Abort
        execNewPod:
          command:
            - /usr/bin/container-entrypoint
          env:
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: gwells-pg12-development
                  key: database-name
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: gwells-pg12-development
                  key: database-user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: gwells-pg12-development
                  key: database-password
            - name: PGHOST
              value: gwells-pg12-development
          containerName: gwells-app-development
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - gwells-backend
        from:
          kind: ImageStreamTag
          namespace: 26e83e-tools
          name: 'gwells-production:production'
    - type: ConfigChange
  replicas: 3
  revisionHistoryLimit: 10
  test: false
  selector:
    app: gwells-backend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gwells-backend
    spec:
      containers:
        - name: container
          image: 'image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          env:
            - name: DATABASE_SERVICE_NAME
              value: gwells-pg12-production
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: gwells-pg12-production
                  key: database-name
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: gwells-pg12-production
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gwells-pg12-production
                  key: database-password
            - name: DATABASE_SCHEMA
              value: public
            - name: APP_MODULE
              value: 'wsgi:application'
            - name: APP_HOME
              value: backend
            - name: APP_CONFIG
              value: /opt/app-root/src/backend/gunicorn.ocp4.cfg
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: gwells-django-production
                  key: secret_key
            - name: DJANGO_ADMIN_URL
              valueFrom:
                secretKeyRef:
                  name: gwells-django-production
                  key: admin_url
            - name: DJANGO_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: gwells-django-production
                  key: admin_user
            - name: DJANGO_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gwells-django-production
                  key: admin_password
            - name: E_LICENSING_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gwells-e-licensing-production
                  key: E_LICENSING_AUTH_PASSWORD
            - name: E_LICENSING_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gwells-e-licensing-production
                  key: E_LICENSING_AUTH_USERNAME
            - name: E_LICENSING_URL
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: E_LICENSING_URL
            - name: DJANGO_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: DJANGO_DEBUG
            - name: GDAL_LIBRARY_PATH
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: GDAL_LIBRARY_PATH
            - name: GEOS_LIBRARY_PATH
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: GEOS_LIBRARY_PATH
            - name: S3_AQUIFER_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: S3_AQUIFER_BUCKET
            - name: S3_REGISTRANT_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: S3_REGISTRANT_BUCKET
            - name: S3_PRIVATE_ROOT_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: S3_PRIVATE_ROOT_BUCKET
            - name: S3_PRIVATE_AQUIFER_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: S3_PRIVATE_AQUIFER_BUCKET
            - name: S3_PRIVATE_REGISTRANT_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: S3_PRIVATE_REGISTRANT_BUCKET
            - name: S3_PRIVATE_WELL_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: S3_PRIVATE_WELL_BUCKET
            - name: SSO_CLIENT
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: SSO_CLIENT
            - name: SSO_PUBKEY
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: SSO_PUBKEY
            - name: SSO_AUTH_HOST
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: SSO_AUTH_HOST
            - name: SSO_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: SSO_AUDIENCE
            - name: SSO_REALM
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: SSO_REALM
            - name: SSO_PORT
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: SSO_PORT
            - name: SSO_TEST_CLIENT
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: SSO_TEST_CLIENT
            - name: SSO_TEST_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: SSO_TEST_AUDIENCE
            - name: ENABLE_ADDITIONAL_DOCUMENTS
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: ENABLE_ADDITIONAL_DOCUMENTS
            - name: ENABLE_AQUIFERS_SEARCH
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: ENABLE_AQUIFERS_SEARCH
            - name: APP_CONTEXT_ROOT
              value: gwells
            - name: SESSION_COOKIE_SECURE
              value: 'True'
            - name: CSRF_COOKIE_SECURE
              value: 'True'
            - name: DB_REPLICATE
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: DB_REPLICATE
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-parameters-production
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-parameters-production
                  key: MINIO_SECRET_KEY
            - name: S3_PUBLIC_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-parameters-production
                  key: S3_PUBLIC_ACCESS_KEY
            - name: S3_PUBLIC_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-parameters-production
                  key: S3_PUBLIC_SECRET_KEY
            - name: S3_HOST
              valueFrom:
                secretKeyRef:
                  name: minio-access-parameters-production
                  key: S3_HOST
            - name: S3_ROOT_BUCKET
              valueFrom:
                secretKeyRef:
                  name: minio-access-parameters-production
                  key: S3_ROOT_BUCKET
            - name: S3_PRIVATE_HOST
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: S3_PRIVATE_HOST
            - name: S3_WELL_EXPORT_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: S3_WELL_EXPORT_BUCKET
            - name: S3_PRIVATE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: S3_PRIVATE_BUCKET
            - name: SSO_IDP_HINT
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: SSO_IDP_HINT
            - name: WEB_CONCURRENCY
              value: '4'
            - name: GUNICORN_WORKERS
              value: '4'
            - name: ENFORCE_ENV_VARIABLES
              value: 'False'
            - name: EMAIL_NOTIFICATION_RECIPIENT
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: EMAIL_NOTIFICATION_RECIPIENT
            - name: GEOCODER_ADDRESS_API_BASE
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-production
                  key: GEOCODER_ADDRESS_API_BASE
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
    
status:
  observedGeneration: 1
  details:
    message: config change
    causes:
      - type: ConfigChange
  availableReplicas: 3
  unavailableReplicas: 0
  latestVersion: 1
  updatedReplicas: 3
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2025-03-25T21:26:20Z'
      lastTransitionTime: '2025-03-25T21:26:20Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2025-03-25T21:26:22Z'
      lastTransitionTime: '2025-03-25T21:26:22Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "gwells-backend-1" successfully rolled out
  replicas: 3
  readyReplicas: 3
