kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    description: Defines how to deploy the application server
  resourceVersion: '13683705274'
  name: gwells-backend
  generation: 5
  namespace: 26e83e-dev
  labels:
    app: gwells-backend
    app-name: gwells
    appver: gwells-backend
    env-name: development
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 900
      maxUnavailable: 25%
      maxSurge: 25%
      pre:
        failurePolicy: Abort
        execNewPod:
          command:
          #   - /usr/bin/container-entrypoint
            - /opt/app-root/src/scripts/pre-deploy.sh
          env:
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: gwells-pg12-development
                  key: database-name
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: gwells-pg12-development
                  key: database-user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: gwells-pg12-development
                  key: database-password
            - name: PGHOST
              value: gwells-pg12-development
          containerName: gwells-app-development
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - gwells-backend
        from:
          kind: ImageStreamTag
          namespace: 26e83e-tools
          name: 'gwells-backend:latest'
    - type: ConfigChange
  replicas: 0
  revisionHistoryLimit: 10
  test: false
  selector:
    name: gwells-backend
  template:
    metadata:
      name: gwells-backend
      creationTimestamp: null
      labels:
        appver: gwells-backend
        name: gwells-backend
    spec:
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 750Mi
          readinessProbe:
            httpGet:
              path: /gwells/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          terminationMessagePath: /dev/termination-log
          name: gwells-app-development
          livenessProbe:
            httpGet:
              path: /gwells/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          env:
            - name: DATABASE_SERVICE_NAME
              value: gwells-pg12-development
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: gwells-pg12-development
                  key: database-name
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: gwells-pg12-development
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gwells-pg12-development
                  key: database-password
            - name: DATABASE_SCHEMA
              value: public
            - name: APP_MODULE
              value: 'wsgi:application'
            - name: APP_HOME
              value: backend
            - name: APP_CONFIG
              value: /opt/app-root/src/backend/gunicorn.ocp4.cfg
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: gwells-django-development
                  key: secret_key
            - name: DJANGO_ADMIN_URL
              valueFrom:
                secretKeyRef:
                  name: gwells-django-development
                  key: admin_url
            - name: DJANGO_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: gwells-django-development
                  key: admin_user
            - name: DJANGO_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gwells-django-development
                  key: admin_password
            - name: E_LICENSING_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gwells-e-licensing-development
                  key: E_LICENSING_AUTH_PASSWORD
            - name: E_LICENSING_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gwells-e-licensing-development
                  key: E_LICENSING_AUTH_USERNAME
            - name: E_LICENSING_URL
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: E_LICENSING_URL
            - name: DJANGO_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: DJANGO_DEBUG
            - name: GDAL_LIBRARY_PATH
              value: /usr/lib/ogdi/4.1/libgdal.so
            - name: GEOS_LIBRARY_PATH
              value: /usr/lib/x86_64-linux-gnu/libgeos_c.so
            - name: S3_AQUIFER_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: S3_AQUIFER_BUCKET
            - name: S3_REGISTRANT_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: S3_REGISTRANT_BUCKET
            - name: S3_PRIVATE_ROOT_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: S3_PRIVATE_ROOT_BUCKET
            - name: S3_PRIVATE_AQUIFER_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: S3_PRIVATE_AQUIFER_BUCKET
            - name: S3_PRIVATE_REGISTRANT_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: S3_PRIVATE_REGISTRANT_BUCKET
            - name: S3_PRIVATE_WELL_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: S3_PRIVATE_WELL_BUCKET
            - name: SSO_CLIENT
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: SSO_CLIENT
            - name: SSO_PUBKEY
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: SSO_PUBKEY
            - name: SSO_AUTH_HOST
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: SSO_AUTH_HOST
            - name: SSO_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: SSO_AUDIENCE
            - name: SSO_REALM
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: SSO_REALM
            - name: SSO_PORT
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: SSO_PORT
            - name: SSO_TEST_CLIENT
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: SSO_TEST_CLIENT
            - name: SSO_TEST_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: SSO_TEST_AUDIENCE
            - name: ENABLE_ADDITIONAL_DOCUMENTS
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: ENABLE_ADDITIONAL_DOCUMENTS
            - name: ENABLE_AQUIFERS_SEARCH
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: ENABLE_AQUIFERS_SEARCH
            - name: APP_CONTEXT_ROOT
              value: gwells
            - name: SESSION_COOKIE_SECURE
              value: 'True'
            - name: CSRF_COOKIE_SECURE
              value: 'True'
            - name: DB_REPLICATE
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: DB_REPLICATE
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-parameters-development
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-parameters-development
                  key: MINIO_SECRET_KEY
            - name: S3_PUBLIC_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-parameters-development
                  key: S3_PUBLIC_ACCESS_KEY
            - name: S3_PUBLIC_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-parameters-development
                  key: S3_PUBLIC_SECRET_KEY
            - name: S3_HOST
              valueFrom:
                secretKeyRef:
                  name: minio-access-parameters-development
                  key: S3_HOST
            - name: S3_ROOT_BUCKET
              valueFrom:
                secretKeyRef:
                  name: minio-access-parameters-development
                  key: S3_ROOT_BUCKET
            - name: S3_PRIVATE_HOST
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: S3_PRIVATE_HOST
            - name: S3_WELL_EXPORT_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: S3_WELL_EXPORT_BUCKET
            - name: S3_PRIVATE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: S3_PRIVATE_BUCKET
            - name: SSO_IDP_HINT
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: SSO_IDP_HINT
            - name: WEB_CONCURRENCY
              value: '4'
            - name: GUNICORN_WORKERS
              value: '4'
            - name: ENFORCE_ENV_VARIABLES
              value: 'False'
            - name: EMAIL_NOTIFICATION_RECIPIENT
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: EMAIL_NOTIFICATION_RECIPIENT
            - name: GEOCODER_ADDRESS_API_BASE
              valueFrom:
                configMapKeyRef:
                  name: gwells-global-config-development
                  key: GEOCODER_ADDRESS_API_BASE
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: 'image-registry.openshift-image-registry.svc:5000/26e83e-tools/gwells-backend'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
