kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: gwells-frontend
  namespace: 26e83e-dev
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - gwells-frontend
        from:
          kind: ImageStreamTag
          namespace: 26e83e-tools
          name: 'gwells-application:dev'
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: gwells-frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gwells-frontend
    spec:
      containers:
        - resources:
            limits:
              cpu: 50m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /gwells
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 1
          terminationMessagePath: /dev/termination-log
          name: gwells-frontend
          livenessProbe:
            httpGet:
              path: /gwells
              port: 8080
              scheme: HTTPS
            timeoutSeconds: 90
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 2
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          startupProbe:
            httpGet:
              path: /gwells
              port: 8080
              scheme: HTTPS
            timeoutSeconds: 1
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 45
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
