kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    description: Defines how to build the application
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","metadata":{"annotations":{"description":"Defines how to build the application"},"creationTimestamp":"2025-03-12T23:20:57Z","generation":2,"labels":{"appver":"gwells-dev"},"managedFields":[{"apiVersion":"build.openshift.io/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:description":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:appver":{}}},"f:spec":{"f:failedBuildsHistoryLimit":{},"f:output":{"f:to":{}},"f:resources":{"f:limits":{".":{},"f:cpu":{},"f:memory":{}},"f:requests":{".":{},"f:cpu":{},"f:memory":{}}},"f:runPolicy":{},"f:source":{"f:contextDir":{},"f:git":{".":{},"f:ref":{},"f:uri":{}},"f:type":{}},"f:strategy":{"f:sourceStrategy":{".":{},"f:env":{},"f:from":{}},"f:type":{}},"f:successfulBuildsHistoryLimit":{}}},"manager":"oc","operation":"Update","time":"2025-03-12T23:20:57Z"},{"apiVersion":"build.openshift.io/v1","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:lastVersion":{}}},"manager":"openshift-apiserver","operation":"Update","time":"2025-03-12T23:21:04Z"}],"name":"gwells-frontend-dev","namespace":"26e83e-tools","uid":"2e4fe59c-543d-4476-9740-23de4b41c433"},"spec":{"failedBuildsHistoryLimit":3,"nodeSelector":null,"output":{"to":{"kind":"ImageStreamTag","name":"gwells-application:dev"}},"postCommit":{},"resources":{"limits":{"cpu":"2","memory":"8Gi"},"requests":{"cpu":"1","memory":"4Gi"}},"runPolicy":"SerialLatestOnly","source":{"contextDir":"app","git":{"ref":"pull/2364/head","uri":"https://www.github.com/bcgov/gwells.git"},"type":"Git"},"strategy":{"sourceStrategy":{"env":[{"name":"BUILD_LOGLEVEL","value":"4"},{"name":"PIP_INDEX_URL"},{"name":"UPGRADE_PIP_TO_LATEST","value":"true"},{"name":"JWT_PUBLIC_KEY","value":"-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjpPznS8NO5XNl395Xa/wJyhhMDMJUk8s2wrG/FQ9gZnRaCbm9YFYynZzeehkpTNbb+SsLBnh0Me5DKTSlt0Gm03ULXXW6FZzL3SCE1wTx6Trm+zQ1mx07aGDbv34OtK0HitToajZrnTsGQ0TloVbQladBM74S2K0ooveV7p2qIydFjtR+DTJGiOxSLvts+qsGn/Wr2l939SRpQa/10vpYJgCLsd6Bv/0v23DpmR8WbVkLh8e3rtI0XgsJ0ZFXR80DPt3fXX3gdrNdPRB+hpOR8IZMEUzhqGRg5VXP8Lp+bbaemFanTwlFD3aUfDlOcPekxYqQeEmS6ahA/6vCpjuGwIDAQAB\\n-----END PUBLIC KEY-----"},{"name":"JWT_AUDIENCE","value":"webapp-dev-local"}],"from":{"kind":"ImageStreamTag","name":"gwells-python:v3"}},"type":"Source"},"successfulBuildsHistoryLimit":3},"status":{"lastVersion":1}}
  resourceVersion: '13630197954'
  name: gwells-frontend-dev
  uid: a5b42cca-5a0a-4d4e-8896-1617ce9b64e1
  creationTimestamp: '2025-03-13T20:28:33Z'
  generation: 3
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2025-03-13T20:28:33Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:description': {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:appver': {}
        'f:spec':
          'f:failedBuildsHistoryLimit': {}
          'f:output':
            'f:to': {}
          'f:resources':
            'f:limits':
              .: {}
              'f:cpu': {}
              'f:memory': {}
            'f:requests':
              .: {}
              'f:cpu': {}
              'f:memory': {}
          'f:runPolicy': {}
          'f:source':
            'f:contextDir': {}
            'f:git':
              .: {}
              'f:ref': {}
              'f:uri': {}
            'f:type': {}
          'f:strategy':
            'f:sourceStrategy':
              .: {}
              'f:env': {}
              'f:from': {}
            'f:type': {}
          'f:successfulBuildsHistoryLimit': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2025-03-13T20:29:13Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:lastVersion': {}
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2025-03-13T20:32:31Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:triggers': {}
  namespace: 26e83e-tools
  labels:
    appver: gwells-dev
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'gwells-application:dev'
  resources:
    limits:
      cpu: '2'
      memory: 8Gi
    requests:
      cpu: '1'
      memory: 4Gi
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: "Dockerfile"
      contextDir: "app/frontend"
      env:
        - name: BUILD_LOGLEVEL
          value: '4'
        - name: PIP_INDEX_URL
        - name: UPGRADE_PIP_TO_LATEST
          value: 'true'
        - name: JWT_PUBLIC_KEY
          value: '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjpPznS8NO5XNl395Xa/wJyhhMDMJUk8s2wrG/FQ9gZnRaCbm9YFYynZzeehkpTNbb+SsLBnh0Me5DKTSlt0Gm03ULXXW6FZzL3SCE1wTx6Trm+zQ1mx07aGDbv34OtK0HitToajZrnTsGQ0TloVbQladBM74S2K0ooveV7p2qIydFjtR+DTJGiOxSLvts+qsGn/Wr2l939SRpQa/10vpYJgCLsd6Bv/0v23DpmR8WbVkLh8e3rtI0XgsJ0ZFXR80DPt3fXX3gdrNdPRB+hpOR8IZMEUzhqGRg5VXP8Lp+bbaemFanTwlFD3aUfDlOcPekxYqQeEmS6ahA/6vCpjuGwIDAQAB\n-----END PUBLIC KEY-----'
        - name: JWT_AUDIENCE
          value: webapp-dev-local
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://www.github.com/bcgov/gwells.git'
      ref: release
    contextDir: app
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secretReference:
          name: github-build-webhook
  runPolicy: SerialLatestOnly
status:
  lastVersion: 2
