kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: gwells-frontend
  namespace: 26e83e-tools
  labels:
    appver: gwells
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "gwells-application:latest"
  resources:
    limits:
      cpu: "2"
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 4Gi
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
  strategy:
    type: Docker
    dockerStrategy:
      env:
        - name: BUILD_LOGLEVEL
          value: "4"
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: "https://www.github.com/bcgov/gwells.git"
      ref: main
    contextDir: app/frontend
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secretReference:
          name: github-build-webhook
  runPolicy: SerialLatestOnly
