kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: gwells-frontend
  namespace: 26e83e-test
  labels:
    app: gwells-frontend
    app-name: gwells
    appver: gwells-frontend
    env-name: test
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - gwells-frontend
        from:
          kind: ImageStreamTag
          namespace: 26e83e-tools
          name: "gwells-application:test"
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: gwells-frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gwells-frontend
    spec:
      containers:
        - name: gwells-frontend
          image: "image-registry.openshift-image-registry.svc:5000/26e83e-tools/gwells-application@sha256:1146deaa947715dc3e3be04bc383ab42539996cc9bebc4d9cf4fd304ce1090a9"
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: VITE_FRONTEND_TILE_URL
              value: 'https://gwells-staging.apps.silver.devops.gov.bc.ca/gwells/tiles'
            - name: VITE_AXIOS_BASE_URL
              value: 'https://gwells-backend-26e83e-test.apps.silver.devops.gov.bc.ca/gwells/api/v2/'
          resources:
            limits:
              cpu: 50m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
