apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: gwells-frontend-template
parameters:
  - name: ENV
    description: Use dev, test, or prod
    required: true
# ----------------- DEPLOYMENT -----------------
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: gwells-frontend
      name: gwells-frontend
      annotations:
        image.openshift.io/triggers: '[{"from": {"kind": "ImageStreamTag", "name": "gwells-application:${ENV}",
          "namespace": "26e83e-tools"}, "fieldPath": "spec.template.spec.containers[?(@.name==\"gwells-frontend\")].image",
          "paused": false}]'
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: gwells-frontend
      strategy:
        type: Recreate
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: gwells-frontend
        spec:
          containers:
          - env:
            - name: AXIOS_BASE_URL
              value: https://gwells-backend-26e83e-prod.apps.silver.devops.gov.bc.ca/gwells/api/v2/
            - name: BACKEND_URL
              value: https://gwells-backend-26e83e-prod.apps.silver.devops.gov.bc.ca
            - name: VITE_BACKEND_URL
              value: https://gwells-backend-26e83e-prod.apps.silver.devops.gov.bc.ca
            - name: API_BASE_URL
              value: https://gwells-backend-26e83e-prod.apps.silver.devops.gov.bc.ca/gwells/api/v2/
            image: image-registry.openshift-image-registry.svc:5000/26e83e-tools/gwells-application@sha256:1dafcc329c0023b5e7230cad3a1c89f4373d49735c229758deb2244a69c7839c
            imagePullPolicy: Always
            name: gwells-frontend
            ports:
            - containerPort: 8080
              protocol: TCP
            resources:
              limits:
                cpu: 50m
                memory: 256Mi
              requests:
                cpu: 10m
                memory: 128Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
