{
  "apiVersion": "apps/v1",
  "kind": "Deployment",
  "metadata": {
    "labels": {
      "app": "gwells-production",
      "app-name": "gwells",
      "app.openshift.io/runtime": "postgresql",
      "env-name": "production",
      "template": "postgresql-persistent-template"
    },
    "name": "gwells-pg12-production",
    "namespace": "26e83e-prod",
    "annotations": {
      "image.openshift.io/triggers": "[{\"from\": {\"kind\": \"ImageStreamTag\", \"name\": \"crunchy-postgres-gis:centos7-12.4-3.0-4.5.0\", \"namespace\": \"26e83e-prod\"}, \"fieldPath\": \"spec.template.spec.containers[?(@.name==\\\"postgresql\\\")].image\", \"paused\": false}]"
    }
  },
  "spec": {
    "replicas": 1,
    "revisionHistoryLimit": 10,
    "selector": {
      "matchLabels": {
        "name": "gwells-pg12-production"
      }
    },
    "strategy": {
      "type": "Recreate"
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "appver": "gwells-production",
          "name": "gwells-pg12-production"
        }
      },
      "spec": {
        "containers": [
          {
            "env": [
              {
                "name": "PG_PRIMARY_PORT",
                "value": "5432"
              },
              {
                "name": "CONTAINER_NAME",
                "value": "postgresql"
              },
              {
                "name": "PG_PRIMARY_HOST",
                "value": "gwells-pg12-production"
              },
              {
                "name": "PGDATA_PATH_OVERRIDE",
                "value": "userdata"
              },
              {
                "name": "PGHOST",
                "value": "/tmp"
              },
              {
                "name": "PG_DATABASE",
                "valueFrom": {
                  "secretKeyRef": {
                    "key": "database-name",
                    "name": "gwells-pg12-production"
                  }
                }
              },
              {
                "name": "PG_PASSWORD",
                "valueFrom": {
                  "secretKeyRef": {
                    "key": "database-password",
                    "name": "gwells-pg12-production"
                  }
                }
              },
              {
                "name": "PG_USER",
                "valueFrom": {
                  "secretKeyRef": {
                    "key": "database-user",
                    "name": "gwells-pg12-production"
                  }
                }
              },
              {
                "name": "PG_MODE",
                "valueFrom": {
                  "secretKeyRef": {
                    "key": "PG_MODE",
                    "name": "crunchy-db-credentials"
                  }
                }
              },
              {
                "name": "PG_PRIMARY_PASSWORD",
                "valueFrom": {
                  "secretKeyRef": {
                    "key": "PG_PRIMARY_PASSWORD",
                    "name": "crunchy-db-credentials"
                  }
                }
              },
              {
                "name": "PG_PRIMARY_USER",
                "valueFrom": {
                  "secretKeyRef": {
                    "key": "PG_PRIMARY_USER",
                    "name": "crunchy-db-credentials"
                  }
                }
              },
              {
                "name": "PG_ROOT_PASSWORD",
                "valueFrom": {
                  "secretKeyRef": {
                    "key": "PG_ROOT_PASSWORD",
                    "name": "crunchy-db-credentials"
                  }
                }
              }
            ],
            "image": "image-registry.openshift-image-registry.svc:5000/26e83e-prod/crunchy-postgres-gis@sha256:3e1a64213a15aba1e0a981efa175f88c819699c0f50b99d3f84b8d5706cfa41c",
            "imagePullPolicy": "IfNotPresent",
            "livenessProbe": {
              "failureThreshold": 3,
              "initialDelaySeconds": 30,
              "periodSeconds": 10,
              "successThreshold": 1,
              "tcpSocket": {
                "port": 5432
              },
              "timeoutSeconds": 1
            },
            "name": "postgresql",
            "ports": [
              {
                "containerPort": 5432,
                "protocol": "TCP"
              }
            ],
            "readinessProbe": {
              "exec": {
                "command": [
                  "/usr/bin/env",
                  "bash",
                  "-c",
                  "psql -q -d $PG_DATABASE -c 'SELECT 1'"
                ]
              },
              "failureThreshold": 5,
              "initialDelaySeconds": 30,
              "periodSeconds": 15,
              "successThreshold": 1,
              "timeoutSeconds": 1
            },
            "resources": {
              "limits": {
                "cpu": "2",
                "memory": "4Gi"
              },
              "requests": {
                "cpu": "800m",
                "memory": "4Gi"
              }
            },
            "securityContext": {
              "capabilities": {},
              "privileged": false
            },
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "volumeMounts": [
              {
                "mountPath": "/pgdata",
                "name": "gwells-pg12-production-data"
              },
              {
                "mountPath": "/var/run/postgresql",
                "name": "gwells-pg12-production-run"
              },
              {
                "mountPath": "/pgconf",
                "name": "gwells-pg12-production-setupcfg"
              }
            ]
          }
        ],
        "dnsPolicy": "ClusterFirst",
        "restartPolicy": "Always",
        "schedulerName": "default-scheduler",
        "securityContext": {},
        "terminationGracePeriodSeconds": 30,
        "volumes": [
          {
            "name": "gwells-pg12-production-data",
            "persistentVolumeClaim": {
              "claimName": "gwells-pg12-production"
            }
          },
          {
            "emptyDir": {},
            "name": "gwells-pg12-production-run"
          },
          {
            "configMap": {
              "defaultMode": 420,
              "name": "gwells-pg12-production-setupcfg"
            },
            "name": "gwells-pg12-production-setupcfg"
          }
        ]
      }
    }
  }
}