apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: minio-template
parameters:
  - name: ENV
    description: Use dev, test, or prod
    required: true
# ----------------- DEPLOYMENT -----------------
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        name: gwells-minio-{ENV}
      name: gwells-minio-{ENV}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gwells-{ENV}
      name: gwells-minio-{ENV}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        openshift.openshift.io/restartedAt: "2026-08-05T22:34:51.789Z"
      creationTimestamp: null
      labels:
        app: gwells-{ENV}
        name: gwells-minio-{ENV}
    spec:
      containers:
      - args:
        - /minio-entrypoint.sh server /opt/minio/s3/data
        command:
        - /bin/sh
        - -c
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              key: MINIO_ROOT_USER
              name: gwells-minio-secrets
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MINIO_ROOT_PASSWORD
              name: gwells-minio-secrets
        - name: MINIO_DATA_DIR
          value: /opt/minio/s3/data
        image: image-registry.openshift-image-registry.svc:5000/26e83e-tools/gwells-minio:latest
        imagePullPolicy: Always
        name: gwells-minio-{ENV}
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          limits:
            cpu: 250m
          requests:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/minio/s3/data
          name: minio-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: minio-vol
        persistentVolumeClaim:
          claimName: gwells-minio-{ENV}