kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: gwells-frontend
  namespace: 26e83e-prod
  labels:
    app: gwells-frontend
    app-name: gwells
    appver: gwells-frontend
    env-name: production
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - gwells-frontend
        from:
          kind: ImageStreamTag
          namespace: 26e83e-tools
          name: 'gwells-application:prod'
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: gwells-frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gwells-frontend
    spec:
      containers:
        - name: gwells-frontend
          image: 'image-registry.openshift-image-registry.svc:5000/26e83e-tools/gwells-application@sha256:1dafcc329c0023b5e7230cad3a1c89f4373d49735c229758deb2244a69c7839c'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: AXIOS_BASE_URL
              value: 'https://gwells-backend-26e83e-prod.apps.silver.devops.gov.bc.ca/gwells/api/v2/'
            - name: BACKEND_URL
              value: 'https://gwells-backend-26e83e-prod.apps.silver.devops.gov.bc.ca'
            - name: VITE_BACKEND_URL
              value: 'https://gwells-backend-26e83e-prod.apps.silver.devops.gov.bc.ca'
            - name: API_BASE_URL
              value: 'https://gwells-backend-26e83e-prod.apps.silver.devops.gov.bc.ca/gwells/api/v2/'
          resources:
            limits:
              cpu: 50m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
