{
  "apiVersion": "apps/v1",
  "kind": "Deployment",
  "metadata": {
    "labels": {
      "app": "matomo",
      "name": "matomo-db",
      "service": "matomo-db",
      "template": "matomo-template"
    },
    "name": "matomo-db",
    "namespace": "26e83e-prod",
    "annotations": {
      "image.openshift.io/triggers": "[{\"from\": {\"kind\": \"ImageStreamTag\", \"name\": \"mariadb:prod\", \"namespace\": \"26e83e-tools\"}, \"fieldPath\": \"spec.template.spec.containers[?(@.name==\\\"mariadb\\\")].image\", \"paused\": false}]"
    }
  },
  "spec": {
    "replicas": 1,
    "revisionHistoryLimit": 10,
    "selector": {
      "matchLabels": {
        "name": "matomo-db"
      }
    },
    "strategy": {
      "type": "Recreate"
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "app": "matomo",
          "name": "matomo-db"
        }
      },
      "spec": {
        "containers": [
          {
            "env": [
              {
                "name": "MYSQL_USER",
                "valueFrom": {
                  "secretKeyRef": {
                    "key": "database-user",
                    "name": "matomo-db"
                  }
                }
              },
              {
                "name": "MYSQL_PASSWORD",
                "valueFrom": {
                  "secretKeyRef": {
                    "key": "database-password",
                    "name": "matomo-db"
                  }
                }
              },
              {
                "name": "MYSQL_ROOT_PASSWORD",
                "valueFrom": {
                  "secretKeyRef": {
                    "key": "database-root-password",
                    "name": "matomo-db"
                  }
                }
              },
              {
                "name": "MYSQL_DATABASE",
                "valueFrom": {
                  "secretKeyRef": {
                    "key": "database-name",
                    "name": "matomo-db"
                  }
                }
              }
            ],
            "image": "registry.redhat.io/rhel8/mariadb-103@sha256:363f7f7293cd7040ba610bbea830f3bc71e2d70d1f2540a0926dc683bfff79c9",
            "imagePullPolicy": "IfNotPresent",
            "livenessProbe": {
              "failureThreshold": 3,
              "initialDelaySeconds": 30,
              "periodSeconds": 10,
              "successThreshold": 1,
              "tcpSocket": {
                "port": 3306
              },
              "timeoutSeconds": 1
            },
            "name": "mariadb",
            "ports": [
              {
                "containerPort": 3306,
                "protocol": "TCP"
              }
            ],
            "readinessProbe": {
              "exec": {
                "command": [
                  "/bin/sh",
                  "-i",
                  "-c",
                  "MYSQL_PWD=\"$MYSQL_PASSWORD\" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE -e 'SELECT 1'"
                ]
              },
              "failureThreshold": 3,
              "initialDelaySeconds": 5,
              "periodSeconds": 10,
              "successThreshold": 1,
              "timeoutSeconds": 1
            },
            "resources": {
              "limits": {
                "cpu": "250m",
                "memory": "512Mi"
              },
              "requests": {
                "cpu": "100m",
                "memory": "100Mi"
              }
            },
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "volumeMounts": [
              {
                "mountPath": "/var/lib/mysql/data",
                "name": "matomo-db-data"
              }
            ]
          }
        ],
        "dnsPolicy": "ClusterFirst",
        "restartPolicy": "Always",
        "schedulerName": "default-scheduler",
        "securityContext": {},
        "terminationGracePeriodSeconds": 30,
        "volumes": [
          {
            "name": "matomo-db-data",
            "persistentVolumeClaim": {
              "claimName": "matomo-db"
            }
          }
        ]
      }
    }
  }
}