---
kind: Template
apiVersion: v1
metadata:
  name: gwells-backend-bc
parameters:
- name: NAME
  value: "gwells-minio"
- name: DEST_IMG_NAME
  value: "gwells-minio"
- name: DEST_IMG_TAG
  value: "latest"
- name: SRC_REPO_URL
  value: "https://github.com/BCDevOps/minio-openshift"
- name: SRC_REPO_BRANCH
  value: "master"
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${DEST_IMG_NAME}"
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: "${NAME}"
      name: "${NAME}"
      template: "${NAME}"
    name: "${NAME}"
  spec:
    successfulBuildsHistoryLimit: 3
    failedBuildsHistoryLimit: 3
    triggers:
    - type: ImageChange
    - type: ConfigChange
    runPolicy: SerialLatestOnly
    source:
      contextDir: "/docker"
      git:
        ref: "${SRC_REPO_BRANCH}"
        uri: "${SRC_REPO_URL}"
      type: Git
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: "${DEST_IMG_NAME}:${DEST_IMG_TAG}"
