apiVersion: v1
kind: Template
metadata:
  name: gwells-pg14
  namespace: 26e83e-tools
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      labels:
        name: gwells-pg14
        part-of: gwells
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    spec:
      source:
        type: Git
        git:
          uri: "https://www.github.com/bcgov/gwells.git"
          ref: main
        contextDir: app/database
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: gwells-pg12-development
                  key: database-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gwells-pg12-development
                  key: database-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: gwells-pg12-development
                  key: database-name
      output:
        to:
          kind: ImageStreamTag
          name: 'gwells-pg14:latest'
      successfulBuildsHistoryLimit: 3
      failedBuildsHistoryLimit: 3
      triggers:
        - type: ConfigChange
        - type: GitHub
          github:
            secretReference:
              name: github-build-webhook
