# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Survey Name'),
        ),
    ]
