# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0002_auto_20180207_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_enabled',
            field=models.BooleanField(default=False, verbose_name='Survey Enabled'),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Survey Link'),
        ),
    ]
