# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0004_survey_survey_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_page',
            field=models.CharField(choices=[('w', 'well'), ('r', 'registry'), ('s', 'search')], default='w', max_length=1, verbose_name='Survey Page'),
        ),
    ]
