# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0005_auto_20180212_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_enabled',
            field=models.BooleanField(default=False, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_page',
            field=models.CharField(choices=[('w', 'well'), ('r', 'registry'), ('s', 'search')], default='w', max_length=1, verbose_name='Page'),
        ),
    ]
