# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0006_auto_20180212_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='survey_name',
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_introduction_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Introduction Text'),
        ),
    ]
