# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0003_auto_20180530_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driller',
            name='drilling_company',
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='driller_responsible',
            field=models.ForeignKey(db_column='driller_responsible_guid', on_delete=django.db.models.deletion.PROTECT, to='registries.Person', verbose_name='Person Responsible for Drilling'),
        ),
        migrations.AlterField(
            model_name='wellsubclasscode',
            name='well_class',
            field=models.ForeignKey(blank=True, db_column='well_class_code', null=True, on_delete=django.db.models.deletion.PROTECT, to='gwells.WellClassCode'),
        ),
        migrations.DeleteModel(
            name='Driller',
        ),
    ]
