# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwells', '0003_auto_20180530_2330'),
    ]

    operations = [
        migrations.RenameModel('ActivitySubmission', 'wells_ActivitySubmission'),
    ]

    # def forward(self, orm):
    #     db.rename_table('gwells_ActivitySubmission', 'wells_ActivitySubmission')

    # def bakwards(self, orm):
    #     db.rename_table('wells_ActivitySubmission', 'gwells_ActivitySubmission')

    # operations = [
    #     migrations.RenameModel('ActivitySubmission',''
    #     ),
    #     migrations.DeleteModel(
    #         name='AquiferWell',
    #     ),
    #     migrations.DeleteModel(
    #         name='BCGS_Numbers',
    #     ),
    #     migrations.DeleteModel(
    #         name='Casing',
    #     ),
    #     migrations.DeleteModel(
    #         name='CasingCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='CasingMaterialCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='DecommissionMethodCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='DevelopmentMethodCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='Driller',
    #     ),
    #     migrations.DeleteModel(
    #         name='DrillingCompany',
    #     ),
    #     migrations.DeleteModel(
    #         name='DrillingMethodCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='FilterPackMaterialCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='FilterPackMaterialSizeCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='GroundElevationMethodCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='IntendedWaterUseCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='LandDistrictCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='LicencedStatusCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='LinerMaterialCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='LinerPerforation',
    #     ),
    #     migrations.DeleteModel(
    #         name='LtsaOwner',
    #     ),
    #     migrations.DeleteModel(
    #         name='ObsWellStatusCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='Perforation',
    #     ),
    #     migrations.DeleteModel(
    #         name='ProductionData',
    #     ),
    #     migrations.DeleteModel(
    #         name='Screen',
    #     ),
    #     migrations.DeleteModel(
    #         name='SurfaceSealMaterialCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='SurfaceSealMethodCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='WaterQualityCharacteristic',
    #     ),
    #     migrations.DeleteModel(
    #         name='Well',
    #     ),
    #     migrations.DeleteModel(
    #         name='WellActivityCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='WellClassCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='WellStatusCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='WellSubclassCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='WellYieldUnitCode',
    #     ),
    #     migrations.DeleteModel(
    #         name='YieldEstimationMethodCode',
    #     ),
    # ]
