# Generated by Django 2.1.8 on 2019-04-09 22:38

import aquifers.data_migrations
import datetime
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aquifer',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('aquifer_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Aquifer ID Number')),
                ('aquifer_name', models.CharField(max_length=100)),
                ('location_description', models.CharField(blank=True, max_length=100, verbose_name='Description of Location')),
                ('area', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Size (square km)')),
                ('litho_stratographic_unit', models.CharField(blank=True, max_length=100, verbose_name='Lithographic Stratographic Unit')),
                ('mapping_year', models.PositiveIntegerField(blank=True, help_text='Use the following format: <YYYY>', null=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2018)], verbose_name='Date of Mapping')),
                ('notes', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Notes on Aquifer, for internal use only.')),
            ],
            options={
                'verbose_name_plural': 'Aquifers',
                'db_table': 'aquifer',
                'ordering': ['aquifer_id'],
            },
        ),
        migrations.CreateModel(
            name='AquiferDemand',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='aquifer_demand_code', max_length=1, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Aquifer Demand Codes',
                'db_table': 'aquifer_demand_code',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AquiferMaterial',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='aquifer_material_code', max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Aquifer Material Codes',
                'db_table': 'aquifer_material_code',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AquiferProductivity',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='aquifer_productivity_code', max_length=1, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Aquifer Productivity Codes',
                'db_table': 'aquifer_productivity_code',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AquiferSubtype',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='aquifer_subtype_code', max_length=3, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aquifer_subtype_code',
            },
        ),
        migrations.CreateModel(
            name='QualityConcern',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='quality_concern_code', max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Aquifer Quality Concern Codes',
                'db_table': 'quality_concern_code',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WaterUse',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='water_use_code', max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Aquifer Water Use Codes',
                'db_table': 'water_use_code',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='aquifer',
            name='demand',
            field=models.ForeignKey(blank=True, db_column='aquifer_demand_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aquifers', to='aquifers.AquiferDemand', verbose_name='Demand Reference'),
        ),
        migrations.AddField(
            model_name='aquifer',
            name='known_water_use',
            field=models.ForeignKey(blank=True, db_column='water_use_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aquifers', to='aquifers.WaterUse', verbose_name='Known Water Use Reference'),
        ),
        migrations.AddField(
            model_name='aquifer',
            name='material',
            field=models.ForeignKey(blank=True, db_column='aquifer_material_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aquifers', to='aquifers.AquiferMaterial', verbose_name='Material Reference'),
        ),
        migrations.AddField(
            model_name='aquifer',
            name='productivity',
            field=models.ForeignKey(blank=True, db_column='aquifer_productivity_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aquifers', to='aquifers.AquiferProductivity', verbose_name='Productivity Reference'),
        ),
        migrations.AddField(
            model_name='aquifer',
            name='quality_concert',
            field=models.ForeignKey(blank=True, db_column='quality_concern_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aquifers', to='aquifers.QualityConcern', verbose_name='Quality Concern Reference'),
        ),
        migrations.AddField(
            model_name='aquifer',
            name='subtype',
            field=models.ForeignKey(blank=True, db_column='aquifer_subtype_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aquifers', to='aquifers.AquiferSubtype', verbose_name='Subtype Reference'),
        ),
        migrations.RunPython(
            code=aquifers.data_migrations.load_aquifer_codes,
            reverse_code=aquifers.data_migrations.unload_aquifer_codes,
        ),
        migrations.AlterField(
            model_name='aquifer',
            name='aquifer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aquifer',
            name='litho_stratographic_unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lithographic Stratographic Unit'),
        ),
        migrations.AlterField(
            model_name='aquifer',
            name='location_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description of Location'),
        ),
        migrations.CreateModel(
            name='AquiferVulnerabilityCode',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='aquifer_vulnerability_code', max_length=1, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Aquifer Vulnerability Codes',
                'db_table': 'aquifer_vulnerability_code',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='aquifer',
            name='vulnerability',
            field=models.ForeignKey(blank=True, db_column='aquifer_vulnerablity_code', null=True, on_delete=django.db.models.deletion.PROTECT, to='aquifers.AquiferVulnerabilityCode', verbose_name='Aquifer Vulnerabiliy'),
        ),
        migrations.RunPython(
            code=aquifers.data_migrations.load_aquifer_vulnerability_codes,
            reverse_code=aquifers.data_migrations.unload_aquifer_vulnerability_codes,
        ),
        migrations.RenameField(
            model_name='aquifer',
            old_name='quality_concert',
            new_name='quality_concern',
        ),
        migrations.AlterField(
            model_name='aquifer',
            name='aquifer_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Aquifer ID Number'),
        ),
        migrations.RunPython(
            code=aquifers.data_migrations.alter_aquifer_sequence,
            reverse_code=aquifers.data_migrations.revert_aquifer_sequence,
        ),
        migrations.AlterField(
            model_name='aquifer',
            name='mapping_year',
            field=models.PositiveIntegerField(blank=True, help_text='Use the following format: <YYYY>', null=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2019)], verbose_name='Date of Mapping'),
        ),
        migrations.AlterField(
            model_name='aquifer',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquifer',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquiferdemand',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquiferdemand',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquiferdemand',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aquiferdemand',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquifermaterial',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquifermaterial',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquifermaterial',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aquifermaterial',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquiferproductivity',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquiferproductivity',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquiferproductivity',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aquiferproductivity',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquifersubtype',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquifersubtype',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquifersubtype',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aquifersubtype',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquifervulnerabilitycode',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquifervulnerabilitycode',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquifervulnerabilitycode',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aquifervulnerabilitycode',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='qualityconcern',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='qualityconcern',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='qualityconcern',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='qualityconcern',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wateruse',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wateruse',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wateruse',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wateruse',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(
            code=aquifers.data_migrations.update_user_fields,
            reverse_code=aquifers.data_migrations.reverse_update_user_fields,
        ),
        migrations.AlterField(
            model_name='aquifer',
            name='update_user',
            field=models.CharField(default='DATALOAD_USER', max_length=60),
        ),
        migrations.AlterField(
            model_name='aquiferdemand',
            name='update_user',
            field=models.CharField(default='DATALOAD_USER', max_length=60),
        ),
        migrations.AlterField(
            model_name='aquifermaterial',
            name='update_user',
            field=models.CharField(default='DATALOAD_USER', max_length=60),
        ),
        migrations.AlterField(
            model_name='aquiferproductivity',
            name='update_user',
            field=models.CharField(default='DATALOAD_USER', max_length=60),
        ),
        migrations.AlterField(
            model_name='aquifersubtype',
            name='update_user',
            field=models.CharField(default='DATALOAD_USER', max_length=60),
        ),
        migrations.AlterField(
            model_name='aquifervulnerabilitycode',
            name='update_user',
            field=models.CharField(default='DATALOAD_USER', max_length=60),
        ),
        migrations.AlterField(
            model_name='qualityconcern',
            name='update_user',
            field=models.CharField(default='DATALOAD_USER', max_length=60),
        ),
        migrations.AlterField(
            model_name='wateruse',
            name='update_user',
            field=models.CharField(default='DATALOAD_USER', max_length=60),
        ),
        migrations.CreateModel(
            name='AquiferResource',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(db_column='aquifer_resource_id', primary_key=True, serialize=False, verbose_name='Aquifer Resource Identifier')),
                ('name', models.CharField(max_length=255, verbose_name='Aquifer Resource Name')),
                ('url', models.URLField(help_text='A resolvable link to the PDF document associated with this aquifer resource.', max_length=255, verbose_name='PDF Document URL')),
                ('aquifer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='aquifers.Aquifer')),
            ],
            options={
                'verbose_name_plural': 'Aquifer Resource',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AquiferResourceSection',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(max_length=60, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_column='aquifer_resource_section_code', max_length=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'aquifer_resource_section_code',
                'verbose_name_plural': 'Aquifer Resource Sections',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='aquiferresource',
            name='section',
            field=models.ForeignKey(db_column='aquifer_resource_section_code', help_text='The section (category) of this resource.', on_delete=django.db.models.deletion.CASCADE, to='aquifers.AquiferResourceSection', verbose_name='Aquifer Resource Section'),
        ),
        migrations.RunPython(
            code=aquifers.data_migrations.load_aquifer_resource_sections,
            reverse_code=aquifers.data_migrations.unload_aquifer_resource_sections,
        ),
        migrations.RunPython(
            code=aquifers.data_migrations.generate_aquifer_resource,
            reverse_code=aquifers.data_migrations.generate_aquifer_resource_reverse,
        ),
        migrations.AddField(
            model_name='aquifer',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=3005),
        ),
        migrations.RunPython(
            code=aquifers.data_migrations.update_aquifer_resource_fields,
        ),
        migrations.RunPython(
            code=aquifers.data_migrations.update_aquifer_resource_fields,
        ),
        migrations.AlterField(
            model_name='aquiferresource',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquiferresource',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquiferresource',
            name='update_user',
            field=models.CharField(default='DATALOAD_USER', max_length=60),
        ),
        migrations.AlterField(
            model_name='aquiferresourcesection',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquiferresourcesection',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aquiferresourcesection',
            name='update_user',
            field=models.CharField(default='DATALOAD_USER', max_length=60),
        ),
        migrations.AddField(
            model_name='aquiferresourcesection',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aquiferresourcesection',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='aquiferresourcesection',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='aquifer',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='aquiferdemand',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='aquifermaterial',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='aquiferproductivity',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='aquiferresource',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='aquiferresourcesection',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='aquifersubtype',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='aquifervulnerabilitycode',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='qualityconcern',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='wateruse',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
    ]
