# Generated by Django 2.1.8 on 2019-04-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0018_auto_20190407_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterrightslicence',
            name='well',
        ),
    ]
