# Generated by Django 2.1.8 on 2019-05-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0020_aquifer_geom_simplified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterrightslicence',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='waterrightspurpose',
            name='update_user',
            field=models.CharField(max_length=60),
        ),
    ]
