# Generated by Django 2.2.1 on 2019-05-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0083_remove_well_licence'),
        ('aquifers', '0022_add_aquifer_resources'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaterRightsLicence',
        ),
    ]
