# Generated by Django 2.2.10 on 2020-02-13 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0027_auto_20200107_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquifer',
            name='mapping_year',
            field=models.PositiveIntegerField(blank=True, help_text='Use the following format: <YYYY>', null=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2020)], verbose_name='Date of Mapping'),
        ),
    ]
