# Generated by Django 2.2.9 on 2020-02-06 16:51

from django.db import migrations


updateAquiferArea = """
    UPDATE aquifer SET area=ROUND(ST_AREA(geom)::numeric / 1000000, 1);
"""

class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0028_auto_20200213_1741'),
    ]

    operations = [
        migrations.RunSQL(
            [updateAquiferArea],
        )
    ]
