# Generated by Django 2.2.10 on 2020-02-13 22:29

from decimal import Decimal
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gwells.db_comments.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0108_auto_20200213_1741'),
        ('aquifers', '0029_aquifer_area_20200206_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalAquiferExtent',
            fields=[
                ('create_user', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_user', models.CharField(max_length=60)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(db_column='vertical_aquifer_extent_id', primary_key=True, serialize=False, verbose_name='VerticalAquiferExtent Resource Identifier')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=False, null=False, srid=4326, verbose_name="Geo-referenced location of aquifer's depth")),
                ('start', models.DecimalField(blank=False, db_column='vertical_aquifer_extent_from', decimal_places=2, max_digits=7, null=False, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='From')),
                ('end', models.DecimalField(blank=True, db_column='vertical_aquifer_extent_to', decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='To')),
                ('aquifer', models.ForeignKey(blank=False, db_column='aquifer_id', null=False, on_delete=django.db.models.deletion.PROTECT, to='aquifers.Aquifer')),
                ('well', models.ForeignKey(blank=True, db_column='well_tag_number', null=True, on_delete=django.db.models.deletion.PROTECT, to='wells.Well')),
            ],
            options={
                'verbose_name_plural': 'VerticalAquiferExtent',
                'db_table': 'vertical_aquifer_extents',
                'ordering': ['start'],
            },
            bases=(models.Model, gwells.db_comments.model_mixins.DBComments),
        ),
    ]
