# Generated by Django 2.2.12 on 2020-04-03 20:18

import django.contrib.gis.db.models.fields
from django.db import migrations


ALTER_AQUIFER_GEOM_TO_MULTIPOLYGON = """
    ALTER TABLE aquifer ALTER COLUMN geom type geometry(MultiPolygon, 3005) using ST_Multi(geom);
    ALTER TABLE aquifer ALTER COLUMN geom_simplified type geometry(MultiPolygon, 4326) using ST_Multi(geom_simplified);
"""

class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0031_verticalaquiferextentshistory'),
    ]

    operations = [
        migrations.RunSQL(
            ALTER_AQUIFER_GEOM_TO_MULTIPOLYGON,
        ),
        migrations.AlterField(
            model_name='aquifer',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='aquifer',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
