# Generated by Django 2.2.28 on 2022-11-29 02:22

from django.db import migrations

UPDATE_AQUIFER_RESOURCE_SECTION = """
    UPDATE aquifer_resource_section_code 
    SET name = 'Drilling and operation advisory'
    WHERE name = 'Artesian advisory';
"""

REVERSE_UPDATE_AQUIFER_RESOURCE_SECTION = """
    UPDATE aquifer_resource_section_code
    SET name = 'Artesian advisory'
    WHERE name = 'Drilling and operation advisory';
"""

class Migration(migrations.Migration):

    dependencies = [
        ('aquifers', '0037_auto_20210224_2343'),
    ]

    operations = [
        migrations.RunSQL(
          UPDATE_AQUIFER_RESOURCE_SECTION,
          REVERSE_UPDATE_AQUIFER_RESOURCE_SECTION
        )
    ]
