export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'
export const SET_LIST_ERROR = 'SET_LIST_ERROR'
export const SET_USER = 'SET_USER'
export const SET_CITY_LIST = 'SET_CITY_LIST'
export const SET_DRILLER_LIST = 'SET_DRILLER_LIST'
export const SET_DRILLER = 'SET_DRILLER'
export const SET_KEYCLOAK = 'SET_KEYCLOAK'
