export const SET_LOADING = 'setLoading'
export const SET_ERROR = 'setError'
export const SET_LIST_ERROR = 'setListError'
export const SET_USER = 'setUser'
export const SET_CITY_LIST = 'setCityList'
export const SET_DRILLER_LIST = 'setDrillerList'
export const SET_DRILLER = 'setDriller'
